### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by jcubic** [github/linguist#1020]
I have project with [SVG icons](https://github.com/jcubic/Clarity) and it show that 100% of it is in shell.

**Comment by arfon** [comment]
SVG is now detected by Linguist (https://github.com/github/linguist/pull/2097) but we've stuck with `data` for now which means it won't contribute to the language statistics. Please take a look at the discussion in https://github.com/github/linguist/pull/2097 for background.

**Comment by jcubic** [comment]
Is it possible to add a way to set the file as language in .gitattributes?

**Comment by jcubic** [comment]
@arfon Just found that one of my repo is in HTML. Is it possible to set data file as markup? Why HTML is detectable language but SVG is not?

Repo that have HTML: https://github.com/jcubic/sysend.js (include in stats)
Repo that have SVG: https://github.com/jcubic/clarity (not included in stats)

**Comment by jcubic** [comment]
It seems it's possible, but I think that SVG is not marked even as data. You need to use:

```
*.svg linguist-detectable linguist-language=SVG
```

Without language it doesn't work, which probably mean that it's not detectable language.

**Comment by Alhadis** [comment]
> Why HTML is detectable language but SVG is not?

HTML is designed to be hand-written, whereas SVGs are not. Moreover, SVG files tend to be quite large: it'd only take one or two detailed graphic files for a web project to be classified as an "SVG project" instead of, say, HTML or JavaScript. Needless to say, this would annoy a _lot_ of users…

> Without language it doesn't work, which probably mean that it's not detectable language.

You don't need the `linguist-language=SVG` attribute. The reason why jcubic/Clarity@dc9d3bf95ac8e0f95d66842e5717b7d9a13419fc didn't seem to work is because [repository stats are only refreshed when a change is pushed](https://github.com/github/linguist/blob/master/docs/how-linguist-works.md#how-linguist-works-on-githubcom). Hence why your follow-up commit, jcubic/Clarity@f17813def872a7595ed918fba005855c87bfb06c, appeared to "fix" the issue.
