### ISSUE TITLE
Golang syntax highlighting in markdown doesn't seem to work

### ISSUE THREAD

**Issue by c4milo** [github/linguist#1450]
We have this project https://github.com/rakyll/magicmime/blob/master/README.md where we believe we have properly written the Go code block. However, Linguist or something else doesn't seem to recognize it.

Apologies if this is not the place to report this issue.

**Comment by jianzhangbjz** [comment]
Hi @pchaigno , I have a file called `olm.go`, but the Golang code wasn't highlighted when submitting a Github PR. But, other files were highlighted correctly. Do you happen to know why? Thanks very much!
olm.go file:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/15416633/200465229-6bd0a892-8007-4500-9b41-d66a3c42da52.png">
Other files:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/15416633/200465446-7ad99524-32a8-40cb-ba9f-179d56e7fe9b.png">

**Comment by lildude** [comment]
@jianzhangbjz  this won't be Linguist causing this. This is probably caching or something gone awry with the highlighting engine in the PR (highlighting is loaded asynchronously). If you can reproduce it, please do so and contact GitHub support using the Contact GitHub link on the page in question.

As an aside, you really should have opened a new [discussion](https://github.com/github/linguist/discussions) rather than commenting on an 8 year old issue 😉
