### ISSUE TITLE
Support language highlighting on GitHub.com based upon Linguist overrides

### ISSUE THREAD

**Issue by arfon** [github/linguist#1792]
Currently the Linguist [overrides](https://github.com/github/linguist#overrides) only affect the language statistics and not the syntax highlighting. It would be good to allow these overrides to change the syntax highlighting behaviour also.

Emacs/Vim mode strings support would also be nice.

Related: https://github.com/github/linguist/issues/781 https://github.com/github/linguist/issues/875

**Comment by arfon** [comment]
> Emacs/Vim mode strings support would also be nice.

PR in progress here: https://github.com/github/linguist/pull/2041

**Comment by arfon** [comment]
OK #2041 is in master now. We plan to cut a gem tomorrow.

**Comment by pchaigno** [comment]
@arfon Does this mean that the idea of overrides impacting highlighting is abandoned?

**Comment by arfon** [comment]
Yikes. Closed this by mistake. We'd still like to support the Linguist-style overrides.

**Comment by bgriffith** [comment]
Just to add my support for this feature or allowing Linguist to set the syntax highlighting (especially when working with custom extensions) :+1:

**Comment by deathbeam** [comment]
Yes please, this would be awesome.

**Comment by bryanhelmig** [comment]
:+1:

**Comment by eugeneia** [comment]
:+1:

**Comment by mintsoft** [comment]
:+1:

**Comment by bendoh** [comment]
👍

**Comment by oakfang** [comment]
:+1:

**Comment by jordwalke** [comment]
I think this is important, and good for github because it allows github to be used as a place to build and share technologies that are not yet mainstream (like JSX before it became popular). Can you update on the plan for this?

**Comment by zenparsing** [comment]
:+1: Sometimes people invent weird extensions for normal things (like "jpp" for a certain functional classification of "jsp").

**Comment by DerekTBrown** [comment]
+1

**Comment by NyproTheGeek** [comment]
Is this issue still being reviewed?

**Comment by itzo** [comment]
Also interested in this.

**Comment by scottbedard** [comment]
This feature would be super useful, I'd love to see it implemented.

**Comment by sunjay** [comment]
This would be really useful to have as adding vim modelines to every file is extremely inconvenient with a lot of files with a non-standard file extension.

**Comment by lildude** [comment]
Good news peeps, this is now a thing that was shipped to all users just over a week ago.

Your [language overrides](https://github.com/github/linguist#overrides) should now be reflected in syntax highlighting of blobs and diffs as well as the language statistics.

All highlighting caches were flushed so you should be seeing your overrides taking place already. If not, pushing a new commit to your repository again should force a re-analysis (it may take a few minutes to appear as the refresh is a low-priority background job).

https://github.com/lildude/test-highlighting-override is an example illustrating this new behaviour.  It contains a single ruby file containing ruby code but is then over-ridden by the `.gitattributes` giving us...

![screen shot 2017-03-14 at 10 16 14](https://cloud.githubusercontent.com/assets/627280/23895969/90837fc2-089f-11e7-9cb9-621a24274fbc.png)

... confirming the statistics and ...

![java-highlighting-on-ruby-files](https://cloud.githubusercontent.com/assets/627280/23895988/9d7609e8-089f-11e7-816f-cf4a809f6db3.png)

... confirming the syntax highlighting override.

If you're not seeing this or are experiencing problems, please contact [GitHub Support](https://github.com/support) and they'll take a look at any repositories you're having problems with, but please ensure you've made at least a single commit and push to the affected repository since 7 Mar 2017 to be sure all data has been re-analysed.

I'll raise a PR to address the Linguist readme to reflect this now works.

**Comment by klausi** [comment]
Unfortunately this does not seem to work for marking Drupal *.module files as PHP, see https://github.com/klausi/github-lingiust-test . Can you also enable PHP as language that can be set in .gitattributes?

**Comment by Alhadis** [comment]
Holy crap.

<img src="https://cloud.githubusercontent.com/assets/2346707/23902314/d2b41ed6-0914-11e7-9d81-5467b845678b.jpg" width="300" />

Colour me a happy bastard.

**Comment by Alhadis** [comment]
@klausi Hrm, that's odd. Perhaps push a change to a `.module` file? The `.gitattributes` thingie was set after the file was uploaded, it might need a cache-bust.

**Comment by klausi** [comment]
@Alhadis Indeed, thanks! So that means you need to touch each and every file in a git commit so that the new syntax highlighting takes effect?

**Comment by Alhadis** [comment]
Well, that was actually a half-educated guess, haha. I don't know the actual mechanics going on behind the scenes, but I know that changes to Linguist won't retroactively affect every file that's already been indexed and cached. =)

For instance, [this repository](https://github.com/bwarken/runoff) hasn't been updated in over 3 years, and it's still being classified as Perl (despite the actual [language breakdown](https://github.com/bwarken/runoff/search?l=perl) being very different).

I think it's safe to say many other mechanisms are handled the same way across the site.

**Comment by gautamkrishnar** [comment]
Wow
