### ISSUE TITLE
language detection doesnt seem to update

### ISSUE THREAD

**Issue by borgified** [github/linguist#197]
create a repo like mine: https://github.com/borgified/linguist-test
1. populate with a couple perl scripts
2. commit and push to github
3. observe that linguist detects it as "perl"
4. delete all the perl scripts, replace with a whole bunch of php scripts
5. commit and push to github
6. observe that linguist still detects repo as "perl"

**Comment by ArcaneEngineer** [comment]
Same problem. Would be nice if there were at least a counter displayed on your repo to show when the next update is expected, i.e. when the linguist cron job will get around to you...

**Comment by arfon** [comment]
Hi @ArcaneEngineer - the languages statistics are actually updated after each push to the repository. Are you having trouble with one of your repositories? If so, would you mind opening a new issue to report the problem?

**Comment by ArcaneEngineer** [comment]
In my repo I have a file

js/polyfills/vendors/x-tag-core.min.js
<https://github.com/ArcaneIngenuity/disjunction/blob/2340d00f1a9cb63abeeb53f561477c23949b285b/js/polyfills/vendors/x-tag-core.min.js>


...which I believed should not be counted by linguist, given the rules
here: https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml

?

On Fri, Jan 2, 2015 at 6:18 PM, Arfon Smith <notifications@github.com>
wrote:

> Hi @ArcaneEngineer <https://github.com/ArcaneEngineer> - the languages
> statistics are actually updated after each push to the repository. Are you
> having trouble with one of your repositories? If so, would you mind opening
> a new issue to report the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/linguist/issues/197#issuecomment-68538448>.
>



-- 
Nick Wiggill
Tech Director
<http://arcaneingenuity.com>
On GameDev <http://gamedev.stackexchange.com/users/5473/nick-wiggill>
StackExchange
(ranked 13th out of 40k+ game developers worldwide)
On LinkedIn <http://www.linkedin.com/in/gamesdeveloper/>
On Twitter <https://twitter.com/arcaneingenuity>
On Skype <http://is.gd/4bwD2u>

This message is confidential; if you are not the intended recipient of the
message, please notify the sender immediately. Any unauthorised disclosure,
use or dissemination, either whole or partial, is prohibited. The contents
of this e-mail do not constitute a commitment by Arcane Ingenuity Ltd
except where provided for in a written agreement between you and Arcane
Ingenuity Ltd  (UK reg. no. 07136176).

**Comment by pchaigno** [comment]
@ArcaneEngineer [I doesn't seem to be counted](https://gist.github.com/pchaigno/b9b1af5d8976410f7e47). I used [`linguist --breakdown`](https://github.com/pchaigno/linguist#stats) to get these results.

**Comment by ArcaneEngineer** [comment]
Hi Paul, Arfon

OK, I mistakenly assumed that the high percentage was due primarily to that
file not being removed, because that file was still showing up in the
linguist stats for my repo.

Guys, the only reason I contacted you directly was because of the help on this
page
<https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/>
(rather
minimal!) saying to do so -- whereas in fact, that page should really link
straight to your repo's readme, first and foremost.... I see now that I can
override the stats to make it 50% JS, 50% C -- perfect!

Cheers,



On Sun, Jan 4, 2015 at 2:38 PM, Paul Chaignon <notifications@github.com>
wrote:

> @ArcaneEngineer <https://github.com/ArcaneEngineer> I doesn't seem to be
> counted <https://gist.github.com/pchaigno/b9b1af5d8976410f7e47>. I used linguist
> --breakdown <https://github.com/pchaigno/linguist#stats> to get these
> results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/linguist/issues/197#issuecomment-68631439>.
>



-- 
Nick Wiggill
Tech Director
<http://arcaneingenuity.com>
On GameDev <http://gamedev.stackexchange.com/users/5473/nick-wiggill>
StackExchange
(ranked 13th out of 40k+ game developers worldwide)
On LinkedIn <http://www.linkedin.com/in/gamesdeveloper/>
On Twitter <https://twitter.com/arcaneingenuity>
On Skype <http://is.gd/4bwD2u>

This message is confidential; if you are not the intended recipient of the
message, please notify the sender immediately. Any unauthorised disclosure,
use or dissemination, either whole or partial, is prohibited. The contents
of this e-mail do not constitute a commitment by Arcane Ingenuity Ltd
except where provided for in a written agreement between you and Arcane
Ingenuity Ltd  (UK reg. no. 07136176).

**Comment by pchaigno** [comment]
> Guys, the only reason I contacted you directly was because of the help on this page <https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/> (rather minimal!) saying to do so -- whereas in fact, that page should really link straight to your repo's readme, first and foremost...

@ArcaneEngineer I agree with you. You should report this support@github.com ;)

**Comment by amdowell** [comment]
Hey, just passing to remind that this is still an issue!

**Comment by pchaigno** [comment]
@amdowell If none of the suggestions in this thread worked for you, please open an issue and we'll look into it.
