### ISSUE TITLE
Possible bug in OCaml syntax highlighting?

### ISSUE THREAD

**Issue by hammer** [github/linguist#1985]
Hey,

Some of the code in https://github.com/Chris00/ocaml-csv/blob/master/src/csv.mli is grayed out as a comment (e.g. `val of_channel`) when it's actually working code. I don't know enough about linguist to determine why this section is not being highlighted correctly, but I wanted to point it out in case someone wiser than me is watching these issues.

Thanks,
Jeff

**Comment by pchaigno** [comment]
This happens because of the double quotes in one of your comments: [csv.mli#L89](https://github.com/Chris00/ocaml-csv/blob/master/src/csv.mli#L89). It starts a string which is never closed.
I think it's related to this [stackoverflow answer](http://stackoverflow.com/questions/20795327/ocaml-comment-containing-results-in-comment-not-terminated).

**Comment by hammer** [comment]
Hmm I tried changing it to `'\"'` but that didn't fix things. I'm at a loss now!

**Comment by Chris00** [comment]
The double quote does not need to be closed because it is between single quotes which specify a char.  `ocamldoc` deals with that properly, there is no reason *linguist* could not.

**Comment by pchaigno** [comment]
I'm far from having enough experience with OCa

**Comment by arfon** [comment]
> I think you should move this issue to the repository of the grammar, there will probably be people better able of explaining/fixing what's happening here.

:+1: - yes. @hammer this is an issue with the grammar that's doing the syntax highlighting and not Linguist I'm afraid.
