### ISSUE TITLE
drubuntu is marked as css

### ISSUE THREAD

**Issue by horvan** [github/linguist#1987]
My repository is marked as a css project it should be marked as shell because it contains shell scripts primarily

**Comment by pchaigno** [comment]
I ran Linguist against your repository. It is recognized as a CSS project because you have [many of CSS files](https://gist.github.com/pchaigno/87f30fdb9de6b63fb4a7#file-drubuntu-linguist-L60-L141). See [README#Overrides](https://github.com/github/linguist#overrides) to exclude them from the statistics.

**Comment by arfon** [comment]
> I ran Linguist against your repository. It is recognized as a CSS project because you have many of CSS files. See README#Overrides to exclude them from the statistics.

:+1: Thanks @pchaigno
