### ISSUE TITLE
My repository is marked as the wrong language

### ISSUE THREAD

**Issue by invizinviz** [github/linguist#1990]
Hi, please change language in my Project1 repo to ruby.
Thanks

**Comment by pchaigno** [comment]
I ran Linguist against your repository. It is recognized as a CSS project because you have [a few CSS files](https://gist.github.com/pchaigno/73dcd9c81f93a044f870#file-project1-linguist-L62-L66) and one of them is really big (`foundation_and_overrides.scss`). See [README#Overrides](https://github.com/github/linguist#overrides) to exclude them from the statistics.

**Comment by arfon** [comment]
> I ran Linguist against your repository. It is recognized as a CSS project because you have a few CSS files and one of them is really big (foundation_and_overrides.scss). See README#Overrides to exclude them from the statistics.

:+1:
