### ISSUE TITLE
C# .cs files misidentified as Smalltalk

### ISSUE THREAD

**Issue by vossad01** [github/linguist#2008]
At time of writing, https://github.com/dennisdoomen/fluentassertions has 16 C# files that are classified as Smalltalk, though another 285 are classified correctly.  Spectacularly, these mere 16 files seem to account for 64.6% of the repository making it overall misidentified.

From what I can gather, the .cs extension is also used used by Squeak (Smalltalk) for Changesets.

It this works how I think it does, I am not sure how the files match the heuristic for Smalltalk.  The string 'methodsFor' does not appear in the files I spot checked.
https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L73

A quick search for 'language:smalltalk' shows Fluent Assertions to not be the only C# project affected.  https://github.com/zebraxxl/CIL2Java also is classified as Smalltalk.

**Comment by arfon** [comment]
Hi @vossad01. Thanks for reporting this. I believe https://github.com/github/linguist/pull/2003 should fix this (and will be live soon).

**Comment by vossad01** [comment]
Sorry about that, spent all that time trying to decide if such issues are reported here, that I then forgot to use the search to check for existing...  Thanks for your help!

**Comment by gamesguru** [comment]
Hi, I am having this issue on legacy C# code.  This is from 2010 or earlier.

The repo was added sloppily as a final release and includes binary files and upgrade reports, is that part of the problem?

It is in fact a pure C# project.
```
Smalltalk  59.9%
C#         36.3%
```

**Comment by lildude** [comment]
@gamesguru if you're referring to your https://github.com/gamesguru/Pin-Cracker-maplestory- repo the problem is caused by these large files (too large to be included by search, hence they don't appear when you click Smalltalk in the language stats bar):

- `Backup/Pin Cracker/frmMain.cs`
- `Pin Cracker/frmMain.cs`

As detailed in the README.md, your repo is only analysed when you push changes. Linguist has evolved since your last push so you may find these files will be reassessed correctly this time. If not, the best thing to do is implement a workaround.

If you've got the bandwidth and experience, we'd happily accept a PR to improve the C# heuristic for the `.cs` extension to reduce the chances of this happening in future.

**Comment by gamesguru** [comment]
I tried a new push on a new repo and got the exact same percentages.  This was not pushed in 2010 lol only recently, I did not know of git in my youth.

I do not think 1600 lines should be considered too large?
But you are right about frmMain.cs being the culprit.  Removed both copies, and linguist resolved a pretty much pure C# analysis. This is interesting.

What is considered acceptable coding here?  Can we default .cs files to C#, or try to see where specifically it is failing?  If not, are we encouraged to make just a small change in the heuristic?  I will fork you guys if I think I have an idea.

**Comment by lildude** [comment]
> Can we default .cs files to C#

Nope because multiple languages use this extension as you are seeing, and we have a heuristic to take care of the differentiation. We have no good reason to switch this around.

> or try to see where specifically it is failing?

Nothing is failing as such. The issue is the heuristic isn't distinguishing between the two languages so it's falling through to the naïve Bayesian classifier.

> If not, are we encouraged to make just a small change in the heuristic?

Now this is where it gets interesting... the heuristic https://github.com/github/linguist/blob/4427258362ad6dcd547c8f63846e79cfde1000a9/lib/linguist/heuristics.yml#L71-L76 

... _should_ already be correctly identifying those files as they _both_ contain both `namespace` and don't match the Smalltalk regex at all. This leads me to think there's a problem with the files themselves that are causing the regex to not match, and sure enough there is...

```
$ /bin/cat -v frmMain.cs | head
��u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@.^@C^@o^@l^@l^@e^@c^@t^@i^@o^@n^@s^@.^@G^@e^@n^@e^@r^@i^@c^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@.^@C^@o^@m^@p^@o^@n^@e^@n^@t^@M^@o^@d^@e^@l^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@.^@D^@a^@t^@a^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@.^@D^@r^@a^@w^@i^@n^@g^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@.^@T^@e^@x^@t^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@.^@W^@i^@n^@d^@o^@w^@s^@.^@F^@o^@r^@m^@s^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@.^@D^@i^@a^@g^@n^@o^@s^@t^@i^@c^@s^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@S^@y^@s^@t^@e^@m^@.^@R^@u^@n^@t^@i^@m^@e^@.^@I^@n^@t^@e^@r^@o^@p^@S^@e^@r^@v^@i^@c^@e^@s^@;^@^M^@
^@u^@s^@i^@n^@g^@ ^@P^@i^@n^@_^@C^@r^@a^@c^@k^@e^@r^@.^@P^@r^@o^@p^@e^@r^@t^@i^@e^@s^@;^@^M^@
```

The file is not plaintext or UTF-8 encoded, and sure enough:

```
$ file frmMain.cs
frmMain.cs: Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators
$
```

... versus a file that _is_ correctly identified:

```
$ file frmSettings.cs
frmSettings.cs: ASCII text, with CRLF line terminators
$
```

So the actual problem here is the encoding of these two files is preventing the heuristic from correctly identifying the language and thus leaving things to the bayesian classifier which won't be able to parse these files either (because of the encoding) so falls back to the first language in the list passed to it, which happens to be Smalltalk.

The solution is to either implement an override, or save the file in plaintext or UTF-8 as I've done in my fork of the repo at https://github.com/lildude/Pin-Cracker-maplestory- (this will be deleted in a few days)

Note, when I edited these files GitHub kindly informed me about the encoding issue too:

![screen shot 2018-10-25 at 10 30 14](https://user-images.githubusercontent.com/627280/47490830-714ac700-d841-11e8-9698-015c5045ebd0.png)

After modifying those two files (I removed the red dot you can see at the beginning of the first line), the language stats are:

![screen shot 2018-10-25 at 10 32 40](https://user-images.githubusercontent.com/627280/47490796-65f79b80-d841-11e8-961f-b753971ecbf2.png)

**Comment by gamesguru** [comment]
oh thats interesting, it's always something lol

do you know why visual studio might have done that to the main form? it was a very old version, 2007 or 10?

**Comment by lildude** [comment]
> do you know why visual studio might have done that to the main form? it was a very old version, 2007 or 10?

Nope. Never used Visual Studio. I'd imagine it's probably a config option or possibly a consequence of an OS setting.

**Comment by gamesguru** [comment]
> Never used Visual Studio.

Well I don't anymore either.

And it seems like the linguist could accept different encodings? But realistically wouldn't worry unless you start seeing others using more modern templates having this issue  Not sure I did anything special with frmMain, but that has been nearly 10 years
