### ISSUE TITLE
Puppet recognized as Pascal if comments contain too many minus characters

### ISSUE THREAD

**Issue by tOnI0** [github/linguist#2027]
I found out that if my source code (for instance this Puppet manifest https://github.com/tOnI0/aco-tomcat/blob/master/manifests/init.pp) contains too many minus characters placed in comments, it gets recognized as Pascal.

Converting '-' to '.' made the language being properly recognized.

**Comment by tOnI0** [comment]
Note: changing all these long lines of '--------' in the class parameters to something shorter like just 3 minus signs ('---') or simply deleting some of the lines also helped. Makes me think the actual number of minus chars is actually involved.

**Comment by pchaigno** [comment]
This is because [one of the three Pascal samples for the Bayesian classifier contains many dashes in comments](https://github.com/github/linguist/blob/master/samples/Pascal/gtkextra.pp). Usually Linguist removes the comments before feeding the samples to the classifier for training but, since here braces are used for multiline comments, it is difficult (removing lines between braces would destroy samples in many languages :/).

I opened a pull request to remove this sample and add new ones at #2031. It fixes the issue with your file.

**Comment by arfon** [comment]
Fixed in #2031. @tOnI0 - it'll be another week or so before this change is live on GitHub.
