### ISSUE TITLE
My project is marked as Perl, but it's really Scala

### ISSUE THREAD

**Issue by deanwampler** [github/linguist#2046]
https://github.com/deanwampler/spark-workshop

**Comment by pchaigno** [comment]
Hi @deanwampler! [These two files](https://github.com/deanwampler/spark-workshop/search?l=perl) are detected as Perl by Linguist's classifier. That's because they're executable and so it tries to find which script language it is. If you remove the executable flag your statistics will return to normal :)

Same issue with [these two files detected as Prolog](https://github.com/deanwampler/spark-workshop/search?l=prolog).

**Comment by deanwampler** [comment]
Thanks! Should be fixed now.
