### ISSUE TITLE
xxx.init.d bash script detected as 'D' language

### ISSUE THREAD

**Issue by SjonHortensius** [github/linguist#2081]
As can be seen on https://github.com/Graylog2/graylog2-server/search?l=d&q=provides

the graylog2-server.init.d file (which has a correct shebang) is detected as being in the 'D' language, which is incorrect

**Comment by arfon** [comment]
Hi @SjonHortensius - thanks for reporting this. The issue is that Linguist only knows about one language with that extension `D`: https://github.com/github/linguist/blob/6d770ab68f7aa9b4ea8a31c260b20cf962971daf/lib/linguist/languages.yml#L676 and so will automatically define it as `D`. If there were other languages defining the `.d` extension then we'd use the [shebang](https://github.com/github/linguist/blob/master/lib/linguist/shebang.rb) classification strategy (and would likely get the correct answer).

One possible fix here would be to define `.d` as `Shell` extension [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2765-L2788).

As I side note, I was under the impression that `init.d` paths were usually directories in Unix/Linux systems but that might just be gross ignorance on my part :smile:

**Comment by pchaigno** [comment]
This issue could be solved if we move the Shebang strategy to the top of the strategies to try (I suggested this before in #1991) .

**Comment by larsbrinkhoff** [comment]
A cursory sweep suggests that out of 3000000 `.d` files, about 10% are actually in D.  I'm tempted to do something about that.

**Comment by arfon** [comment]
@larsbrinkhoff - we'll so be doing [Shebang detection first](https://github.com/github/linguist/pull/2085) which will presumably help at some level here?

**Comment by larsbrinkhoff** [comment]
@arfon It'll help if those init.d shell script do have shebang lines.  I just checked, and they seem to do -- great!

However,m a quick random sampling of search results seem to indicate that many of the .d files are Makefile dependency include files, and they don't contain any shebang.

**Comment by arfon** [comment]
> However, a quick random sampling of search results seems to indicate that many of the .d files are Makefile dependency include files, and they don't contain any shebang.

OK, it might well be worth doing something about those then.
