### ISSUE TITLE
nginx highlighting of access_log vs error_log

### ISSUE THREAD

**Issue by alcohol** [github/linguist#2125]
It seems `access_log` is not highlighted whereas `error_log` does get highlighted. Not sure if this is intentional or has to do with them being defined slightly different in the vendor grammar file.

Grammar definitions:
* [access_log](https://github.com/brandonwamboldt/sublime-nginx/blob/master/Syntaxes/nginx.tmLanguage#L678-L700)
* [error_log](https://github.com/brandonwamboldt/sublime-nginx/blob/master/Syntaxes/nginx.tmLanguage#L241-L263)

**Comment by pchaigno** [comment]
Linguist is only detecting the languages and assigning the right grammars to highlight the files.
In the case of Nginx, GitHub is using [this grammar](https://github.com/brandonwamboldt/sublime-nginx) (See [`grammars.yml`](https://github.com/github/linguist/blob/master/grammars.yml)).

You should open an issue on the grammar repository ;)

**Comment by pchaigno** [comment]
Also, could I know if you read somewhere that Linguist was handling syntax highlighting and where?
I'll try to fix the documentation if it's misleading (or contact GitHub support if it's on github.com doc).
Thanks!

**Comment by alcohol** [comment]
Well, I didn't read it anywhere. All I've read is that Linguist is used to determine the language(s) of source files and such. I've also read somewhere that previously, Pygments was used, but now Linguist. I understand it uses grammar files provided by third party vendors. What I don't understand yet, is how it uses those. The grammar files I listed work fine for highlighting `access_log` as illustrated in the [screenshot](https://github.com/brandonwamboldt/sublime-nginx/blob/master/screenshot.png) in the repository. However, `access_log` is not highlighted in any nginx files or syntax blocks I mark as nginx on github. For example, [here](https://github.com/alcohol/sf-minimal-demo#nginx-example) (I'm under the assumption it's also used for highlighting syntax code blocks -- please correct me if I am wrong).

I think the documentation is simply missing (not wrong or misleading) when it comes to how syntax highlighting is handled on GitHub. There is a whole section on GF Markdown and such, but not a single word about how Linguist and the grammar files comes into play for syntax highlighting.

**Comment by pchaigno** [comment]
Hu! You're right. I tried it on Lightshow just to make sure that we're not missing an update and I get [the same highlighting](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbrandonwamboldt%2Fsublime-nginx%2Fmaster%2FSyntaxes%2Fnginx.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Flinguist%2Fmaster%2Fsamples%2FNginx%2Ffilenames%2Fnginx.conf&code=). I also tested on Sublime Text without going through the package installer (I installed it manually) and the file is highlighted corrected.

There has been a similar problem before (see paulmillr/LiveScript.tmbundle#40 for more info). It happened because the regular expression engine used by Sublime Text and GitHub were interpreting regexes slightly differently. However I can't see anything that could cause the same issue with the Nginx grammar...

/cc @aroben

**Comment by brandonwamboldt** [comment]
@pchaigno @alcohol Well that took an hour to find, but I fixed the issue:

https://github.com/brandonwamboldt/sublime-nginx/commit/872afddd2d61acae85560fa009658257f4030244

Will submit a PR to update the submodule

**Comment by alcohol** [comment]
It's often the little things. Nice catch and thanks for taking time to look into this :-)

**Comment by pchaigno** [comment]
@brandonwamboldt Nice catch!

> Will submit a PR to update the submodule

It will be automatically updated with the next release of Linguist ;)

**Comment by bkeepers** [comment]
@alcohol @pchaigno thanks for your work on fixing this!
