### ISSUE TITLE
Custom file extensions ignored by linguist

### ISSUE THREAD

**Issue by kirillDanshin** [github/linguist#2267]
If you create a file with, say, `.ext` extension (or other, not `.php`), and write PHP code there, linguist will ignore that file. For example, see [this repository](https://github.com/izumrud-system/izumrud-system).

**Comment by arfon** [comment]
Yes, this is by design. Linguist employs a [number of strategies](https://github.com/github/linguist/blob/master/lib/linguist/language.rb#L90-L96) to identify the language of your files, if the extension is not matched by any 'candidate' languages then we don't try and identify the language.

That said, there are a number of ways in which you can override the detection by Linguist. You can read more about these here: https://github.com/github/linguist#overrides
