### ISSUE TITLE
Documents other than HTML not included in language stats

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2316]
I have a repository with documents in various formats, and no program code:
https://github.com/larsbrinkhoff/forth-documents

As an end user, I might find it strange that only the HTML documents are included in the language statistics, and not the other documents which are PDF, PostScript, and plain Text.  It may not be clear what the disctinction between `markup` and `prose` is that makes one kind included in stats and one not.

Cf #2097, #2138, @aroben.

**Comment by aroben** [comment]
Indeed, I think it would be great to include all `prose` files in the language stats (as long as they aren't documentation, tests, vendored, etc.). That would be really useful for repositories that primarily contain prose (books like https://github.com/progit/progit2 are one example).

https://github.com/github/linguist/pull/2097 was the first step in this direction, and as we've seen it's been tricky to get right. I suspect we'll run into similar issues if/when we add `prose` files to the language stats, which is why we've tried to be conservative so far.

**Comment by larsbrinkhoff** [comment]
I suppose most users would want their code repositories to be classified according to the "most important" programming language in the repo.  Unless, of course, the repository is "obviously" a prose/markup repo.  (For some value of "important" and "obviously".)

Would this be a good time to start working on some repository classification into either `programming` or `markup`/`prose`?  And then restrict the classification of the repository language inside that class?

(This wouldn't necessarily affect the statistics in the language bar at all.)

**Comment by pchaigno** [comment]
> Would this be a good time to start working on some repository classification into either `programming` or `markup`/`prose`? And then restrict the classification of the repository language inside that class?

:+1:

**Comment by arfon** [comment]
Closing this as stale.
