### ISSUE TITLE
Misclassification of .jsm files as being of Java code (should be javascript)

### ISSUE THREAD

**Issue by oshybystyi** [github/linguist#2377]
Can be reproduced here https://github.com/oshybystyi/Linguist-jsm-misclassification-bug .

I checked https://github.com/github/linguist/blob/master/lib/linguist/languages.yml - and .jsm is related to javascript (I use those files in firefox extensions, example [here](https://github.com/oshybystyi/FireX-Pixel-Perfect/blob/issue-5-make-addon-restartless/content/ui.jsm)).

**Comment by pchaigno** [comment]
This is because of [the modeline](https://github.com/oshybystyi/Linguist-jsm-misclassification-bug/blob/7a135171e0b37165e0a9e10030303e7adabc6a15/ui.jsm#L1). You can tell Linguist to consider this file as JavaScript with a `.gitattributes` file:
```
*.jsm linguist-language=Java
```

We're having many users with Java modelines on their JavaScript files. I'll see if we can do something (maybe it would be worth having an exception for this particular modeline...).

**Comment by oshybystyi** [comment]
@pchaigno, I've just copied the first modeline from some firefox module (like [PdfJs](https://dxr.mozilla.org/mozilla-central/source/browser/ex tensions/pdfjs/content/PdfJs.jsm)) not realizing of what it does.

Don't think that it makes sence to implement the exceptions for that.

So mark this bug as 'invalid'.

**Comment by pchaigno** [comment]
> I've just copied the first modeline from some firefox module (like PdfJs) not realizing of what it does.

It's actually used for Emacs and Vim syntax highlighting.

Is this issue resolved then?

**Comment by oshybystyi** [comment]
> Is this issue resolved then?

Yes, thanks.
