### ISSUE TITLE
Language Rename Groff -> Python

### ISSUE THREAD

**Issue by Jessjeanjo** [github/linguist#2402]
The language of my PythonCharming Repo is set as Groff when it should be Python

**Comment by pchaigno** [comment]
This is happening because Linguist can't detect your Python files (we only check the shebang for executable files) and one of them has a potential Groff extension (`Superhero 2.7`).

Three solutions possible:
- Add a `.py` extension to your Python files
- Make your scripts executable (but it looks like your working on Windows :/)
- Add a `.gitattributes` file to recognize all files as Python (see [my fork of your repo](https://github.com/pchaigno/PythonCharming) for an example)

I would go for the first option because I think it's always good practice to give an extension to your files. The last option is probably the worst since even your README (or any other non-Python files you may want to add later) will be detected as Python :/

**Comment by Jessjeanjo** [comment]
Thank you Paul!
Adding the python extension, fixed the problem right up
