### ISSUE TITLE
JavaScript repo reporting ~50% as Java

### ISSUE THREAD

**Issue by dustinc** [github/linguist#2454]
Any chance recent updates could be responsible for status bar miscalculating percent of Java files in repo? Reports repo as 46.5% Java when in fact there is 0% Java present. To be sure, searched ```?l=java``` on repo which returns nothing.

Thanks

**Comment by arfon** [comment]
Could you share a link to the repository?

**Comment by dustinc** [comment]
Sure. It is a [private repo](https://github.com/dustinc/vtt), fyi.

**Comment by arfon** [comment]
> Sure. It is a private repo, fyi.

Ah OK, I'm afraid I won't be able to see that then.

Out of interest, do any of your files have Emacs or Vim modelines in any of your files specifying that the language is `Java`? You can see what these look like [here](https://github.com/github/linguist#using-emacs-or-vim-modelines)

**Comment by dustinc** [comment]
They do not. The only files even remotely close are some used by Heroku, but as you can see they do not mention ```Java```: 

*.buildpacks*
```
https://github.com/heroku/heroku-buildpack-nodejs
https://github.com/heroku/heroku-buildpack-python
```

*Procfile*
```
web: node server.js
```

*requirements.txt*
```
argparse==1.2.1
xlrd==0.9.3
```

There is a hefty amount of ```.jade``` files, though. While they're nothing like ```Java```, could the file extensions be getting misinterpreted?

**Comment by arfon** [comment]
Just realised I can look at language stats for your repo from our staff tools. Although this doesn't let me see the contents of files I could see the language breakdown.

Looks like pdf.js is the culprit here. As you you see [here](https://github.com/mozilla/pdf.js/blob/master/src/pdf.js#L1) this project is setting the language to `Java` (I think this is for their text editor).

You can fix this by adding a `.gitattributes` file which will either allow you to ignore the file:

```
public/scripts/pdf/pdf.js  linguist-vendored
```

or manually set the language:

```
public/scripts/pdf/pdf.js linguist-language=JavaScript
```

**Comment by dustinc** [comment]
Wonder why that file doesn't show up in search results. Anyways, thank you.
