### ISSUE TITLE
Add highlighting mode for coloured shell output

### ISSUE THREAD

**Issue by dpogue** [github/linguist#2528]
There's currently no good highlighting mode for coloured shell output, such as clang/gcc errors or other tools that rely on ANSI escape codes for colouring.

Using plaintext mode gets the content across, but it can be significantly harder to interpret with colours removed.

**Comment by arfon** [comment]
We use Textmate and Sublime grammars for syntax highlighting. Do you know if there are any grammars that do this? (We'd also need a reliable way of detecting shell output)

**Comment by vsch** [comment]
I was just checking if GitHub recognized ANSI Escapes as a language for fenced blocks. I could not be the only one who wanted:

<img width="400" alt="screen shot 2015-08-20 at 2 06 04 pm" src="https://cloud.githubusercontent.com/assets/10299086/9391415/a3cd6304-4744-11e5-952e-50c0ab644744.png">

to render as:

<img width="383" alt="screen shot 2015-08-20 at 1 34 01 pm" src="https://cloud.githubusercontent.com/assets/10299086/9390620/2ce2308e-4740-11e5-9d61-e01a5a570a6a.png">

instead of:

    ```ansi
    [0m[[31merror[0m] [0m         TableCaptionNode [0-0][0m
    [0m[[31merror[0m] [0m           TextNode [604-609] 'Table'[0m
    [0m[[31merror[0m] [0m           SpecialTextNode [609-610] ':'[0m
    [0m[[31merror[0m] [0m           TextNode [610-618] ' Caption'[0m
    [0m[[31merror[0m] [0m     '[0m
    [0m[[31merror[0m] [0m     [0m
    [0m[[31merror[0m] [0m      is not equal to [0m
    ```

I was right. :)

@arfon, I had to dig up some old, old memories but the ANSI escape sequences for terminal control all have the regex form: `/␛\[[0-9]*(;[0-9]*)*[a-z]/`. I would venture a bet that this could be the most easily detected language, with no possibility of false positives or false negatives. If you find the above regex pattern then it is an ANSI escape sequence.

For display rendering control the lowercase letter is `m`. You can set multiple commands with one escape sequence: 

    ␛[0;31;37;38m

is equivalent to a longer sequence: 

    ␛[0m␛[31m␛[37m␛[38m
 
[Wikipedia: ANSI Escape Codes](https://en.wikipedia.org/wiki/ANSI_escape_code) gives the definitions for all sequences but I would only go as far as the display rendering code support it is the CSI:
<img width="547" alt="screen shot 2015-08-20 at 1 39 44 pm" src="https://cloud.githubusercontent.com/assets/10299086/9390986/794e5bda-4742-11e5-944d-8e3adcce75dc.png">

The lexer for this would be easy to write, with a simple state machine to keep track of the fore color, back color and attributes: normal, bright, faint settings. Final attributes are a simple look-up, which can even include *flavours* of terminal implementations: ansi.vga, ansi.winxp, ansi.terminal, ansi.putty, etc. Right from the Wikipedia color chart for different implementations. Vanilla `ansi` would implement all the features using colors, text-decoration and font styles and weights, since it is very easy and would make creating new flavours just another configuration entry.

I would be willing to write the code and test it if someone can focus me where to look to help narrow down the search. (eg: look in https://github.com/github/linguist, dir or files for an example). For anyone who has written or maintained a real language syntax colorizer this would be literally 'a no brainer'.

**Comment by peteruithoven** [comment]
Any updates on this?

**Comment by pchaigno** [comment]
Unfortunately this is not something that can be changed in Linguist as it is a rendering issue (as opposed to a simple highlighting issue). [github/markup](https://github.com/github/markup) is probably a better place to propose a new rendering engine. However, they try to avoid adding too many new rendering engines as they can have a significant cost to maintain (in particular, any change needs to be checked for security vulnerabilities).

**Comment by joshnatis** [comment]
Hey Paul, has the state of affairs changed in any relevant way since your last comment in 2016? I know there's still pushback against colored text in GitHub Markdown in general, but is it still not feasible to honor raw ANSI/VT100 escape codes[1] in code blocks via Linguist? (or at least some subset of them?)

[1] like what you'd get with `ls --color=always | copy`

**Comment by lildude** [comment]
@joshnatis still no change, and all of the previous comment still stands, especially the part about this being outside of Linguist's control as it's a rendering issue 😉 Such functionality would need to be implemented in the markup library, not Linguist.
