### ISSUE TITLE
Linguist Truck Factor

### ISSUE THREAD

**Issue by gavelino** [github/linguist#2543]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Linguist** and obtained a value of **2**.

The developers responsible for this TF are:

Joshua Peek - author of 48% of the files
Arfon Smith - author of 23% of the files

To validate our results, we would like to ask **Linguist** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Linguist**?

(b) Do you agree that **Linguist** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Linguist** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by arfon** [comment]
Hi @gavelino, thanks for getting in touch.

> (a) Do you agree that the listed developers are the main developers of Linguist?

Not really. I think you should probably consider putting a time-window on your analysis - i.e. look at who has been active over the past 3, 6, 9, 12 months etc. Josh is the original author of this library but isn't active these days. Even a cursory inspection of [this page](https://github.com/github/linguist/graphs/contributors) would demonstrate this.

> (b) Do you agree that Linguist will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

No, because of my first answer.

> (c) Does Linguist have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Perhaps? Linguist is pretty well tested and documented.

I would be happy to talk more with you about your analysis methodology (I'm an academic working for GitHub) if that would be useful.

**Comment by gavelino** [comment]
Thank you.
