### ISSUE TITLE
TypeScript mistaken for Java

### ISSUE THREAD

**Issue by edsilv** [github/linguist#2556]
https://github.com/UniversalViewer/universalviewer

Why is it reporting 51% Java?

I've tried to override this using .gitattributes, but I must be doing something wrong?

**Comment by pchaigno** [comment]
This is happening because of the [Vim modeline](https://github.com/UniversalViewer/universalviewer/blob/a13e90abe79139864c0bd9dc23508704c85d4315/src/extensions/uv-pdf-extension/lib/viewer.js#L1) on [these `.js` files](https://github.com/UniversalViewer/universalviewer/search?l=java). That's a recurring issue with Mozilla's JavaScript files.

You can probably override that by defining the folder as vendored (`linguist-vendored`).
