### ISSUE TITLE
Backslashes disappear in Lightshow

### ISSUE THREAD

**Issue by pchaigno** [github/linguist#2593]
I found a weird bug in Lightshow that probably has to do with the url encoding.
If I test a grammar on the following code, copy the resulting link, paste it in GitHub and re-open it, it loses one of the two backslashes.
```
'line1
line2\\
line3'
```
[Example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-javascript%2Fa906d863677b8346aba3d429434a63747ac334ba%2Fgrammars%2Fjavascript.cson&grammar_text=&code_source=from-text&code_url=&code=%27line1%0D%0Aline2\\%0D%0Aline3%27)

/cc @aroben

**Comment by aroben** [comment]
The URL in the Markdown version of your comment is:

    https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-javascript%2Fa906d863677b8346aba3d429434a63747ac334ba%2Fgrammars%2Fjavascript.cson&grammar_text=&code_source=from-text&code_url=&code=%27line1%0D%0Aline2\\%0D%0Aline3%27

Note that the backslashes appear as literal backslash characters, and there are two of them.

However, the HTML that github.com generates contains the following URL instead:

    https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&amp;scope=from-url&amp;grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-javascript%2Fa906d863677b8346aba3d429434a63747ac334ba%2Fgrammars%2Fjavascript.cson&amp;grammar_text=&amp;code_source=from-text&amp;code_url=&amp;code=%27line1%0D%0Aline2%5C%0D%0Aline3%27

Note that backslash has turned into `%5C`, and there is only one of them.

So it seems like this is happening somewhere in the code that turns Markdown into HTML, rather than being a bug in Lightshow.

@pchaigno What browser are you using? It looks like Safari and Chrome generate `%5C` in their address fields, while Firefox generates `\`.

**Comment by pchaigno** [comment]
I'm using Firefox (40.0 under Ubuntu).

Should I close this and report to support@github.com?

**Comment by aroben** [comment]
It looks like this is happening in the Markdown processing itself, not any later step (e.g., linking up @mentions etc.).

> Should I close this and report to support@github.com?

Yes, I think so. Thanks!

**Comment by pchaigno** [comment]
Done. @aroben Thanks for the help!
