### ISSUE TITLE
What are the exact requirements for a language to be added?

### ISSUE THREAD

**Issue by danilolekovic** [github/linguist#2657]
Hi, 

I read the guidelines but was still wondering exactly how much usage was required and what the exact requirements for adding a language is. Are stars on the language repository considered too?

Thanks a ton!
@danilolekovic

**Comment by deathbeam** [comment]
I am interested in this too, as in guides there is that "there must be hundreds of repositories with language you want to add".

**Comment by danilolekovic** [comment]
@deathbeam Yeah, and I see languages on here with like 4 repositories that are all by the same person.

**Comment by deathbeam** [comment]
For example, I found this language: https://github.com/anunayk/cool-tmbundle to be officially supported, but there exists only one repository in COOL language on GitHub and also, even the main repo for COOL have 0 starts lol.

**Comment by pchaigno** [comment]
First, I should precise that I'm not part of GitHub staff ; I'm only a contributor to this project.

So, as @bkeepers explained in [#1894 (Comment)](https://github.com/github/linguist/pull/1894#issuecomment-67742740):
> this [requirement] is just a rule of thumb to help us differentiate languages that have widespread adoption vs languages that are research projects or personal hobbies. It's not a hard rule.

Languages/extensions for which the requirement is not clear are generally considered on a case by case basis. The popularity of the language outside of GitHub (indicating that it might just be a matter of time before it spreads on GitHub) and the unlikelihood of the extension to collide with another might help. For instance, when `.dyalog` was added (see #1894) there was only 54 sample files (more than 800 now).
<br>

> I see languages on here with like 4 repositories that are all by the same person.

Several things could explain that some extensions/languages don't fulfil this requirement.
- This requirement came as the project was getting more mature and growing in size (in terms of number of languages supported). So there might be some languages that were added even though they wouldn't meet the requirements today.
- The popularity of a language can change quickly over time. Some extensions might have (almost) disappeared from GitHub even though they were widespread a few years ago. We can probably remove those if they happen to conflict with another language in the future.
<br><br>

> For example, I found this language: https://github.com/anunayk/cool-tmbundle to be officially supported, but there exists only one repository in COOL language on GitHub and also, even the main repo for COOL have 0 starts lol.

Please see #1796 and #1181 for the background on COOL. I can find [almost 1,500 examples of COOL files on GitHub](https://github.com/search?l=cool&q=pool+class+extension%3Acl&ref=searchresults&type=Code&utf8=%E2%9C%93). [More repositories here](https://github.com/trending?l=cool).

**Comment by bkeepers** [comment]
Thanks for the explanation, @pchaigno. 

@danilolekovic does that help clarify it? I'm going to close this issue, but feel free to continue the discussion here and we can reopen it if any action needs to be taken.

**Comment by davidzchen** [comment]
Thanks for the explanation.

@bkeepers - can you clarify on whether the requirement for both adding an extension and adding a language is still hundreds of repositories (as currently stated in [`CONTRIBUTING.md`](https://github.com/github/linguist/blob/master/CONTRIBUTING.md)), or have the requirements changed? I am wondering because:

* In #2348, you mentioned that the requirement for adding an extension is having "hundreds of samples," which seems to imply hundreds of files rather than hundreds of repositories.
* For the JSONLD language, which was added in #957 about a year ago, the search indicates that there are over [15k files](https://github.com/search?p=1&q=extension%3Ajsonld+NOT+nothack&ref=searchresults&type=Code&utf8=%E2%9C%93), but I only count ~18 repositories that contain `.jsonld` files, with the bulk of them contained in ~3 repositories.

I understand that the distribution of languages change over time and that the requirements for Linguist change as GitHub scales up. However, I think we would appreciate some additional clarification on the requirements, especially whether the requirement is on the number of *files* or *repos*.

**Comment by danilolekovic** [comment]
Thanks @davidzchen @bkeepers!

**Comment by bkeepers** [comment]
>  can you clarify on whether the requirement for both adding an extension and adding a language is still hundreds of repositories (as currently stated in CONTRIBUTING.md), or have the requirements changed?

@davidzchen Hundreds of repositories is the rule of thumb. Again, it's not really a hard and fast rule. We just want to see that a language has some adoption before we commit to supporting it. If you have a language that you think should be added, feel free to open a pull request for discussion.

**Comment by davidzchen** [comment]
@bkeepers Understood. Thanks for the clarification.
