### ISSUE TITLE
whitespace in .gitattributes linguist-language

### ISSUE THREAD

**Issue by c-lipka** [github/linguist#2751]
In the `.gitattributes` file, how do we set the `linguist-language` attribute to a language name that contains whitespace, such as `Ant Build System`?

**Comment by arfon** [comment]
Good question @c-lipka. It doesn't seem to work currently. I'll try and investigate a solution to this.

**Comment by pchaigno** [comment]
@c-lipka Whitespaces in `.gitattributes` do not seem to be the issue here. I tried with `AGS Script` and it works fine.

Maybe this has to do with `Ant Build System` being a [data language in Linguist](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L166)? As a consequence it will not appear in statistics, even with a `.gitattributes`.

**Comment by pchaigno** [comment]
Flagging as stale :flags:
