### ISSUE TITLE
IDL .pro code misidentified as Prolog

### ISSUE THREAD

**Issue by vishal-bala** [github/linguist#2762]

**Comment by pchaigno** [comment]
Could you link to the incorrectly classified file(s)?

**Comment by vishal-bala** [comment]
Sure, here it is: https://github.com/vishal-bala/AS441/blob/master/CCD_CHAR.pro

**Comment by pchaigno** [comment]
The `.pro` (IDL, Prolog, QMake and INI) classification is not perfect and will probably never be :/
Your file is incorrectly classified because of [this line](https://github.com/vishal-bala/AS441/blob/master/CCD_CHAR.pro#L17); `:-` is detected as a Prolog construct.
You can fix that using [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by arfon** [comment]
> You can fix that using Linguist overrides.

Yeah, this is probably the best solution here.
