### ISSUE TITLE
Support non-rendering option

### ISSUE THREAD

**Issue by thwg** [github/linguist#2777]
Recently I've intended to upload some .org files to GitHub, but instead of being syntax highlighted, they are rendered for the user.  One problem is that most options are not supported, so anything more than simple org files will look very unreadable and inaccurate.  Some projects have [disclaimers](https://github.com/limist/literate-programming-examples/blob/master/02-minimal-clojure-project/clojure-default-skeleton.org) not to use GitHub to view them, whereas displaying syntax-highlighted text ([similar to this](https://github.com/github/linguist/blob/master/samples/API%20Blueprint/attributes.apib)) would be much more useful.

I am proposing a new gitattribute, `linguist-render`, which is a boolean.

It could be used in the following way:

```
*.org linguist-render=false
README.org linguist-render
```

The above example would render README.org as it currently does, but other *.org files would be displayed as a regular syntax-highlighted document.

For backwards compatibility, rendering would be the default, and disable rendering would be explicit.

`linguist-render` would be agnostic, so while my example is for *.org files, it could also be applied for all the other markups as well.

Let me know if this proposal sounds good or any suggestions, and I can look into working on it.

**Comment by thwg** [comment]
I'm actually not 100% sure that this would be a linguist option, since it deals with the display rather than detection.  If there is a better place for this to be done, please let me know.

**Comment by pchaigno** [comment]
Selection of the rendering engine happens at [github/markup](https://github.com/github/markup). A `render` attribute should probably be implemented there rather than in Linguist. /cc @bkeepers 

> One problem is that most options are not supported, so anything more than simple org files will look very unreadable and inaccurate.

To parse `.org` files, markup relies on [a Ruby implementation of Org mode](https://github.com/wallyqs/org-ruby). Why not open an issue there (or a pull request) for the missing features?

**Comment by thwg** [comment]
Hi, thanks for the reply!

I took a look at github/markup before, but it doesn't appear to look inside the file ([such as linguist does for the modeline](https://github.com/github/linguist/blob/dca18d77cb163582c0569ef337c113f9eaddd57a/lib/linguist/strategy/modeline.rb#L4)) or know anything about the repository ([such as linguist does for gitattributes](https://github.com/github/linguist/blob/efdc790374a7ade32bbe429934491afa48cc1fc8/lib/linguist/lazy_blob.rb#L39)).

If it should be done in github/markup, I think a modeline directive would be the way to go.  An additional language file could be added to linguist afterwards for org-mode syntax highlighting.

> To parse .org files, markup relies on a Ruby implementation of Org mode. Why not open an issue there (or a pull request) for the missing features?

Some of the common features, like `include` directives, need to have some filesystem abstraction.  They can't be rendered properly as individual documents.  I think this is incompatible with the way that GitHub renders them, even if it were supported by org-ruby.

**Comment by pchaigno** [comment]
> I took a look at github/markup before, but it doesn't appear to look inside the file (such as linguist does for the modeline)

Yep, github/markup currently only looks at the file extension. I opened a pull request (github/markup#537) to change that (rely on Linguist instead of the file extension) but I haven't had time to finish it yet.

As for the correct way to implement this, I'm not from GitHub and I don't know if they'd prefer to extend the responsibilities of Linguist or make Markup repository-aware...
