### ISSUE TITLE
Perl5 detected as Perl6

### ISSUE THREAD

**Issue by chorny** [github/linguist#2781]
https://github.com/drzowie/Alien-Gnuplot/search?l=perl6

File is https://github.com/drzowie/Alien-Gnuplot/blob/0d4659a3687fafd79ba7aabc3a12f633e2d6ec06/Makefile.PL

IMHO, "use strict;" should be enough to classify this as Perl5.

**Comment by pchaigno** [comment]
> IMHO, "use strict;" should be enough to classify this as Perl5.

That's what we do with the [heuristic strategy](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L281). However, your file matches the Perl6 heuristic first, because of [the line that starts with `module`](https://github.com/drzowie/Alien-Gnuplot/blob/0d4659a3687fafd79ba7aabc3a12f633e2d6ec06/Makefile.PL#L38) (the heuristic strategy is not aware of multiline comments and strings).

#2782 should fix this by reordering the heuristic for Perl. The Perl5 heuristic is more accurate than the Perl6 so I placed it before.

That said, Perl5/Perl6 classification will never be 100% accurate, because the two languages are very similar.
