### ISSUE TITLE
Code being reported as Java but no Java files found

### ISSUE THREAD

**Issue by alexandermendes** [github/linguist#2816]
Hi,

My code is being reported as 70% Java in this repo:

https://github.com/LibCrowds/libcrowds-pybossa-theme

But if I search the repo for any Java files none are found:

https://github.com/LibCrowds/libcrowds-pybossa-theme/search?l=java

Any ideas? Thanks!

**Comment by pchaigno** [comment]
Your repository is detected as Java because of [this file](https://github.com/LibCrowds/libcrowds-pybossa-theme/blob/master/static/js/pdf/pdf.js) which has a Java [modeline](https://github.com/github/linguist#using-emacs-or-vim-modelines). You can override that with a [`.gitattributes` file](https://github.com/github/linguist#using-gitattributes).

**Comment by alexandermendes** [comment]
Ah ok, that's good to know! All fixed now, thanks :smiley:
