### ISSUE TITLE
Languages like XML not shown in the language bar

### ISSUE THREAD

**Issue by FarbodSalamat-Zadeh** [github/linguist#2818]
I've seen numerous repositories ([my own, for example](https://github.com/FarbodSalamat-Zadeh/LabelledSpinner)), but although they include languages such as `.xml`, `.gradle`, etc., these are not shown in the language bar.

[They can be seen in search](https://github.com/FarbodSalamat-Zadeh/LabelledSpinner/search?utf8=%E2%9C%93&q=), and they are present in the [languages.yml file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) here, so I'm not sure why they don't appear on the language bar.

**Comment by pchaigno** [comment]
Only languages classified as [`markup` or `programming`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) are displayed in the language bar.

**Comment by FarbodSalamat-Zadeh** [comment]
Ah, thanks. Just out of curiosity, why are only markup and programming displayed on the bar?

**Comment by FarbodSalamat-Zadeh** [comment]
Ah, thanks. Just out of curiosity, why are only markup and programming displayed on the bar?

**Comment by FarbodSalamat-Zadeh** [comment]
@pchaigno Ah, thanks. Just out of curiosity, why are only markup and programming displayed on the bar?

**Comment by arfon** [comment]
> @pchaigno Ah, thanks. Just out of curiosity, why are only markup and programming displayed on the bar?

We find this is generally what people are looking for when browsing a repository i.e. what programming languages are used in this repository?

**Comment by davidzchen** [comment]
Is this a recent change? I recall seeing Maven Pom and Gradle displayed in the language bars not too long ago.

Perhaps Maven Pom and Gradle should not be classified as data? Perhaps one can make the argument that `pom.xml` can be data since Maven tries to be completely declarative, but Gradle files very frequently contain code for custom build tasks (e.g. Samza's [`rat.gradle`](https://github.com/apache/samza/blob/master/gradle/rat.gradle)). Similarly, [CMake](https://github.com/github/linguist/blob/9961f8bc1cfc9e986c9e600ef7aa198bd3f4d1ec/lib/linguist/languages.yml#L451) and [Makefile](https://github.com/github/linguist/blob/9961f8bc1cfc9e986c9e600ef7aa198bd3f4d1ec/lib/linguist/languages.yml#L2017) are classified as programming.

**Comment by larsbrinkhoff** [comment]
I'll take the opportunity to briefly mention my idea that maybe there could be a new `build script` class of languages.  Makefile, CMake, Maven, Gradle, etc would all fit in this class.  The build script languages would not affect repository classification.  The reason would be that people are usually more interested in the implementation langauge than the build script.

**Comment by FarbodSalamat-Zadeh** [comment]
@larsbrinkhoff What would the class of `build script` languages be used for? It would be nice (IMO) if the build script languages could be shown as one group on the languages bar (e.g. it may show: Java (90%); Build Scripts (10%)).

**Comment by FarbodSalamat-Zadeh** [comment]
@davidzchen I would agree that Gradle and Maven Pom should not be classified as data, especially Gradle file. It could be linked with @larsbrinkhoff 's suggestion that they are grouped under 'build script' languages.

**Comment by larsbrinkhoff** [comment]
@FarbodSalamat-Zadeh Many build script languages occupy a gray zone between `data` and `programming`.  Most are not pure data, but they may not be full programming languages either.

Also, users are typically unhappy when a repository is classified as a build script language.  So it might make sense to exclude build scripts from the classification candidates.  (Unless there are no other candidates.)

**Comment by FarbodSalamat-Zadeh** [comment]
@larsbrinkhoff I see, that makes a lot more sense now.

I still agree with you on this point, and I can also understand why it is not shown on the language bar.

If I was you, I would open a new issue with this suggestion.

**Comment by davidzchen** [comment]
@larsbrinkhoff That is reasonable. it would be more useful for the build language content to be excluded when classifying the repository itself. For the language bar, though, I still feel that it might be useful to include build scripts since most non-trivial projects would usually have a good amount of non-trivial custom build logic.

Would it be reasonable to have the `build script` category be excluded for classifying the repository yet included in the language bar?

**Comment by larsbrinkhoff** [comment]
@davidzchen Yes, I think that's reasonable.

**Comment by rostopira** [comment]
What about XML-layout files in android projects? When layout created in code it's counted, and when in XML - not? Isn't it as much important as HTML in sites repos? HTML is always counted, btw. I think would be great, if users can specify which file should be included in list

**Comment by FarbodSalamat-Zadeh** [comment]
@rostopira I completely agree with you here, which is why I suggested this in the first place. I am an Android developer too and it's annoying that the XML code isn't displayed even though it's used just like HTML in the context of Android projects.

**Comment by pchaigno** [comment]
@FarbodSalamat-Zadeh Makes sense to me. Maybe you could open a pull request with Android View XML (that way we could count those XML files only) as a new language to initiate discussion. I'm not from GitHub though and I can't guarantee everyone will share my views ;)

**Comment by maillouxc** [comment]
Old issue, but I'd strongly like to second the comments regard android XML layout files. I use the percentages bar to see the structures of my projects. I think repo classification and the language bar should be independent. The language bar should show everything, and the repo classification should work as it does currently.

**Comment by vv7v7** [comment]
Why is XML language not considered as markup one?
