### ISSUE TITLE
Pawn files mismatched as SourcePawn files

### ISSUE THREAD

**Issue by shrmnk** [github/linguist#2823]
I have recently added some of my old plugins I wrote for [AMX Mod X](https://github.com/alliedmodders/amxmodx) (scripting framework used for Half-Life 1/goldsrc engine-based games). The languages these are written in is Pawn, which was later adapted by SourceMod for the Source engine, to make SourcePawn.

Historically, we released the source code for our plugins in files ending with the `.sma` extension. "sma" is short for "_small_", which was the original name of the language before "_Pawn_". Therefore, we sometimes label our language as "**_Pawn/Small_**" - the current definition in the linguist language file is "**PAWN**".

The 2 documented guides for writing Pawn also includes `.pawn` and `.p` as possible file extensions for Pawn files. Therefore,
### Recommended file extensions
- `.sma`
- `.p`
- `.pawn`
### List of repos with sample Pawn files

(I've manually overridden the language through `.gitattributes`)
- https://github.com/ShrmnK/amx_ns_glower
- https://github.com/ShrmnK/amx_ns_elechive
- https://github.com/ShrmnK/amx_ns_swear
- https://github.com/ShrmnK/amx_ns_snipermod

**Comment by pchaigno** [comment]
[`.sma`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3364) is already recognized as SourcePawn.
There are only [102 `.pawn`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Apawn+NOT+dfhdjfhjf&type=Code&ref=searchresults) files so that will probably not be enough to add it to Linguist.
[`.p`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2459) is already an OpenEdge ABL extension. To add `.p` to Pawn, you'll have to show that there are a good number of repositories using them. We'll also have to check the detection accuracy. Please see [the contribution guidelines on how to add a new extension](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language).

**Comment by Crayder** [comment]
Just gonna note, there are "7,445 code results" for `.pwn` which is a PAWN file. `.pwn` is the general extension used for Pawn in SA-MP. We use `.pwn` for the main scripts and `.inc` for the includes. The `y_testing` include in your SourcePawn samples is a SA-MP designated include.

**Comment by pchaigno** [comment]
@Crayder [`.pwn` files are already recognized as PAWN files](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2510), it is not working for you?

**Comment by Crayder** [comment]
I wasn't saying that was the problem, I was just pointing that out.

**Comment by pchaigno** [comment]
Oki :-)
