### ISSUE TITLE
Bash highlight in markdown broken 

### ISSUE THREAD

**Issue by Luchillo** [github/linguist#2840]
Check this out, it should highlight as bash but it doesn't:
![image](https://cloud.githubusercontent.com/assets/9698639/13093053/255c8afc-d4d1-11e5-88e1-d8d26f145370.png)

and here's the file and the raw file: 
https://github.com/Luchillo/Auto-Installer/blob/develop/README.md
https://raw.githubusercontent.com/Luchillo/Auto-Installer/develop/README.md

**Comment by arfon** [comment]
Hi @Luchillo - I believe this is an issue with our markup system. Would you mind opening this issue over there please? https://github.com/github/markup

**Comment by pchaigno** [comment]
@Luchillo Actually, I think this is the expected behavior. The [grammar selected by Linguist to highlight Bash scripts](https://github.com/atom/language-shellscript) doesn't highlight any of the keywords you have, as can be seen [this Lightshow example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-shellscript%2Fblob%2Fmaster%2Fgrammars%2Fshell-unix-bash.cson&grammar_text=&code_source=from-text&code_url=&code=sudo+bash+start.sh).

**Comment by Luchillo** [comment]
Oh i see, as i do bash scripts in sublime and that words are highlighted i tough it was the same, also my markdown plugin does highlight those words:
![image](https://cloud.githubusercontent.com/assets/9698639/13192293/6379c23c-d738-11e5-802b-0aa989958038.png)
