### ISSUE TITLE
No language being detected for NetBSD repo

### ISSUE THREAD

**Issue by jamesqo** [github/linguist#2915]
This mirror repo of the NetBSD source code:

https://github.com/IIJ-NetBSD/netbsd-src

doesn't appear to have a language detected, even though it's full of [plenty][1] of [examples][2] of [C code][3].

Also, may/may not be related, but [this](https://github.com/dotnet/core) repo doesn't have one detected either, while it contains a bunch of [C# files](https://github.com/dotnet/core/blob/master/samples/qotd/Program.cs).

[1]: https://github.com/IIJ-NetBSD/netbsd-src/blob/master/crypto/dist/ipsec-tools/src/racoon/admin.c
[2]: https://github.com/IIJ-NetBSD/netbsd-src/blob/master/sbin/atactl/atactl.c
[3]: https://github.com/IIJ-NetBSD/netbsd-src/blob/master/games/backgammon/teachgammon/data.c

**Comment by pchaigno** [comment]
> Also, may/may not be related, but this repo doesn't have one detected either, while it contains a bunch of C# files.

The C# files in `samples/` are ignored in statistics by Linguist because the `samples` folder is considered *documentation*. You can change that with Linguist overrides, in a `.gitattributes` file:
```
samples/* linguist-documentation=false
```

> This mirror repo of the NetBSD source code:
https://github.com/IIJ-NetBSD/netbsd-src
doesn't appear to have a language detected, even though it's full of plenty of examples of C code.

I suspect that this is happening because of the huge size of the repository (6.2G with `.git`). I made a copy of the repository, removed the `external` folder (2.1G) and re-initialized `.git` (`git init`). Linguist works fine on this copy (900M with `.git`).

**Comment by arfon** [comment]
> I suspect that this is happening because of the huge size of the repository (6.2G with `.git`). I made a copy of the repository, removed the `external` folder (2.1G) and re-initialized `.git` (`git init`). Linguist works fine on this copy (900M with `.git`).

Yeah, I tried to manually run the language detection script from our admin tools and I'm afraid it doesn't complete.

**Comment by pchaigno** [comment]
Even locally it fails to complete (which would indicate that the problem comes from Linguist itself...).

**Comment by arfon** [comment]
> Even locally it fails to complete (which would indicate that the problem comes from Linguist itself...).

I suspect the language calculation job is timing out somewhere in our infrastructure either because of memory usage and/or the time the job takes to run.

I don't see us prioritizing this anytime soon sorry because it feels like an edge case for very large repositories. I'm therefore going to close this.

**Comment by pchaigno** [comment]
Linguist currently returns no language counts - even when run locally - because of [this line, which limits the number of blobs in the repository to 100,000](https://github.com/github/linguist/blob/master/lib/linguist/repository.rb#L135).

If I increase the number of blobs to 200,000 (there are around 196k blobs in that repository), Linguist takes around 3 minutes to execute on [netbsd-src](https://github.com/IIJ-NetBSD/netbsd-src) on my computer (running on a single 2.4GHz core).
This is only because it's the initial run. Since the computation of statistics is incremental, subsequent computations would be much faster.

**Comment by arfon** [comment]
> Linguist currently returns no language counts - even when run locally - because of this line, which limits the number of blobs in the repository to 100,000.

Good find @pchaigno. I'll see what the systems/infrastructure team think about bumping the file limit for production.

**Comment by sanajitjana** [comment]
The same problem - language was not detected for this repo https://github.com/sanajitjana/react-map-method

**Comment by lildude** [comment]
@sanajitjana It looks like the analysis job didn't run or complete successfully when you pushed. Try pushing another change and that should kick off the job.
