### ISSUE TITLE
Wrongly states repository is Perl6, actual language Turing

### ISSUE THREAD

**Issue by MathBunny** [github/linguist#2940]
My recent GitHub repository was coded in a Turing file (*.t), but it is marked as Perl6.

Link: https://github.com/MathBunny/connect-four

**Comment by pchaigno** [comment]
You can fix the issue locally, on your repository, with [Linguist overrides](https://github.com/github/linguist#overrides). If it's a general issue on github.com, we could add new heuristic rules to distinguish between Turing, Perl, Perl6 and Terra files.

**Comment by Alhadis** [comment]
@MathBunny The [Turing sample](https://github.com/github/linguist/blob/master/samples/Turing/turing.t) that Linguist uses looks pretty basic. It would probably help the classifier if it had a more substantial fixture to work off.

[Your program](https://github.com/MathBunny/connect-four/blob/master/ConnectFour.T) looks like it'd be a good example, but we can't use it unless it's released under a permissive license (like MIT, ISC, Apache-2, etc).

At the moment, your project's license isn't listed, so I'm not sure how you'd feel about this.

**Comment by arfon** [comment]
Closing this out as #3040 is merged.

**Comment by Alhadis** [comment]
I'll test this locally, and if the repo is still being misclassified, I'll write a heuristic. =)

**Comment by MathBunny** [comment]
@Alhadis I was looking at the file `test_heuristics.rb`, and I couldn't find Turing there, but I saw Perl6 was listing there with the extension `*.t` - is this how it's supposed to work? Shouldn't Turing be listed there?

**Comment by Alhadis** [comment]
Haha, no no. =) Linguist identifies files based on the frequency of certain patterns and tokens, which is good enough for most cases. However, there are situations when it gets stuck or confused, and it needs human help to push it in the right direction. Those are the times when a heuristic is written is help.

[This](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L310-L316) heuristic would've been written to help Linguist tell the difference between Perl and Perl6, since both languages use the `.pm` and `.t` extensions, and both probably have a lot in common (I only know Perl, never been bothered to learn Perl6, and I frankly don't want to).

**Comment by MathBunny** [comment]
Got it! Thanks :)

**Comment by Alhadis** [comment]
No wukkaz!

(That's Australian for *"you're most welcome"*).

**Comment by Alhadis** [comment]
@MathBunny, you'll be pleased to know a heuristic won't be necessary. Your sample's educated Linguist on Turing perfectly. :D Have a look at the result:

<img src="https://cloud.githubusercontent.com/assets/2346707/15861408/a36d1dbc-2d0f-11e6-9605-9e767d03497a.jpg" alt="" width="490" />

**Comment by MathBunny** [comment]
Amazing, glad it worked out!
