### ISSUE TITLE
C main.c is tagged as scheme

### ISSUE THREAD

**Issue by mowgli** [github/linguist#2942]
[This](https://github.com/BestImageViewer/geeqie/blob/1797b9e1a522b077f852aa560b35d0fca018c603/src/main.c) main.c that is clearly plain C is wrongly tagged as Scheme language.

Maybe that is linked to issue #2197.

**Comment by pchaigno** [comment]
@mowgli This is happening because [this line in your file](https://github.com/BestImageViewer/geeqie/blob/1797b9e1a522b077f852aa560b35d0fca018c603/src/main.c#L552) matches [the regex for Emacs modelines](https://github.com/github/linguist/blob/master/lib/linguist/strategy/modeline.rb#L4).
The current regex was introduced in #2233 by @tesch1.

@arfon I'm wondering if we should check only the beginning and the end of files for the modeline. It may show some performance improvement, as well as solve this bug (although it's probably a corner case).

**Comment by tesch1** [comment]
The emacs "modeline" of this style (in emacs-speak: "file variable") can only appear in the first line, so yes, it would be more correct to check for it only there.

**Comment by arfon** [comment]
> @arfon I'm wondering if we should check only the beginning and the end of files for the modeline. It may show some performance improvement, as well as solve this bug (although it's probably a corner case).

Yeah perhaps we should scope this to the first (and last) 5 lines or something?
