### ISSUE TITLE
Javascript in repos

### ISSUE THREAD

**Issue by staabm** [github/linguist#2968]
The repo https://github.com/krakjoe/bundle doesnt contain a single line javascript, but the github language statistics shows ~36% javascript

Is this intended?

**Comment by pchaigno** [comment]
[This file](https://github.com/krakjoe/bundle/blob/c1d5ed2c2b5fc137b610787b0d9a39e312bbdd11/Makefile.frag) (`Makefile.frag`) is detected as JavaScript because [`.frag` is defined as a potential file extension](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1710). What language should is be detected as?

**Comment by staabm** [comment]
It should be a makefile

**Comment by pchaigno** [comment]
I will add `Makefile.frag` as a [filename for Makefile](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2083). Can I use your file as a sample (there isn't a license in your repository)?

**Comment by krakjoe** [comment]
License added, thanks :)

**Comment by pchaigno** [comment]
Thanks!

#2969 should fix this ;)

**Comment by arfon** [comment]
Fixed in #2969
