### ISSUE TITLE
Repository Language Detection - Arduino

### ISSUE THREAD

**Issue by jaredpetersen** [github/linguist#2985]
Linguist is only displaying one language for [my repository](https://github.com/jaredpetersen/ghostlab42reboot) even though multiple are used. Clicking on the language brings up the [accurate language classifications](https://github.com/jaredpetersen/ghostlab42reboot/search?l=cpp) but these are not factored into the repository languages header.

It should be bringing up C++ and Arduino but it is only displaying C++. I made sure that Arduino is a supported language and that the Arduino file extension was already included in Linguist. Another Arduino library repository's language header is working fine ([https://github.com/jmax33/arduino_libShiftRegister](https://github.com/jmax33/arduino_libShiftRegister)).

**Comment by pchaigno** [comment]
Arduino files are not counted in the statistics because they are in the `examples` directory which is [classified as `documentation` by Linguist](https://github.com/github/linguist/blob/9ae19a1f9470a6f15a1ae70f870c044f55e9d8f5/lib/linguist/documentation.yml#L16). See [Linguist overrides](https://github.com/github/linguist#using-gitattributes) to change this default behavior. In particular, you could add a `.gitattributes` file:
```
examples/**.ino linguist-documentation=false
```

**Comment by jaredpetersen** [comment]
That makes sense, thanks for the help @pchaigno.
