### ISSUE TITLE
Confusion between OCaml and Standard ML on very short files

### ISSUE THREAD

**Issue by Zimmi48** [github/linguist#3002]
Hi,

I have just detected that some very short files written in OCaml were misclassified as Standard ML. For instance, here in the OCaml compiler repository:
https://github.com/ocaml/ocaml/search?l=standard-ml

The explanation is most likely that these files are both correct SML and correct OCaml, the syntax of the two being quite close.

It seems to me that a good fix would be to take the statistics of the whole repository into account in case of ambiguity for a few files. In this case, the majority of the files in the repository are correctly classified as OCaml.

Thanks!

**Comment by lildude** [comment]
A little late to the party... I've not managed to get this far into the backlog until now. 😉

Linguist can't take the whole repository into account as there would be no way of knowing if the user intended to include Standard ML in the repo along with the OCaml. Yes, probably not likely, but it could happen with other repos and similar files. In fact, if we did that, many files within this repo could be misidentified if we looked at the repo as a whole. C/C++/Objective-C are very much in the same situation and are commonly misclassified because of small header files.

As the files are so small, there's very little chance the classifier or heuristics will be able to glean enough from the files for an accurate identification, so the only option is include a modeline identifier within the file itself or implement a [manual override to force the language](https://github.com/github/linguist#overrides) for those files that have been misidentified.

I'm going to close this issue on the understanding that a modeline or manual override is really the only option for correctly identifying small files in situations like this as there's very little consistency within the files themselves that could be used to automate this.
