### ISSUE TITLE
Code statistical result issue "We couldn't find any code matching"

### ISSUE THREAD

**Issue by cyjseagull** [github/linguist#3004]
Repo code statistical result shows that 80.2% part of total codes are Groff. However, most of my codes are C++ actually. When I click "Groff" , I have got "We couldn't find any code matching" " in page https://github.com/cyjseagull/SHMA/search?l=groff. The repo URL is https://github.com/cyjseagull/SHMA. Looking forward to your response.

**Comment by pchaigno** [comment]
[These `.1M` files](https://github.com/cyjseagull/SHMA/tree/master/zsim-nvmain/nvmain/traceReader/GEMS_Samples/traces) are recognized as Groff files and count for a large part of statistics because they are quite large. Please take a look at [Linguist overrides](https://github.com/github/linguist#overrides) to ignore them in statistics.

**Comment by Alhadis** [comment]
I had a look at it, but couldn't figure it out.

👆 I love this guy.

**Comment by pchaigno** [comment]
@Alhadis I always just download and run Linguist locally on it :-)
We should have an Heroku app to do that...

**Comment by cyjseagull** [comment]
Thank you very much! Problem has been solved. My project is marked as C++ project normally.
