### ISSUE TITLE
Are GPL'ed sample files ok?

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#3057]
There seems to be a few GPL-licensed sample files:

http://github.com/github/linguist/search?q=path%3Asamples+gpl

Are those ok?

Cf #3054

**Comment by arfon** [comment]
Errr, probably not. We should try and swap these out for non-GPL examples.

**Comment by larsbrinkhoff** [comment]
Note that there are probably more GPL'ed files that those matching that searching.  Hopefully the commit message may reveal some more; the rest is anyone's guess.

**Comment by sahildua2305** [comment]
@arfon How to choose samples for a particular language? Are they taken randomly from the public repos with desired type of license? Are there any constraints (size, content, etc.) on files which can be chosen as samples?

**Comment by pchaigno** [comment]
@sahildua2305 To select sample files, I think it's important to understand how they're used:

**Bayesian classifier:** Sample files are used by [the naive Bayesian classifier](https://github.com/github/linguist/blob/5ac2cdde5053d3cf811a197d35af713e6330e91f/lib/linguist/classifier.rb) as training data. The Bayesian classifier is used [as last resort](https://github.com/github/linguist/blob/5ac2cdde5053d3cf811a197d35af713e6330e91f/lib/linguist.rb#L49-L66) when other strategies failed to recognize the language of a file. It associates distributions of keywords to languages based on their sample files. For instance, JavaScript may be associated with a high number of `var` keywords and a low number of `class` keywords (and many other keywords).
Files to classify are then assigned a language based on their own distribution of keywords. For instance, a file with a high number of `var` keywords and no `class` keywords might be classified as JavaScript.
(It's a simplified explanation as there's actually a bit of probability theory involved.)

**Selecting sample files:** From the above we can deduce a few guidelines to select sample files.
First, sample files should be as representative of the actual distribution of keywords of the language as possible. That means sample files with simple hello worlds should be avoided. You should also avoid files that use a restricted number of keywords (such as files with only constants being declared). In my opinion the best is to select sample files from actual production applications.
Second, it's best to select a few sample files of medium size from several sources rather than a single large file. The diversity of files should help better reflect the diversity of coding styles and patterns.
Finally, we also try not to add too many sample files because of the issue discussed at #2117. A couple of sample files per extension is usually enough.

These are only guidelines and may not always hold true, but I hope it helps.

**Comment by sahildua2305** [comment]
@pchaigno Thanks a lot for detailed overview, Paul! I have understood the basics of how the classifier works (have worked with Bayesian classifier earlier).

Can I create a PR for any single (or a couple of) extension(s) or do I have to cover multiple extensions' sample files altogether?

**Comment by pchaigno** [comment]
A single pull request is more convenient for us to merge, but if you prefer to divide it into several pull requests, that's probably fine too.

**Comment by sahildua2305** [comment]
@pchaigno @arfon Can I add code written by me in the samples? I can add MIT license in those files if that's required. Does that code has to be on GitHub? I have a lot of C++ code written by me which was for general purpose written in last over 2 years and I think it can serve good purpose as sample for C++.

**Comment by arfon** [comment]
> @pchaigno @arfon Can I add code written by me in the samples?

Yep, that should be fine. Please make sure there's a license (MIT preferred) but the code doesn't need to be on GitHub.

**Comment by sahildua2305** [comment]
Cool!

Does Apache License allow redistribution under MIT?

**Comment by arfon** [comment]
> Does Apache License allow redistribution under MIT?

I don't think so but we don't absolutely need things to be licensed under MIT. We just need them to be licensed under a permissive license (MIT, Apache 2, BSD etc).

**Comment by larsbrinkhoff** [comment]
Question has been answered.  Resolution in progress.
