### ISSUE TITLE
Syntax highlighting not working with script tag and type="text/ecmascript-6"

### ISSUE THREAD

**Issue by stoewer** [github/linguist#3072]
If an html `<script>` tag has the attribute `type="text/ecmascript-6"` the content is not highlighted as javascript:

```html
<script type="text/ecmascript-6">
    function printFoo(foo) {
        console.lot(foo)
    }
</script>
```

However, it does work with  `type="text/javascript"`:

```html
<script type="text/javascript">
    function printFoo(foo) {
        console.lot(foo)
    }
</script>
```

Some editors and IDEs (e.g. Jetbrains products) require this attribute to be present in order to treat the content of `<script>` tags appropriately. This issue arises frequently when one is using Vue.js with [*.vue files like this](https://github.com/G-Node/gin-ui/blob/7c77a6e87d000f8d1fe22ef9b901c8a6a0f19f98/src/App.vue).

The highlighting is also not working if a `<script>` tag has `type="text/babel"`, which is also commonly used to indicate es6 content in a `<script>` tag.

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For JavaScript, GitHub uses [atom/language-javascript](https://github.com/atom/language-javascript/tree/83f9e51bc96b56d392e603c6efbbfba453e7c4a7). You should open an issue there if there isn't already one ;)

**Comment by Alhadis** [comment]
@pchaigno This actually seems to be an issue with the HTML syntax.

Seems Linguist is using the [TextMate grammar](https://github.com/textmate/html.tmbundle) for highlighting instead of Atom's. Interestingly enough, if Atom's grammar is used for highlighting, it [works fine](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-html%2Fblob%2Fmaster%2Fgrammars%2Fhtml.cson&grammar_text=&code_source=from-text&code_url=&code=%3Cscript+type%3D%22text%2Fecmascript-6%22%3E%0D%0A%09function+printFoo%28foo%29+%7B%0D%0A%09%09console.log%28foo%29%0D%0A%09%7D%0D%0A%3C%2Fscript%3E).

I think we should switch...

**Comment by pchaigno** [comment]
@Alhadis - Ooh, right!
@stoewer -  [textmate/html.tmbundle](https://github.com/textmate/html.tmbundle) it is!

> I think we should switch...

If they're other issues, I agree. But otherwise, we'd probably better open a pull request ;)
That said, I don't think there's a single grammar free of any issue. It's just that difficult to parse context-free grammars with regular expressions :stuck_out_tongue_winking_eye:

**Comment by Alhadis** [comment]
> That said, I don't think there's a single grammar free of any issue.

Nope, of course not. However, Atom's grammars are updated frequently, and would arguably be a better fit for fast-moving technologies like CSS and HTML. Conversely, TextMate's grammar repos aren't updated all that frequently, and don't receive as much input from users as Atom's grammars do.

**Comment by stoewer** [comment]
> @stoewer - textmate/html.tmbundle it is!

Thank's, I'll report it there.

**Comment by luke-j** [comment]
`type="text/babel"` should now work in *.vue files as per my pull request [here](https://github.com/vuejs/vue-syntax-highlight/pull/57)

**Comment by pchaigno** [comment]
Closing as this needs to be fixed upstream.
