### ISSUE TITLE
Accent Highlight in Go Source 

### ISSUE THREAD

**Issue by songgao** [github/linguist#3118]
Hi there!

Go [supports](https://golang.org/ref/spec#Identifiers) using any Unicode letter in identifiers, but it seems the syntax highlight breaks when there is an accent character. For example:

```go
type CaféStruct struct {
}

func CaféString() {
  return "Café"
}
```

It'd be nice to have these properly highlighted!

**Comment by pchaigno** [comment]
Linguist only selects the grammar to use for highlighting. For Go, GitHub uses [AlanQuatermain/go-tmbundle](https://github.com/AlanQuatermain/go-tmbundle/tree/0bdec37eded22e8416d046fe28e50d2c5c666798). You should open an issue there if there isn't already one ;)
This issue is also related to atom/atom#10309.
