### ISSUE TITLE
SourcePawn stock repository detected as partially C++

### ISSUE THREAD

**Issue by nosoop** [github/linguist#3156]
[nosoop/stocksoup](https://github.com/nosoop/stocksoup) has a few include files (with `.inc` suffix) that are being incorrectly classified as C++.  The project only contains SourcePawn code, all which are include files.

[nosoop/newdecl-handles](https://github.com/nosoop/newdecl-handles) is also being classified as completely C++.

A thing that might be of note is that SourcePawn, as of SourceMod's 1.7 version, has added [a transitional syntax](https://forums.alliedmods.net/showthread.php?t=244092) which is more similar to C# and Java than Pawn.  While the new syntax is preferred, scripts written in the old syntax will still compile on recent compilers, and scripts can contain a mix of old/new syntax.

[More information about the new syntax is available here.](https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax)

**Comment by pchaigno** [comment]
Any keyword or construct unique to SourcePawn that we could [use to recognize it](https://github.com/github/linguist/blob/0e9109c3fcdacb17b27581710c7b435086b70485/lib/linguist/heuristics.rb#L202)?

**Comment by nosoop** [comment]
`stock`  is a common function declaration prefix in Pawn-like language include files, including but not limited to SourcePawn.

`methodmap` is a declaration unique to SourcePawn's transitional syntax, but its use isn't guaranteed.

**Comment by pchaigno** [comment]
Is it always `^stock nameoffunction\(`?

**Comment by nosoop** [comment]
Transitional syntax requires a return type, but the old syntax does not.  Would have to match the following:

* `stock return_type function_name(` to match SourcePawn's transitional syntax only
* `stock function_name(` and `stock return_type:function_name(` to match Pawn-likes in general

As far as I can tell, `^\s*stock\s+(\w+(\s+|\s*:\s*))?\w+\s*\(` correctly matched all the ones I threw at it, including variable amounts of spaces between the opening parenthesis and surrounding the colon.

For completeness' sake, `^\s*stock\s+\w+\s+\w+\s*\(` can be used to only match SourcePawn's transitional syntax, and `^\s*stock\s+(\w+\s*:\s*)?\w+\s*\(` can be used to only match Pawn-like stock declarations.

**Comment by pchaigno** [comment]
Thanks for the detailed explanation.

Does that mean [this file](https://github.com/github/linguist/blob/8dc4a1308f7d309ebdf5566251eca3f5562d8901/samples/SourcePawn/mfile.inc#L58) is actually a PAWN file?

**Comment by nosoop** [comment]
`mfile.inc` is definitely not SourceMod's flavor of Pawn (uses a different file open call).  The function declarations listed could be done in SourcePawn, though.

The `CallLocalFunction` call suggests the file is from a variant of Pawn used for San Andreas Multiplayer (SA:MP).  `y_testing.inc` and `Check.inc` are also for SA:MP.

`foo.sma` is for AMX Mod X based on file extension; it's a much closer relative compared to SA:MP (it's Pawn for an older engine in the same family as the engine that SourcePawn scripts are used for).

`fixed.inc` is for CompuPhase's PAWN; I don't think `operator` constructs are valid in SourcePawn.

`foo.sp` is SourcePawn.

**Comment by pchaigno** [comment]
Crap! Looks like I'm gonna have to move everything... Do you know where I could find samples of SourcePawn files for `.sma` and `.inc`?

**Comment by nosoop** [comment]
The include files in [this repository][bit-mckay] are SourcePawn.  `.inc` files dated from before 2015 use the older Pawn-style syntax, 2015 ones use the new syntax.  [This repository has some as well.][gh-powerlord]  The [transitional helpers repository][gh-thelpers] has a good amount of samples that only implement methodmaps, no stock functions.

The [SourceMod repository][sourcemod] has the standard library includes.

[This forum][am-inc] has samples for AMX's flavor of Pawn.  I'm not as knowledgeable in that domain, so I can't give any more precise examples.  Should be fine just opening a few threads labeled "[INC]" and scrolling down to the download on the first post in each.  (`.sma` is apparently AMX's equivalent to SourceMod's `.sp` "main" files; they both use `.inc` for includes.)

Also, forgot to note:  AMX's Pawn is a lot closer to Pawn when it comes to syntax; the C#-style syntax isn't available there.

[bit-mckay]: https://bitbucket.org/Doctor_McKay/public-plugins/src/d92573285b1821a916d7c8bb1aafa1ebab3bb45a/scripting/include?at=default
[gh-powerlord]: https://github.com/powerlord/sourcemod-snippets/tree/master/scripting/include
[sourcemod]: https://github.com/alliedmodders/sourcemod/tree/master/plugins/include
[am-inc]: https://forums.alliedmods.net/forumdisplay.php?f=83
[gh-thelpers]: https://github.com/VoiDeD/sourcemod-transitional-helpers

**Comment by pchaigno** [comment]
Unfortunately, all these repositories are either under GPLv3 license or don't have one :/
We need a permissive license for samples as Linguist is under MIT license.

**Comment by nosoop** [comment]
That's going to be a bit tricky, then.  [The licensing for SourceMod](https://svn.alliedmods.net/viewvc.cgi/trunk/public/licenses/LICENSE.txt?revision=2255&root=sourcemod) states that derivative works must be licensed under GPLv2+.

Maybe I could write a sample file that only demonstrates syntax without including GPL-licensed files?

**Comment by pchaigno** [comment]
Sample files are used to train the Bayesian classifier, so demo files tend to skew its results. We usually prefer sample files from "real" applications. Could you relicense a file from one of your repository under a permissive license? If you prefer to avoid that, we'll have to do with a realistic sample file written specifically for this.

**Comment by nosoop** [comment]
Honestly, I've been releasing my projects as GPL because I'm not a lawyer and I can't wrap my head around the licensing stuff.

Provided no issues (e.g., I can still reference SourceMod's GPLv3-licensed standard library), I'd be more than happy to relicense all of my personal SourcePawn code as MIT.

**Comment by pchaigno** [comment]
> Honestly, I've been releasing my projects as GPL because I'm not a lawyer and I can't wrap my head around the licensing stuff.

Me neither and I've found http://choosealicense.com to be of great help.

**Comment by nosoop** [comment]
Whoops, poor wording on my part.  I'm actually already really fond of MIT's simplicity (some non-SourceMod projects I wrote are licensed under that); just didn't want the hassle of checking for incompatibilities when it comes to writing SourceMod stuff in particular since the whole "all derivative works must be GPL" bit in their license is pretty intimidating.

If I can get a definitive answer to any limitations for MIT-compatible SourcePawn code ([I've also asked on the primary SourceMod forum here](https://forums.alliedmods.net/showthread.php?p=2477085#post2477085)), I'll go with whatever's appropriate.

**Comment by Caged** [comment]
:wave: Going to close this as it appears we can't move forward with the license as is.  Please feel free to reopen if there's a compatible license, or if I misinterpreted the status of this issue.

**Comment by X6B0ISI09wD4** [comment]
@pchaigno is there nothing that can be done to improve this due to the licensing? Early on in the issue you asked if there are any unique keywords or constructs in SourcePawn, is it possible to match files on those without violating the licensing conditions set by AlliedModders?

To add, this repository contains an old version of `mapchooser.sp` named [`foo.sp`](https://github.com/github/linguist/blob/7be6fb013864b59e7c9ba76e3c0062dd95cedc76/samples/SourcePawn/foo.sp), this file is licensed under GPLv3 so it shouldn't be redistributed here under the MIT license, correct?

Thanks.

**Comment by lildude** [comment]
> @pchaigno is there nothing that can be done to improve this due to the licensing? Early on in the issue you asked if there are any unique keywords or constructs in SourcePawn, is it possible to match files on those without violating the licensing conditions set by AlliedModders?

Not really. We can create a heuristic, but we still need a sample under a permissive license for the classifier which is used to catch things that fall through the heuristic.

> To add, this repository contains an old version of mapchooser.sp named foo.sp, this file is licensed under GPLv3 so it shouldn't be redistributed here under the MIT license, correct?

Whooops. That definitely needs to go.

**Comment by X6B0ISI09wD4** [comment]
@lildude won't removing that file make the language unsupported on GitHub?

**Comment by lildude** [comment]
@X6B0ISI09wD4 I'm currently in discussions with our legal team regarding the license of samples. I'll provide an update once I know for certain where we stand.

**Comment by lildude** [comment]
I've spoken with our legal team, and whilst we'd prefer _not_ to include copyleft licensed samples, there shouldn't be any problems with us doing so from a licensing perspective as...

- we're only including them in the repo as data and not as executable or linked code, and
- when building a release, we break up the samples into tokens that don't represent the original code. These tokens are "stored" in the `samples.json` file which we _do_ use and ship within the gem.

So we can leave the GPL licensed samples in place (we've got quite a few already), and if absolutely necessary (we'd prefer not to if possible), can accept copyleft licensed samples in future.

We can _**not**_ however accept copyleft or restrictively licensed grammars as these _are_ shipped as linkable and executable code.

I'm reopening this issue as licensing of the samples should not hinder improving the classification.

/cc @pchaigno @Alhadis @larsbrinkhoff for future reference.
/cc @mlinksva

**Comment by X6B0ISI09wD4** [comment]
@lildude that's great to hear. I don't think it's possible to avoid including GPL licensed samples in SourcePawn's case as [their license is very restrictive](https://github.com/alliedmodders/sourcemod/blob/master/public/licenses/LICENSE.txt) and all derivative works must be under version 2 or 3 of the GPL.
<hr>

About this issue itself though (#3156) what can actually be done?

Something I noticed is that [not one of the samples for SourcePawn](https://github.com/github/linguist/tree/master/samples/SourcePawn) is in the new transitional syntax which is still optional as of SourceMod `1.9` but is becoming the standard. Also [AMX Mod X](https://github.com/alliedmodders/amxmodx) has been mixed in with [SourcePawn](https://github.com/alliedmodders/sourcepawn) which is strange.

Also just curious with the [SourcePawn submodule](https://github.com/github-linguist/sublime-sourcepawn/tree/d5e1022a4e09cdba32b416e682a2c31c72240733) which file(s) in that repository are used by linguist? It would be great if [Dillonb/SublimeSourcePawn](https://github.com/Dillonb/SublimeSourcePawn) could replace that as it's received and still is receiving updates from Tsunami to include the new syntax and natives as they release.

**Comment by lildude** [comment]
> About this issue itself though (#3156) what can actually be done?

Well, the problems and changes you've mentioned suggest we need to update Linguist to take these changes into account. I certainly don't have any experience with SourcePawn, but you seem to so please review the [contributing guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md) and open a pull request. 

This PR can include new samples for the new syntax you've mentioned and also a switch to the syntax highlighting grammar.  Just keep in mind that we will _not_ accept a grammar that is _not_ licensed under one of [these licenses](https://github.com/github/linguist/blob/257425141d4e2a5232786bf0b13c901ada075f93/vendor/licenses/config.yml#L2-L11) - the grammar you've referenced doesn't have a license from what I can see.

> Also just curious with the SourcePawn submodule which file(s) in that repository are used by linguist?

From a quick look, it'll mostly be [`sourcepawn.tmLanguage`](https://github.com/github-linguist/sublime-sourcepawn/blob/master/sourcepawn.tmLanguage) as this is what defines the syntax highlighting grammar.

**Comment by X6B0ISI09wD4** [comment]
@lildude a few more queries I have before diving into the contributing guidelines.
1. The best samples are probably the plugins bundled with SourceMod from the official [`alliedmodders/sourcemod`](https://github.com/alliedmodders/sourcemod) repository, the previously mentioned `mapchooser.sp` (known as `foo.sp` in this repository) is an example of one. These are of course all licensed under the GPL v3. My question is do you also need explicit permission from the sample's author for it be used in Linguist or does the license allow its use here automatically?

1. As you said @Dillonb's repository doesn't seem to have any license at all, does that prevent its use in Linguist? I'm not sure if completely unlicensed works are included. If it does I will try to get in contact with him before any kind of PR as I think the 100s of new natives, forwards, tags and keywords will do wonders in differentiating the rather vaguely suffixed `.inc` files.

1. Would further disambiguation between `.inc` files still be possible with what @pchaigno mentioned [here](https://github.com/github/linguist/issues/3156#issuecomment-264709896)? A lot of SourcePawn includes are misidentified as `C++` and even if the improved grammar can be implemented most simple  includes won't benefit from it that much.

    If so how would I go about implementing that? There are some quite unique constructs with naming conventions put in place by the wiki that should only exist in SourcePawn.

    A couple of examples would be:
- `public SharedPlugin __pl_myfile =` or `public SharedPlugin:__pl_mapchooser =`
- `public void __pl_mapchooser_SetNTVOptional()` or `public __pl_mapchooser_SetNTVOptional()`

**Comment by pchaigno** [comment]
> My question is do you also need explicit permission from the sample's author for it be used in Linguist or does the license allow its use here automatically?

When you submit the pull request, you'll have to sign [GitHub's CLA](https://cla.github.com/), in which you state you have the rights to submit this contribution (see `3. Source of Contribution`).

> As you said @Dillonb's repository doesn't seem to have any license at all, does that prevent its use in Linguist?

Yes. For grammars in Linguist, we need a permissive license. Politely asking the author to add one often works :-)

> Would further disambiguation between .inc files still be possible with what @pchaigno mentioned here?

Yes, I'm hoping we can. We should probably start with the samples and the grammar since the disambiguation work is a bit more complex.
It looks like we'll have to do some cleaning (moving incorrectly classified samples) and we could add a heuristic rule with the constructs you mentioned.

**Comment by X6B0ISI09wD4** [comment]
@pchaigno thank you, that all sounds great. When you say moving incorrectly classified samples could you give an example? I'm a little confused what that means. Also I forgot to ask in my previous comment, is there a limit to the amount of samples one language can have in the Linguist repository or a guideline at least?

**Comment by pchaigno** [comment]
> When you say moving incorrectly classified samples could you give an example?

I'm referring to [this post](https://github.com/github/linguist/issues/3156#issuecomment-266288954), but I can take care of that once your PR is merged.

> is there a limit to the amount of samples one language can have in the Linguist repository or a guideline at least?

Yes, there's a limit because the resulting training file is loaded in memory. We usually limit ourselves to 2-3 sample files (with say, a few hundred lines per file) per file extension. We try to use sample files from "real" application (i.e., not sample files written for the occasion) because they are then used by the Bayesian classifier and in our tests.

**Comment by X6B0ISI09wD4** [comment]
Hmm, I feel like that should be done first @pchaigno, if there's a good reason it shouldn't though I'm happy to carry on with the other stuff.
<hr>

I'll give some more information on the situation in case it comes in handy when you decide what to do.
 [AlliedModders LLC](http://alliedmods.net/) have produced and maintain a multitude of _mods_ for games. The two that are relevant to this issue are [`AMX Mod X`](https://github.com/alliedmodders/amxmodx) and [`SourceMod`](https://github.com/alliedmodders/sourcemod).

`AMX Mod X` is a server modification for [`GoldSrc`](https://developer.valvesoftware.com/wiki/Goldsource) games such as the original Counter-Strike. _Plugins_ for this _mod_ are written in [CompuPhase](https://www.compuphase.com/)'s [`Pawn`](https://github.com/compuphase/pawn) language formerly known as [`Small`](https://www.compuphase.com/small.htm) _(this is where the `.sma` suffix comes from)_. The scripts themselves should always be suffixed with `.sma` and includes should always be suffixed with `.inc`.

`SourceMod` is a server modification for [`Source`](https://en.wikipedia.org/wiki/Source_(game_engine)) games such as the currently popular Counter-Strike: Global Offensive. _Plugins_ for this _mod_ are written in [AlliedModders LLC](http://alliedmods.net/)'s _Pawn-modification_ [`SourcePawn`](https://github.com/alliedmodders/sourcepawn) _(this is where the `.sp` suffix comes from)_. The scripts themselves should always be suffixed with `.sp` and includes should always be suffixed with `.inc`.

To add to the confusion [`SA-MP`](https://www.sa-mp.com/) (San Andreas Multiplayer) also uses [CompuPhase](https://www.compuphase.com/)'s [`Pawn`](https://github.com/compuphase/pawn) language for its _plugins_. Luckily these plugins use the somewhat more common `.pwn` suffix for the plugins themselves and again they use the `.inc` suffix for includes.
<hr>

- The first thing I noticed is that in Linguist there is only `PAWN` and not `Pawn`, I had a quick look around online and couldn't find any other languages with the same name, just [CompuPhase](https://www.compuphase.com/)'s `Pawn`, so that language should probably be renamed unless I'm mistaken.

- While `SourcePawn` is based on `Pawn` it has built on it a lot in the past decade and I don't think it's really appropriate to umbrella the original under it anymore, not to mention the entire syntax changed from `Pawn`'s in mid-2014 to a completely new one. I think the `AMX Mod X` and `SA-MP` samples/grammars/suffixes need to be transferred to `Pawn` _(or `PAWN` if it's not renamed)_.

- [CompuPhase](https://www.compuphase.com/)'s own [`Pawn` examples](https://github.com/compuphase/pawn) use the `.p` suffix _(i'm not sure what the `.i` files are for under `/rpn`)_ and [their includes](https://github.com/compuphase/pawn/tree/master/include) use `.inc`. You can see in their repository that the includes are being misclassified as `SourcePawn`.

    As suggested in #2823 I think the appropriate action is to include `.p`, `.pwn`, `.pawn` and `.sma` as `Pawn` extensions.
<hr>

That should be a good start, sorry for the long read 😖

**Comment by X6B0ISI09wD4** [comment]
Any update on this @pchaigno?
<hr>

Also @lildude you previously said Linguist can use the `.tmLanguage` format for grammars, can it also use `.tmLanguage.json` or are these two easily _convertable_, I've never looked into TextMate grammars before but a quick search doesn't yield much information on this.

It seems there's a more up-to-date grammar being maintained for [a vscode extension for SourcePawn](https://github.com/Dreae/sourcepawn-vscode/blob/master/syntaxes/sourcepawn.tmLanguage.json) and it's licensed under the MIT license 🎉.

**Comment by lildude** [comment]
> Also @lildude you previously said Linguist can use the `.tmLanguage` format for grammars, can it also use `.tmLanguage.json` or are these two easily convertable, I've never looked into TextMate grammars before but a quick search doesn't yield much information on this.

From what I've seen `.tmLanguage.json` is generally generated from a `.tmLanguage` (plist) file and we certainly have a few grammars using `.tmLanguage.json` as the only option so I don't think there'll be any problems with using the JSON version rather than the PLIST version.

> It seems there's a more up-to-date grammar being maintained for a vscode extension for SourcePawn and it's licensed under the MIT license 🎉.

🎉 Feel free to include a switch to this in your PR.

**Comment by Dillonb** [comment]
I'm happy to add a license to my [repo](https://github.com/Dillonb/SublimeSourcePawn) so it can be used here, but I haven't touched SourcePawn in quite a few years, and I don't even use Sublime Text anymore. I'd definitely suggest using the grammar from the vscode plugin over mine.

**Comment by DJPlaya** [comment]
Yea, mind the Syntax Change in 1.8, i dont think we need support for the older Style.

**Comment by pchaigno** [comment]
@Dillonb If your grammar or the vscode one perform better than the current one (you can check/demonstrate that quickly with [Lightshow](https://github-lightshow.herokuapp.com)), we'd definitely welcome a pull request implementing the change. I can help for the pull request if necessary.

**Comment by X6B0ISI09wD4** [comment]
@pchaigno any chance we can open this issue again? Also, could you elaborate on b4a77abd82d9613f35790bc8e0b251ffd028542b, is this fork procedure needed if we switch to a different grammar?
<hr>

Due to Dreae's support for newer language features, his grammar is most likely the best fit now. It does differ quite a bit from the currently used one though, choosing not to highlight punctuation or operators. It also lacks support for older syntax plugins (this syntax is deprecated now though). I've made some comparisons using Lightshow:
- SourceMod 1.10 syntax plugin - austinwagner grammar (currently used grammar)
![](https://i.imgur.com/kOaeKP8.png)
- SourceMod 1.10 syntax plugin - Dreae grammar (proposed grammar)
![](https://i.imgur.com/79lSetU.png)
- SourceMod 1.6 syntax plugin - austinwagner grammar (currently used grammar)
![](https://i.imgur.com/03r0fn9.png)
- SourceMod 1.6 syntax plugin - Dreae grammar (proposed grammar)
![](https://i.imgur.com/D9B45UY.png)

**Comment by X6B0ISI09wD4** [comment]
After looking through #3070 and #3208, I've seen that the grammar was only forked to the @github-linguist organisation because the author removed the grammar from the original repository.

There is another problem though, as with https://github.com/goodmind/language-typelanguage/pull/2, the new grammar contains an invalid key (`$schema`). I've opened a PR (https://github.com/Dreae/sourcepawn-vscode/pull/15) and hopefully it gets merged at some point in the near future.

**Comment by pchaigno** [comment]
The grammar you proposed does look better to me. Don't hesitate to open a pull request to switch once the issue is fixed.

**Comment by X6B0ISI09wD4** [comment]
@lildude @pchaigno @Alhadis any chance you can offer input on a possible heuristic for SourcePawn, specifically for its include files. Since they use a super common extension, I figure it might be good to include one.

There are 3 unique and common conventions that come to mind (`x` is a series of letters, numbers and underscores).
1. Double include prevention (same for old and new syntax).
    ```sourcepawn
    #if defined _x_included_?
        #endinput
    #endif
    #define _x_included_?
    ```
1. `SharedPlugin` struct.
    - <1.7 syntax.
        ```sourcepawn
        public SharedPlugin:__pl_x
        ```
    - \>=1.7 syntax.
        ```sourcepawn
        public SharedPlugin __pl_x
        ```
3. Marking natives as optional.
    - <1.7 syntax.
        ```sourcepawn
        public __pl_x_SetNTVOptional()
        ```
   - \>=1.7 syntax.
        ```sourcepawn
        public void __pl_x_SetNTVOptional()
        ```

Unfortunately I'm horrible at writing regular expressions and have no idea how Linguist actually requires or a match. This is what I came up with, but it's super long and ugly. Thanks in advance.
```regex
^(?:public\s(?:void|SharedPlugin)?(?::|\s)?__pl_.+|#if\sdefined\s(_.+_included_?)\n\s*#endinput\n#endif\n#define\s\1)
```

**Comment by Alhadis** [comment]
> This is what I came up with, but it's super long and ugly.

It looks fine to me. Only recommendations I could make are adding quantifiers after each `\s` assertion (so mandatory whitespace becomes `\s+` and optional blanks become `\s*`). Also, if multiple newlines are permitted, then `\n` should become `\n+`.

Otherwise, your expression looks fine. Sometimes it's impossible to keep a regex elegant or concise (particularly if the format doesn't support multiline/expanded expressions, like Perl and Ruby do).

**Comment by X6B0ISI09wD4** [comment]
> It looks fine to me. Only recommendations I could make are adding quantifiers after each \s assertion (so mandatory whitespace becomes \s+ and optional blanks become \s*). Also, if multiple newlines are permitted, then \n should become \n+.
>
> Otherwise, your expression looks fine. Sometimes it's impossible to keep a regex elegant or concise (particularly if the format doesn't support multiline/expanded expressions, like Perl and Ruby do).

Thanks for the advice! Seems I'll have to drop the first one as it was adopted by the SA:MP community at some point, so there's a chance that could be in Pawn files. Is it worth adding the stuff after `[...]__pl_.+` or not in this case?
```regex
^public\s+(?:void|SharedPlugin)?(?:\s+|:)?__pl_.+(?:_SetNTVOptional)?$
```

**Comment by Alhadis** [comment]
> Is it worth adding the stuff after `[...]__pl_.+` or not in this case?

You know more about these languages than I do (my knowledge of both is *zilch*), but as long as these patterns are common and consistent, then go for it. 👍

**Comment by X6B0ISI09wD4** [comment]
> You know more about these languages than I do (my knowledge of both is zilch), but as long as these patterns are common and consistent, then go for it. +1

Well, since there's a `.+` in my regex, it seems it will match everything after that until the end of the line, possibly making everything after it redundant?

**Comment by Alhadis** [comment]
Ah, right. Change it to `\S+` (matching only non-whitespace), or `\w+` (matching only "word" characters, excluding any others that might be legal in the language's syntax for identifiers).

**Comment by pchaigno** [comment]
`.+` is also quite costly. If you can limit that to `\w+` to avoid unconstrained [backtracking](https://www.regular-expressions.info/catastrophic.html) it's much better!

**Comment by X6B0ISI09wD4** [comment]
> Ah, right. Change it to \S+ (matching only non-whitespace), or \w+ (matching only "word" characters, excluding any others that might be legal in the language's syntax for identifiers).
Changed it around a little and incorporated `\S+`, could you take a look. I'll leave all the possibilities it needs to match below too (each line is separate).
```regex
^public\s+(?:void|SharedPlugin)?(?:\s+|:)?__pl_\S+(?:\s*=)?(?:\s*{)?
```
```sourcepawn
public SharedPlugin:__pl_x=
public SharedPlugin:__pl_x =
public SharedPlugin:__pl_x={
public SharedPlugin:__pl_x= {
public SharedPlugin:__pl_x ={
public SharedPlugin:__pl_x = {
public SharedPlugin __pl_x=
public SharedPlugin __pl_x =
public SharedPlugin __pl_x={
public SharedPlugin __pl_x= {
public SharedPlugin __pl_x ={
public SharedPlugin __pl_x = {
public __pl_x_SetNTVOptional()
public void __pl_x_SetNTVOptional()
```

**Comment by pchaigno** [comment]
Isn't `[a-zA-Z0-9_]` equivalent to `\w`?

**Comment by Alhadis** [comment]
> Isn't `[a-zA-Z0-9_]` equivalent to `\w`?

Eh... according to POSIX, yes. But modern, Unicode-aware engines like (Perl and Oniguruma) treat `\w` as equivalent to `\p{Word}` (having the Unicode *"word"* property), unless a modifier like `/a` is enabled to restrict matching to ASCII expectations (`[a-zA-Z0-9_]`).

`perlrecharclass(1)` actually has a whole subsection dedicated to discussing "word" characters.

**Comment by X6B0ISI09wD4** [comment]
Is the engine GitHub uses still a mystery?

**Comment by Alhadis** [comment]
Going by [earlier discussion](https://github.com/github/linguist/issues/3291#issuecomment-460973497), it seems GitHub forces ASCII locale to significantly speed up processing. Contrary to what I originally believed, the engine responsible for processing grammars is actually PCRE-based, *not* Oniguruma (GitHub have a Ruby-fuelled pipeline, so it's only natural to assume it powered their highlighting too).

Unfortunately, the syntax highlighting software is closed (or mixed) source, meaning we can't openly see what's driving everything...

**Comment by X6B0ISI09wD4** [comment]
I guess I'll leave it as is then since we don't really know the state of the engine, and its future.

**Comment by pchaigno** [comment]
> Going by [earlier discussion](https://github.com/github/linguist/issues/3291#issuecomment-460973497), it seems GitHub forces ASCII locale to significantly speed up processing.

So unless it changed, `\w` should be the same as the above on GitHub, right? We're already using `\w` in a lot of places in the heuristic rules, so I think it would be better to use it here too, at least to improve readability.

**Comment by Alhadis** [comment]
Well, one can't simply swap out a language's regex engine and expect an ecosystem of dependencies to not break with incompatible syntax... so I'd say whatever GitHub are using for highlighting, it's a different runtime/environment/whatever to Ruby.

That being said, I don't know enough about Ruby's (apparently convoluted) locale-handling to guess whether Linguist is running with Unicode-awareness...

**Comment by X6B0ISI09wD4** [comment]
@Alhadis if we merge #4518 before #4517 can we test this out?
1. Create a repository with a misclassified `.inc` file (it's quite easy to get a SourcePawn include misclassified as C++ at the moment).
2. Commit the line(s) detected by the heuristic with and without Unicode word characters and see if the detection changes.

Would that work or am I missing something?

**Comment by Alhadis** [comment]
> Create a repository with a misclassified `.inc` file

You won't need to do that. Linguist includes [an executable](https://github.com/github/linguist/blob/master/bin/github-linguist) that can analyse a specific file:

~~~console
$ bin/github-linguist ~/tmp/script.py
info: 2 lines (1 sloc)
  type:      Text
  mime type: text/plain
  language:  Python
~~~

See [command-line usage](https://github.com/github/linguist#command-line-usage) for more info, or consult an [unofficial `man` page](https://github.com/github/linguist/blob/e79e407fb41bb9e427e9ec3e1b67e015887859eb/test/fixtures/Data/Manpages/linguist.1gh) I wrote because I needed another Roff fixture to test #4433. 😜

**Comment by Alhadis** [comment]
@lildude Ruby question: what's the difference between `bundle exec bin/github-linguist` and running the executable from command-line directly?

I noticed the former doesn't always pick up my local changes (such as when I'm testing a heuristic), and the latter requires me to `gem install …` Linguist's dependencies globally (with the tradeoff that it manages to pick up every change I make to a file...)

**Comment by lildude** [comment]
`bundle exec` runs the ruby script in the context of the gems specified in the Gemfile ie it uses the gems and versions specified in the Gemfile rather than the system or user installed versions, which may have incompatible differences between versions.

Both should pick up your local changes though. Both also require you to install the gems specified in the Gemfile, with `script/bootstrap` doing the magic for you when follow the contrib docs.

**Comment by Alhadis** [comment]
> Both should pick up your local changes though. Both also require you to install the gems specified in the Gemfile

Oh, I figured that. I was wondering if the presence of a `.bundle/` directory (along with `tmp/` which contained untracked copies of tracked source code) may have been interfering with the `bundle exec` step. 😅

Thanks! That clears up a lot of confusion now... `bundle exec` must be Ruby's equivalent of `npm install .` (concerning local VS globally-installed dependencies).

**Comment by X6B0ISI09wD4** [comment]
> > Create a repository with a misclassified `.inc` file
> 
> You won't need to do that. Linguist includes [an executable](https://github.com/github/linguist/blob/master/bin/github-linguist) that can analyse a specific file:

Hmm, I gave it a go but if I include non-ASCII characters to test it, I get:
```
bundler: failed to load command: bin/github-linguist (bin/github-linguist)
ArgumentError: invalid byte sequence in US-ASCII
    /home/user/linguist/lib/linguist/blob_helper.rb:279:in `split'
    /home/user/linguist/lib/linguist/blob_helper.rb:279:in `lines'
    /home/user/linguist/lib/linguist/blob_helper.rb:341:in `loc'
bin/github-linguist:59:in `<top (required)>'
```

**Comment by lildude** [comment]
@X6B0ISI09wD4 you need to be using a UTF-8 compatible locale, eg `en_US.UTF-8`. Either set it in your env or set it when executing `bundle exec`: `LANG=en_US.UTF-8 bundle exec bin/github-linguist ...`

**Comment by X6B0ISI09wD4** [comment]
> @X6B0ISI09wD4 you need to be using a UTF-8 compatible locale, eg `en_US.UTF-8`. Either set it in your env or set it when executing `bundle exec`: `LANG=en_US.UTF-8 bundle exec bin/github-linguist ...`

Thanks! Seems `\w` is limited to `[a-zA-Z0-9_]` then, as a `á` in the token won't trigger the heuristic.

**Comment by Alhadis** [comment]
> as a `á` in the token

**Tip:** When verifying how UTF-8 input is handled, try to avoid using characters from the Extended Latin block (U+0080 — U+00FF, a.k.a, "Latin-1"). Use an alphabet like Thai or Greek guaranteed to be a multibyte character.

The reason is that if you're dealing with a program with faulty or unpredictable locale-handling, there's a risk that any byte above `0x7F` is treated as a single-byte encoding, rather than UTF-8. So you might end up with false positives/negatives, depending on how bad the program's encoding support is.

**Comment by X6B0ISI09wD4** [comment]
> **Tip:** When verifying how UTF-8 input is handled, try to avoid using characters from the Extended Latin block (U+0080 — U+00FF, a.k.a, "Latin-1"). Use an alphabet like Thai or Greek guaranteed to be a multibyte character.

Thanks for the tip. So there's a chance some programs could interpret it as two separate ASCII characters and match the `\w+`? I assume since it didn't match even with `á` it's fine, but I tried again with `α` and the result was the same.

**Comment by Alhadis** [comment]
> So there's a chance some programs could interpret it as two separate ASCII characters and match the `\w+`?

Honestly, no. It's just a safeguard against a worst-case scenario, such as iif both input *and* output are being received incorrectly. For instance, `â` in UTF8 is `0xC3 0xA2`, but `0xE2` in Latin-1. UTF-8 is backwards compatible with ASCII by design, so a transparent encoding change from UTF-8 to Latin-1 would remain unnoticed to a reader.

Conversely, `ช` (UTF8: `0xE0 0xB8 0x8A`) becomes `à¸` when converted to Latin-1. So a corruption would be recognisable immediately.
