### ISSUE TITLE
There should be a way to configure linguist from github repo using config file

### ISSUE THREAD

**Issue by jcubic** [github/linguist#3159]
SVG is not marked as language (#1020) same happen to markdown (#3158) it would be nice if you could add language in some config file that will be read by linguist on init.

**Comment by Alhadis** [comment]
First, please read the [troubleshooting notes](https://github.com/github/linguist#troubleshooting) on adjusting your project's language classification.

Secondly, Markdown isn't going to be listed in language statistics. This is why:

There are [four distinct classifications](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3) of language on GitHub:

* **Prose:** Material intended to be consumed by a human reader, with little to no processing
* **Markup:** Material intended to be presented to a reader after being processed or parsed by a program
* **Programming:** Material with instructions designed to be interpreted or compiled by software
* **Data:** Virtually anything that doesn't fit into the above

Language statistics are only affected by markup and programming languages. Data and prose are ignored, and they'd unfairly bloat a repository's language statistics.

Markdown is classed as "prose", as it's designed to be read in its raw form as easily as its processed form. HTML is classed as "markup", because it's not designed to be read in its raw form.

**Comment by sunjay** [comment]
What about repositories where "prose" is most of the content? For example blogs hosted on GitHub pages are mostly markdown but this isn't shown in the language statistics.

**Comment by arfon** [comment]
@sunjay - please see this related discussion for some additional background: https://github.com/github/linguist/issues/3228
