### ISSUE TITLE
Recognizing as "GCC Machine Description" a repository without language

### ISSUE THREAD

**Issue by reebr** [github/linguist#3172]
Hello,

I created a file that has some commands interpreted by an application that I've done.
I've never seen this syntax anywhere and was surprised when the repository was marked as " GCC Machine Description".

[Here's the repository][1].

Is this normal?

[1]:https://github.com/reebr/f-id

**Comment by Alhadis** [comment]
What's [this file](https://raw.githubusercontent.com/reebr/f-id/master/NOTE2.md) supposed to be?

**Comment by reebr** [comment]
@Alhadis  the content is equals to [Note][1] file,
but I haven't commited yet because I need wait the update from my client on next week :smile:.

[1]:https://github.com/reebr/f-id/blob/master/Note

**Comment by Alhadis** [comment]
@larsbrinkhoff Did you factor in empty files when you submitted #3095?

**Comment by pchaigno** [comment]
@reebr It's recognized as a GCC Machine Description file because of the file extension and the absence of content. `.md` can be a file extension for Markdown and GCC Machine Description. We usually distinguish between the two with [a heuristic rule](https://github.com/github/linguist/blob/6763b73d9ca5d88be2e67e6dcccd45f64eb65b8f/lib/linguist/heuristics.rb#L242-L248), based on the file content. Since there is no content here yet, it fails to correctly identify the language.

If you want to use the `.md` extension for something else than GCC or Markdown, you can use [Linguist overrides](https://github.com/github/linguist#overrides).

**Comment by reebr** [comment]
@pchaigno This info about overrides is pretty nice, thank you.

**Comment by larsbrinkhoff** [comment]
No, I didn't consider empty files.  It's obviously hard to classify empty files, but in this case I imagine users may be adding empty markup files every now and then.  Probably almost never empty GCC machine descriptions.

**Comment by s-u** [comment]
Note that we see the same bug for valid Markdown files, e.g. the following Markdown content gets misclassified as "GCC machine description":

```
<div id="map" style="width:500px; height:600px"></div>
```

Is there a way to override linguist  in a gist? Unfortunately the gist API doesn't seem to allow us to set the language through the edit/create gist API.

**Comment by larsbrinkhoff** [comment]
I believe `</div>` should be rare in GCC files, so I can add that to the heuristic.

**Comment by gordonwoodhull** [comment]
More generally, we get hit by this when our Markdown files start with either `>` or Tab, no matter what other content is in there. 

`>` is the symbol for a blockquote in Markdown, so that's pretty common. Tab is maybe less common.

We're moving toward not using the detected language, but I thought I'd comment here in case it helps later searchers.
