### ISSUE TITLE
Linguist still not acknowledging .pl as Perl scripts also

### ISSUE THREAD

**Issue by wboswall** [github/linguist#3230]
Perl scripts is not being acknowledged as .pl but when the extension is changed it is then acknowledged as Perl.  I don't have any Prolog scripts.  What about creating a module that looks into the files to determine the language based on syntax and other certain characteristics that languages have that others don't.  
![image](https://cloud.githubusercontent.com/assets/5710449/18618058/af7ae814-7db4-11e6-964d-669946b12572.png)

**Comment by larsbrinkhoff** [comment]
Hello @wboswall,

The issue is that you have [two](https://github.com/wboswall/wboswall.github.io/blob/master/mywebsites/TheAttic.netTemplate/perl00.pl) [files](https://github.com/wboswall/wboswall.github.io/blob/master/mywebsites/galaxySoftwareInt'l/public_html/perl00.pl) which don't look like typical Perl files.  Linguist mistakenly thinks they are Prolog files.

A quick fix for you would be to [override](https://github.com/github/linguist#overrides) the language detection.

**Comment by wboswall** [comment]
@larsbrinkhoff Thanks for replying but I don't know nor use Prolog. I was reading a perl book when I created the .pl files and I checked and Perl's extension for the script files uses .pl.....Which is really confusing.  Don't know why they had an alternate file extension like the other programming languages such as php-it uses php, php5,php7 etc.  I tried renaming .pl to .perl but won't compile and rename every time committing from .pl to perl would just suck.  So right now it's just really annoying.  Other people are saying the same thing such as this person: https://github.com/github/linguist/issues/435.  Hopefully there will be a solution to this bug soon.

**Comment by pchaigno** [comment]
@wboswall In your case, these files are detected as Prolog because the smiley in [these](https://github.com/wboswall/wboswall.github.io/blob/master/mywebsites/TheAttic.netTemplate/perl00.pl#L31) [lines](https://github.com/wboswall/wboswall.github.io/blob/master/mywebsites/galaxySoftwareInt'l/public_html/perl00.pl#L31) matches [our heuristic](https://github.com/github/linguist/blob/00efd6a463d198ae5b3c0482fb66e9f7cb71e7cd/lib/linguist/heuristics.rb#L321). It's kind of a corner case, so I don't think we should make the regular expression more complicated to fix it (the heuristic will never be perfect anyway).
I would recommend you use the Linguist overrides in this case, as @larsbrinkhoff suggested.

**Comment by wboswall** [comment]
It didn't work. So just hunted up other perl extensions and changed the ones in question with the new extension.  Thank you for all of your help @larsbrinkhoff and @pchaigno Much appreciated!!!!!!!:-D
![image](https://cloud.githubusercontent.com/assets/5710449/18749999/aa25444c-80af-11e6-9f48-8f9a2a57891f.png)

**Comment by wboswall** [comment]
It didn't work. So just hunted up other perl extensions and changed the ones in question with the new extension. Thank you for all of your help @larsbrinkhoff and @pchaigno Much appreciated!!!!!!!:-D
![image](https://cloud.githubusercontent.com/assets/5710449/18750066/f86a0868-80af-11e6-945c-538cd2ad1fba.png)
