### ISSUE TITLE
Incorrectly classifying files as OpenEdge ABL

### ISSUE THREAD

**Issue by flipdazed** [github/linguist#3270]
The visual languages bar chart in the home page of [this repository](https://github.com/flipdazed/Hybrid-Monte-Carlo) shows:

 - OpenEdge ABL 72.4%	 
 - Mathematica 17.6%	 
 - Python 8.5%	 
 - C 0.9%	 
 - C++ 0.3%	 
 - Matlab 0.3%

Clicking on the bar-chart and then on `OpenEdge ABL` sends the user to [this page](https://github.com/flipdazed/Hybrid-Monte-Carlo/search?l=openedge-abl) with

> We couldn’t find any code matching ''

 but displays what looks like a more correct list of languages as

**Languages**

 - 139 Python
 - 20 Markdown
 - 15 Mathematica
 - 12 C
 - 6 CSV
 - 4 Matlab
 - 3 C++
 - 1 Makefile
 - 1 Text

**Comment by pchaigno** [comment]
The mismatch between the language bar and the search results looks like a caching issue (we've had a lot lately). It should update on the next push to the repository. If it does not, you can contact support so they trigger an update manually.

As for the `72.37%  OpenEdge ABL`, this happens because [this file](https://github.com/flipdazed/Hybrid-Monte-Carlo/blob/master/results/data/other_objs/christian_xx.p) is detected as OpenEdge ABL. You can mark your data files as vendored using [Linguist overrides](https://github.com/github/linguist#overrides) to fix this.

**Comment by Ho-Holic** [comment]
I have similar behaviour in this [repo](https://github.com/Ho-Holic/meta). It treats TeX class files as OpenEdge ABL.

**Comment by Alhadis** [comment]
We probably need more samples for OpenEdge ABL. The [ones we have now](https://github.com/github/linguist/tree/master/samples/OpenEdge%20ABL) are pretty modest.

**Comment by pchaigno** [comment]
> I have similar behaviour in this repo. It treats TeX class files as OpenEdge ABL.

Actually, the 47.08% TeX are due to [this file](https://github.com/Ho-Holic/meta/blob/717b54908e82bbeced5a5d1f4a2222a88f28ef9f/cv-rus/cv.tex).

**Comment by Ho-Holic** [comment]
But we are about wrong prediction of Open Edge ABL, aren't we?
[This file](https://github.com/Ho-Holic/meta/blob/717b54908e82bbeced5a5d1f4a2222a88f28ef9f/cv-rus/curricula-vitae.cls) is valid TeX class file, but it has OpenEdge ABL 43.2%

**Comment by pchaigno** [comment]
@Ho-Holic Oops, you're right. Sorry about that! Could you open a new issue?

We could probably add some heuristic rule to distinguish TeX from other languages with the `.cls` extension.

**Comment by Ho-Holic** [comment]
Done  #3299
