### ISSUE TITLE
Incorrect detection of javascript as auto-generated

### ISSUE THREAD

**Issue by devnoname120** [github/linguist#3288]
This diff is suppressed, but it shouldn't: https://github.com/HandyUserscripts/AntiAdware/commit/d835ac35824fd467a38d74806997e33bf485a1e5

I contacted Github, and they explained to me that this was due to this file in Linguist, and that I had to open an issue on the repository: https://github.com/github/linguist/blob/905d87a112cddf67026e41f437442bafc45b02b4/lib/linguist/generated.rb

**Comment by pchaigno** [comment]
[Linguist thinks the file is minified](https://github.com/github/linguist/blob/905d87a112cddf67026e41f437442bafc45b02b4/lib/linguist/generated.rb#L91-L106) (thus, generated) because of [this line](https://github.com/HandyUserscripts/AntiAdware/blob/d835ac35824fd467a38d74806997e33bf485a1e5/AntiAdware.user.js#L554). I'm afraid we don't currently have a way to override this :/

**Comment by vvo** [comment]
I have a similar question, this diff is supressed also for a one line change:

![2016-10-27-121532_1534x199_scrot](https://cloud.githubusercontent.com/assets/123822/19763623/266a6d98-9c3f-11e6-97e6-9cb4f8acd594.png)

![2016-10-27-121537_1532x389_scrot](https://cloud.githubusercontent.com/assets/123822/19763622/2666a19a-9c3f-11e6-9817-a2b75e9d5eba.png)

Link: https://github.com/algolia/instantsearch.js/pull/1475/files#diff-973b6bf37d8da83d3bf4d3d30e91b748L12

**Comment by devnoname120** [comment]
@pchaigno This is not yet fixed. Example: https://github.com/HandyUserscripts/AntiAdware/commit/dcfbf868cfeb0fab28dc7c73a04b3c0df081a62f.
