### ISSUE TITLE
misclassification of languages

### ISSUE THREAD

**Issue by jevanpipitone** [github/linguist#3318]
1. https://github.com/jevanpipitone/musicMaker
Says Tex, should be C#

2. https://github.com/jevanpipitone/ListURLs
Says Tex, should be C#

3. https://github.com/jevanpipitone/chatPC
Says Tex, should be C#

4. https://github.com/jevanpipitone/BitmapPatterns
Says Tex, should be Visual Basic

5. https://github.com/jevanpipitone/TaskSuggestions
Says JavaScript, should be Ruby on Rails

**Comment by pchaigno** [comment]
The language for a repository is the first language in the statistics. Statistics are computed from file sizes for each language. You can tell Linguist to ignore files in statistics using [Linguist overrides](https://github.com/github/linguist#overrides).

For the last repository: JavaScript comes as the first language because of the large [jQuery file](https://github.com/jevanpipitone/TaskSuggestions/blob/50d6301b0d88143881988fdccdfc9fd22ad4a081/src/public/assets/application-23fc44afbee60fd2d27aeea15a5471c8e4d489170caa284fa22cbaa0bd3172b6.js). Linguist usually detects jQuery files from the filename but since this one seem to have a random filename, it fails :/
