### ISSUE TITLE
misclassified languages

### ISSUE THREAD

**Issue by sathyalog** [github/linguist#3327]
Hi,

My project is developed on javascript/angularjs. But it shows CSS in my repositories tab. Please have a look at https://github.com/sathyalog/ng-firebase-chat.

I even added .gitattributes to my repo but it didn't help much. Please do the needful. Thanks

**Comment by Alhadis** [comment]
Hi @sathyalog,

Your [`.gitattributes`](https://github.com/sathyalog/ng-firebase-chat/blob/master/.gitattributes) file isn't doing anything for two reasons:

1. You've specified `*.rb` in the file, but there are no Ruby files in your project.
2. `linguist-language=Angularjs` won't work because `Angularjs` isn't a language. The correct name is `JavaScript`.

However, this isn't the attribute you want to fix your repository's classification. Instead, you'll want to use `linguist-vendored`, which says *"I didn't write these files, they're written by somebody else"*:

```
build/css/* linguist-vendored
```

This will exclude any CSS file in your project's [`build/css/`](https://github.com/sathyalog/ng-firebase-chat/tree/master/build/css) directory from language statistics.

**Comment by sathyalog** [comment]
Wow. Thanks @Alhadis  :). It worked.

**Comment by Alhadis** [comment]
Glad to hear it! You're welcome. =)
