### ISSUE TITLE
Javascript/python/html/css labeled as OpenEdge ABL

### ISSUE THREAD

**Issue by holmrenser** [github/linguist#3344]
Almost all files in this repository are incorrecly labeled.

https://github.com/holmrenser/bioportal

For now I will add an override.

**Comment by Alhadis** [comment]
Looks like [this 6.75 MB file](https://github.com/holmrenser/bioportal/blob/master/data/interpro.hierarchy.p) was the culprit. Since it's the biggest single file in the repo, its `.p` extension was unfairly skewing the stats.

This file's clearly Python-related, but I'm not familiar with its use. Judging from the abundance of [similar files](https://github.com/search?p=1&q=extension%3Ap+NOT+nothac22k&ref=searchresults&type=Code&utf8=%E2%9C%93) in the wild, though, I'd say this is worth looking at.

/cc resident Python guy @pchaigno

**Comment by holmrenser** [comment]
Great catch. This is a python pickled file, of which I am not sure there is a formal extension.
I'll add the suggested line in ```.gitattributes```

**Comment by Alhadis** [comment]
Ah! We have [Pickle](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3183-L3189) registered under the extension `.pkl`. I'm guessing we could add `.p` as an extension, and secure it using a [heuristic](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb). Since every pickle file seems to be composed of very short lines, I don't imagine it being very hard.

Do you know if pickle-files have a definitive maximum character count per line?

**Comment by holmrenser** [comment]
I am not aware of any limitations on line length in the pickle format specification. 

Removing the pickled file fixed the problem, I will stick to using ```.pkl``` in the future.
