### ISSUE TITLE
Classifying my gdscript project as PHP

### ISSUE THREAD

**Issue by lukeoftheaura** [github/linguist#3345]
Linguist seems to be detecting my godot engine/gdscript project as being PHP. If I check the language breakdown it seems the fact it's detecting it as PHP is one .inc file godot is using for a font, even though there's a majority of files in the repo being gdscript.
I see why, as the inc file is so big, but I don't see why github reports that as being PHP.

**Comment by Alhadis** [comment]
It'll be because `.inc` is listed [as a PHP extension](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml). The fact your [repository's `.inc` file](https://github.com/lukeoftheaura/game/blob/5ac102b8f144900038dbeb0242020a961534d39f/Fonts/opensans.inc) is so big is accounting for the majority of the codebase's language statistics (which get calculated proportionally).

You can exclude it from analysis by using your `.gitattributes` file to mark it as vendored (which is Linguist's way of saying _"Okay, you didn't write this file? No problem, I'll ignore it"_):

```
Fonts/opensans.inc linguist-vendored
```

Alternatively, you can set the language using a similar method:

```
Fonts/opensans.inc linguist-language=GDScript
```

This won't affect syntax highlighting though (unless you use a [modeline](https://github.com/github/linguist#using-emacs-or-vim-modelines)). It's kind of a current technical limitation...
