### ISSUE TITLE
Github thinks this file is Makefile instead of D

### ISSUE THREAD

**Issue by nholland94** [github/linguist#3462]
https://github.com/nholland94/bynar/blob/bca4c9e1e3e85f932b205393a9805199082cbe95/source/common.d

I think it is confused by the ternary on line 34

**Comment by seppestas** [comment]
The .d file extension is also commonly used for [dependency files generated by GCC](https://gcc.gnu.org/onlinedocs/gcc-4.2.2/gcc/Preprocessor-Options.html#dashMF). These files are small makefiles listing dependencies of a source file that get included into the main makefile, causing make to know to rebuild a source file when one of the included header files was changed.

That being said, since those files are output from the preprocessor, they shouldn't really be checked into git IMO...

**Comment by pchaigno** [comment]
@nholland94 - #3145 has been merged since you opened this issue and the incorrect classification of your file seems fixed. Is this still an issue for you?

**Comment by nholland94** [comment]
The classification is better, but it is still classifying this file as a Makefile: https://github.com/nholland94/bynar/blob/70c03830c0e3c469722eb735ad1084710b38a234/source/input_rel_exp.d

**Comment by pchaigno** [comment]
I think the language statistics are just out-of-date for this file. It's correctly recognized as a D file (which the highlighting confirms):
```
$ linguist --breakdown
98.67%  D
1.13%   Shell
0.20%   APL

Shell:
.travis-ci.sh

APL:
scripts/lib.apl

D:
source/app.d
source/bench.d
source/collections.d
source/common.d
source/descriptor_set_pool.d
source/descriptor_set_writer.d
source/device.d
source/execution_pipeline.d
source/execution_strategies.d
source/input_rel_exp.d
source/memory.d
source/test.d
source/test_utils.d
```
The statistics should update next time you push to the repository (or you can contact GitHub support so they manually update it).

**Comment by lildude** [comment]
I've nudged the analysis of this repo and it is now showing no instances of Makefile. I think we can consider this resolved so I'm closing this issue.
