### ISSUE TITLE
Delays

### ISSUE THREAD

**Issue by Wetitpig** [github/linguist#3506]
Why does it take more than an hour or two to display the language bar in github? Thanks.

**Comment by lildude** [comment]
@Wetitpig the analysis of code in order to determine the language and statistics is performed by a low priority background job. It can sometimes take a bit longer than usual for this job to run, however it shouldn't take as long as an hour.

That said, last week work was taking place in order to add support for syntax highlight overriding using the `.gitattributes` file (previously unsupported) and this involved refreshing the caches for all repositories.  Your experience may have been during this time.

Please try again and if you're still seeing issues, please contact [GitHub support](https://github.com/support) and they'll be able to look into your specific repositories to see what could be causing the delays.
