### ISSUE TITLE
OpenEdge *.w files wrong classification

### ISSUE THREAD

**Issue by MaickelHubner** [github/linguist#3513]
The OpenEdge *.w files are being classified like C/C++ in GitHub.
Could anyone solve this?

Thanks

**Comment by pchaigno** [comment]
Is OpenEdge with `.w` the same as [OpenEdge ABL](https://github.com/github/linguist/blob/1b429ea46bbf0caecac2e1f55bd730a0f037b1eb/lib/linguist/languages.yml#L2905-L2916)? If so, please see the [guidelines to add support for a new extension to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language). Otherwise, you can [add OpenEdge as a new language in Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). In both case, we'll welcome a pull request if OpenEdge `.w` files meet the requirements on in-the-wild usage.
