### ISSUE TITLE
linguist command line tool only works on Git repositories

### ISSUE THREAD

**Issue by armijnhemel** [github/linguist#3563]
The linguist commandline tool (note: *not* the git-linguist tool) does not work if the .git directory is missing, despite it being a tool for any file or directory according to the documentation,

$ ./bin/linguist 
./bin/linguist:27:in `new': Could not find repository from '/home/armijn/git/linguist' (Rugged::RepositoryError)
	from ./bin/linguist:27:in `<main>'

The docs say:

 Detect language type for a file, or, given a directory, determine language breakdown.

**Comment by pombredanne** [comment]
Fixing the doc is ok yet feels like a weak workaround...
I cannot understand why would language detection need to have a git repo: I reckon that's your primary use case, but does this means that there is no way to run this on a dir at all? (either with a CLI or a library call?)

**Comment by Alhadis** [comment]
@pombredanne Not on entire directories, no. However, it's still possible to use Linguist for analysing individual files. While far from optimal, it's still possible to recurse through a directory and individually analyse each file.

I'm inclined to agree, however, that analysing the contents of any arbitrary directory would be most useful.

**Comment by pchaigno** [comment]
@pombredanne We'd welcome a pull request to enable running against plain directories.

**Comment by PuZZleDucK** [comment]
Turns out linguist deals with blobs and never touches files as such.

We could wrap it in a function that checks for a repo, and inits a new one if needed (and deletes after). It's far from ideal (unusual termination leads to stray git repos).

I've hacked together a simple script that demonstrates the concept and allows linguist to run on non repos, but it's taking longer than I expected to convince the Rugged library to do the same:
https://gist.github.com/PuZZleDucK/a45fd1fac3758235ffed9fe0e8aab643
