### ISSUE TITLE
No .sql language detection

### ISSUE THREAD

**Issue by mlanier** [github/linguist#3573]
I am not seeing .sql being detected.

**Comment by lildude** [comment]
This is expected as SQL is considered a data language by Linguist. We've discussed (and tried to change) this behaviour [several times in the past](https://github.com/github/linguist/search?utf8=%E2%9C%93&q=sql+data+programming&type=Issues) but all have been reverted due to wildly inaccurate representations.

**Comment by yangsoosong** [comment]
You can now [override](https://github.com/github/linguist/blob/master/README.md#detectable) language definitions and file paths. You just need to make sql detectable for linguist library.
Adding *.sql linguist-detectable=true in .gitattributes solved this issue for me!
