### ISSUE TITLE
Some of my repo doesn't showing Language bar after push

### ISSUE THREAD

**Issue by dwicao** [github/linguist#3595]
Hi, my previous repo is contained with Example of React Native folder which is heavily written on Objective-C, at this time, it shown Language bar, but since I deleted the Example folder and pushes some code written in Javascript, the Language Bar is missing.
Here is the repo:
https://github.com/dwicao/react-native-circle-button
https://github.com/dwicao/react-native-double-click
https://github.com/dwicao/react-native-simple-tab

I actually wait for 24 hours++ since the last time I pushed the code, but nothing happened 😢

**Comment by lildude** [comment]
@dwicao this is happening because all your code is under the `dist` directory in each repo.  This is [considered a vendored](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L18-L19) directory by Linguist.  You'll need to [manually override](https://github.com/github/linguist#overrides) this or use a different directory name that isn't considered a vendored directory.

**Comment by dwicao** [comment]
Thank you very much, now it is solved 🎉
