### ISSUE TITLE
Nim tmLanguage Highlighting Incompatibility

### ISSUE THREAD

**Issue by Varriount** [github/linguist#3631]
Hello. I'm the current maintainer for the [NimLime](https://github.com/Varriount/NimLime) repository, which appears to be used by Github for syntax highlighting (I didn't know about this until someone filed an [issue](https://github.com/Varriount/NimLime/issues/82) in the repository)

Anyway, [this](https://github.com/Varriount/NimLime/issues/82) issue currently reports that the following code is incorrectly highlighted:
```nim
let hex = 0xDEADBEEF'u32
let bin = 0B0_10001110100_0000101001000111101011101111111011000101001101001001'f64
```

However Sublime Text highlights the snippet correctly:
![image](https://cloud.githubusercontent.com/assets/524596/26173704/d458a4cc-3b1a-11e7-802b-555b46dcf0e9.png)

Is this due to incompatibilities between Sublime Text and Linguist's highlighting implementations, or the fact that Linguist is using an old version of the syntax file? The tmLanguage files were once located in the root directory of the repository, but have since been moved to the [Syntaxes](https://github.com/Varriount/NimLime/tree/master/Syntaxes) directory.

**Comment by lildude** [comment]
I think the issue here is the wrong Nim grammar source is being used/detected.

If we dabble with Lightshow (I updated it this morning to match GitHub.com), we can see that [selecting Nim and pasting that text](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.nim&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=let+hex+%3D+0xDEADBEEF%27u32%0D%0Alet+bin+%3D+0B0_10001110100_0000101001000111101011101111111011000101001101001001%27f64) produces the behaviour reported here.  The grammar in question is [this one](https://github.com/Varriount/NimLime/blob/master/Syntaxes/Nim.YAML-tmLanguage).

If we however [point to the Nim CFG grammar in your repo](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FVarriount%2FNimLime%2Fblob%2Fmaster%2FSyntaxes%2FNim_Cfg.YAML-tmLanguage&grammar_text=&code_source=from-text&code_url=&code=let+hex+%3D+0xDEADBEEF%27u32%0D%0Alet+bin+%3D+0B0_10001110100_0000101001000111101011101111111011000101001101001001%27f64) @Varriount, we get much better highlighting:

![screen shot 2017-05-20 at 13 46 40](https://cloud.githubusercontent.com/assets/627280/26275876/c66b334e-3d62-11e7-8845-dd8b8188130a.png)

I have no idea if this syntax is `nimcfg` or not, but if it is then, whilst all the grammars have been added to Linguist (https://github.com/github/linguist/blob/master/grammars.yml#L65-L68), only the first has been associated with any language... there is only a reference in `languages.yml` to the `source.nim` grammar at https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2773-L2781 and no references to `source.nimcfg` or `source.nim_filter`.

**Comment by Varriount** [comment]
The nimcfg grammer is for something else - it just happens to work somewhat on this particular input.

**Comment by lildude** [comment]
Thanks for the clarification.  I've done a quick experiment using the [Atom syntax](https://github.com/zah/nim.atom) (I manually had to change the cson to json as Lightshow wasn't playing nice with the cson file) and, whilst probably not perfect, it seems to be working better as you can see [here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Flildude%2F1246482e19954c85cfae262f1310ab32%2Fraw%2F945f55f5f31484aea8450e17ac10cad0aa5a3a63%2Fnim.json&grammar_text=&code_source=from-text&code_url=&code=let+hex+%3D+0xDEADBEEF%27u32%0D%0Alet+bin+%3D+0B0_10001110100_0000101001000111101011101111111011000101001101001001%27f64):

![screen shot 2017-05-26 at 09 28 43](https://cloud.githubusercontent.com/assets/627280/26487065/c05b5d34-41f5-11e7-9aa7-a11c12763a57.png)

This leads me to believe there is probably something Sublime-specific in your grammar that isn't working with the parser we use.

**Comment by Varriount** [comment]
Thanks for help! I'll try testing out the various regular expressions in a PCRE-based tester, and see what happens.

**Comment by Alhadis** [comment]
> This leads me to believe there is probably something Sublime-specific in your grammar that isn't working with the parser we use.

It's because of the `\h` sequence. It means two entirely different things, depending on engine:

- **PCRE:** Horizontal whitespace (e.g., spaces and tabs)
- **Oniguruma:** Hexadecimal characters (e.g., a shorter way to write `[0-9A-Fa-f]`

This isn't the first time this discrepancy has bitten us, either (I knew without checking the source the `\h` was to blame).

@Varriount You can fix this by replacing `\h` with `[0-9A-Fa-f]` instead. :)
