### ISSUE TITLE
CShart Visual Project repo misclassified as SciLab repo

### ISSUE THREAD

**Issue by nrough** [github/linguist#3654]
https://github.com/nrough/framework

**Comment by wwdenis** [comment]
Similar issue here: It says is Smalltalk but it's C#/TypeScript.

https://github.com/wwdenis/wwa
https://github.com/wwdenis/wwa/search?l=smalltalk

**Comment by lildude** [comment]
@nrough: your misclassification is due to all the files with `.tst` extensions.  This is being associated with [GAP](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1330-L1337) and [SciLab](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L4054-L4061) with the classifier then whittling this down to SciLab.

Due to the current approach where the extension is quite heavily weighted, you'll need to implement a [manual over-ride](https://github.com/github/linguist/blob/master/README.md#overrides) to correct the identification.

@wwdenis your issue is slightly different in that `.cs` is associated with C#, but it's also associated with SmallTalk and the [heuristics](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L119-L124) has determined those file to be SmallTalk instead of C#.  This one can be improved by supplying a PR that improves this disambiguation and a manual over-ride until the PR is merged.
