### ISSUE TITLE
My Swift repository is shown as Shell repository

### ISSUE THREAD

**Issue by javalnanda** [github/linguist#3656]
This [repo](https://github.com/javalnanda/NumericAnimatedLabel) contains Xcode project in Swift 3 language but on my pinned repository list it is showing as Shell language.

**Comment by lildude** [comment]
This is happening because of [these shell scripts](https://github.com/javalnanda/NumericAnimatedLabel/search?l=shell) are counting more than your Swift code due to their accumulative size.

To make Swift the primary language, you'll need to implement a [manual override](https://github.com/github/linguist#overrides) to ignore them (maybe mark them as vendored?)... or write more Swift 😜

**Comment by javalnanda** [comment]
😜 will need to manual override it then. Since it is a small library, can't add more swift code :P
