### ISSUE TITLE
XPM files misidentified as Perl6

### ISSUE THREAD

**Issue by DarkAyron** [github/linguist#3661]
I created a project containing several icons in xpm format. All these files are identified as Perl6. If Github doesn't know about XPM, a better wrong guess would be C, but not Perl. Although XPM files are C code, they allways start with /* XPM */.

Here is one of the misidentified files: [key_start.m.pm](https://github.com/DarkAyron/Morsetutor/blob/4dd2033465d0266eafbe39c8d03739d91d7e1a9c/key_start.m.pm)

**Comment by pchaigno** [comment]
We'd welcome a pull request [to add support for XPM to Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). There's a requirement on in-the-wild usage, but that [seems okay](https://github.com/search?p=96&q=extension%3Apm+xpm&type=Code&utf8=%E2%9C%93). The best would probably be to add a [heuristic rule](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb) to distinguish it from Perl, since there's a sure way to identify those files.

**Comment by smola** [comment]
PR: https://github.com/github/linguist/pull/3706

**Comment by lildude** [comment]
Support for XPM has been added. Closing.
