### ISSUE TITLE
Detects most repository as Ruby files while no such files exist

### ISSUE THREAD

**Issue by roeeaharoni** [github/linguist#3668]
[This repository](https://github.com/roeeaharoni/string-to-tree-nmt) has no Ruby files but most files in it are detected as such:
![screen shot 2017-06-06 at 21 21 56](https://user-images.githubusercontent.com/6319492/26845117-347d849c-4afe-11e7-9bdf-48eb6195bdd0.png)

**Comment by Alhadis** [comment]
... yep, yet when we try listing which Ruby files it has indexed, [we get absolutely nothing](https://github.com/roeeaharoni/string-to-tree-nmt/search?l=ruby). 😞 Sometimes this happens; it's usually when a codebase hasn't been modified in a while, and the usage stats get "stuck" or something. Still not sure what causes it, actually.

@lildude Could you run a reset on this gent's repository?

Intriguing subject matter, might I add. ;-)

**Comment by roeeaharoni** [comment]
Thanks! Linguistic indeed ;)

**Comment by Alhadis** [comment]
Alright, now running the `linguist` executable on a locally-checked out copy of your project *does* reveal a substantial number of Ruby files:

~~~
string-to-tree-nmt/data/news-ru-en/dev/newstest2015-ruen.ru
string-to-tree-nmt/data/news-ru-en/test/newstest2016-ruen.ru
string-to-tree-nmt/data/news-ru-en/train/news-commentary-v8.ru-en.ru
string-to-tree-nmt/data/news-ru-en/train/news-commentary-v8.ru-en.tok.penntrg.clean.ru
string-to-tree-nmt/data/news-ru-en/train/news-commentary-v8.ru-en.tok.penntrg.clean.true.bpe.ru
string-to-tree-nmt/data/news-ru-en/train/news-commentary-v8.ru-en.tok.penntrg.clean.true.ru
string-to-tree-nmt/data/news-ru-en/train/news-commentary-v8.ru-en.tok.penntrg.ru
string-to-tree-nmt/data/news_commentary_v8/news-commentary-v8.ru-en.ru
~~~

... or perhaps I should say "Рубин files", because one immediate glimpse reveals files written in Russian. 😀 Which, quite obviously, explains how `ru` was misconstrued by GitHub as being Ruby, and not short for "Russian".


You can resolves this by adding a `.gitattributes` file to your project's root, and add the following lines:

~~~
*.ru linguist-language=Text
*.ru linguist-documentation
~~~

**Comment by roeeaharoni** [comment]
Haha, that makes sense :) will add this. Thanks again!

**Comment by Alhadis** [comment]
Glad I could help! =)

**Comment by pchaigno** [comment]
It looks like we (well, github.com) might have a [lot of text files under `.ru`](https://github.com/search?p=4&q=extension%3Aru+NOT+require+NOT+run&type=Code&utf8=%E2%9C%93). Worth adding it as an extension to Text?

**Comment by Alhadis** [comment]
Honestly, the same could be said for many ISO 639-1 codes which coincide with a common file-extension. "Perl VS Poland" being the most commonly seen.
