### ISSUE TITLE
Bibtex syntax highlighting

### ISSUE THREAD

**Issue by blegat** [github/linguist#3679]
If I am not mistaken, currently [`.bib`](https://github.com/github/linguist/blob/b6460f8ed6b249281ada099ca28bd8f1230b8892/lib/linguist/languages.yml#L4384) files are reported as [`latex`](https://github.com/github/linguist/blob/b6460f8ed6b249281ada099ca28bd8f1230b8892/lib/linguist/languages.yml#L4379) and are not highlighted.
I understand that reporting it as LaTeX allows to correctly highlight any LaTeX present in the fields as in the example below with `$math$`. However, it would be nice to have a separate language that also adds color highlighting to `@book`, ...
```latex
@book{knuth1998art,
  title={The art of computer programming: sorting and searching $math$},
  author={Knuth, Donald Ervin},
  volume={3},
  year={1998},
  publisher={Pearson Education}
}
```

**Comment by pchaigno** [comment]
We'd welcome a pull request to make Bibtex a separate language with its own syntax highlighting.

**Comment by ruffsl** [comment]
As of now, there are a few projects I see syntax highlighting for bibtex:

* https://github.com/SaswatPadhi/prismjs-bibtex
  * https://saswatpadhi.github.io/prismjs-bibtex/
* https://github.com/FlamingTempura/bibtex-tidy
  * https://flamingtempura.github.io/bibtex-tidy/
  * Not sure how its using CodeMirror.js

I don't know much javascript, but how would one move this upstream?

**Comment by pchaigno** [comment]
Unfortunately, we only support TextMate, Sublime Text, and Atom grammars.

**Comment by ruffsl** [comment]
From reading contributing.md and [linguist/vendor/README.md](https://github.com/github/linguist/blob/master/vendor/README.md), it looks like [textmate/latex.tmbundle](https://github.com/textmate/latex.tmbundle) is the current official TextMate support for LaTeX and BibTex. Looking at that repo, it also seems to have plenty of code/tests on BibTex syntax; commits dating back from 2015. Is there a particular reason syntax highlighting is not being rendered with linguist now?

https://github.com/textmate/latex.tmbundle/blob/404e0049b67d54c2733b5a16eb600740c4ec2e19/Syntaxes/Bibtex.plist#L5-L16

e.g.:

``` latex
@incollection{dijkstra1982role,
  title={On the role of scientific thought},
  author={Dijkstra, Edsger W},
  booktitle={Selected writings on computing: a personal perspective},
  pages={60--66},
  year={1982},
  publisher={Springer}}
```

<details>

```
`` ` latex
@incollection{dijkstra1982role,
  title={On the role of scientific thought},
  author={Dijkstra, Edsger W},
  booktitle={Selected writings on computing: a personal perspective},
  pages={60--66},
  year={1982},
  publisher={Springer}
}
`` `
```

**Comment by Alhadis** [comment]
> Is there a particular reason syntax highlighting is not being rendered with linguist now?

Yup, it's because we need a separate language entry for BibTeX. The file you linked to ([Bibtex.plist](https://github.com/textmate/latex.tmbundle/blob/404e0049b67d54c2733b5a16eb600740c4ec2e19/Syntaxes/Bibtex.plist#L5-L16)) isn't the one being used for `*.bib` files, because `*.bib` is [listed](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L5069) as a TeX extension, and TeX highlighting is handled using a [different grammar](https://github.com/textmate/latex.tmbundle/blob/404e0049b67d54c2733b5a16eb600740c4ec2e19/Syntaxes/TeX.plist).

If we use the `Bibtex.plist` file *specifically*, [the output is verrry different](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=xml&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Flatex.tmbundle%2F404e0049b67d54c2733b5a16eb600740c4ec2e19%2FSyntaxes%2FBibtex.plist&grammar_text=&code_source=from-text&code_url=&code=%40incollection%7Bdijkstra1982role%2C+title%3D%7BOn+the+role+of+scientific+thought%7D%2C%0D%0A++author%3D%7BDijkstra%2C+Edsger+W%7D%2C%0D%0A++booktitle%3D%7BSelected+writings+on+computing%3A+a+personal+perspective%7D%2C%0D%0A++pages%3D%7B60--66%7D%2C%0D%0A++year%3D%7B1982%7D%2C%0D%0A++publisher%3D%7BSpringer%7D%7D):

![figure-1](https://user-images.githubusercontent.com/2346707/61512077-2c546980-aa3c-11e9-8d50-150b358efa5c.png)

**Comment by Alhadis** [comment]
I've submitted a pull-request that will fix this. See #4584.
