### ISSUE TITLE
Reason code being misclassified as C++

### ISSUE THREAD

**Issue by jaredly** [github/linguist#3683]
Reason support was added here https://github.com/github/linguist/pull/3336

3 of my reason files are being classified as C++
![image](https://user-images.githubusercontent.com/112170/27256993-85fad05c-5384-11e7-89f3-9d9790dbdb37.png)

https://github.com/jaredly/ohai/search?l=c%2B%2B

Here's the contents of one of the files, which is definitely not valid C++

```re

/* Build an Opam file */

let build info => {
  open Info.T;
  let start = Printf.sprintf
  {|opam-version: "2.0"
name: %S
version: %S
maintainer: %S
authors: [%S]
homepage: %S
bug-reports: %S
dev-repo: %S
license: [%s]
tags: []
build: [["jbuilder" "build" "-p" name "-j" jobs]]
build-test: [["jbuilder" "runtest" "-p" name "-j" jobs]]
depends: [
  "jbuilder" {build}%s
]
|}
  info.name
  info.version
  info.maintainer
  info.maintainer
  (info.homepage |> CCOpt.get_or default::"")
  (info.bug_reports |> CCOpt.get_or default::"")
  (info.dev_repo |> CCOpt.get_or default::"")
  (switch (info.license) {
  | Some s => Printf.sprintf "%S" s
  | None => ""
  })
  (info.reason ? {|
  "reason" {>= "2.0.0"} {build}|} : "");
  start
};
```

**Comment by lildude** [comment]
This is happening because these files are falling right through to the classifier to try and determine the language, and it is assessing, based on the samples in `samples/Reason` and `samples/C++`, that the files are C++... but only just.

You can manually over-ride this, or help others by opening a new PR with a few more Reason samples, like these, so the classifier can get a better understanding.
