### ISSUE TITLE
Regression on Liquid syntax highlighting in Markdown fenced code block

### ISSUE THREAD

**Issue by nhoizey** [github/linguist#3690]
I used to use the `liquid` syntax highlighting in [the `README.md` for my Jekyll Cloudinary plugin](https://github.com/nhoizey/jekyll-cloudinary/blob/master/README.md):

    ```liquid
    {% cloudinary [preset] path/to/img.jpg [attr="value"] %}
    ```

But it doesn't work anymore, Github Pages refuses to generate the site because it tries to evaluate the `{% cloudinary %}` Liquid tag, which doesn't exist (because it comes from a plugin that is not available in Github Pages).

I had to [modify my code samples](https://github.com/nhoizey/jekyll-cloudinary/commit/ed644fb0310e7006d506bb9803220148e18fbee3) to use the `{% raw %}` Liquid tag and the `Markdown` syntax highlighter:

    {% raw %}
    ```markdown
    {% cloudinary cloudflare.png alt="Un schéma montrant l'apport de Cloudflare" caption="Un schéma montrant l'apport de Cloudflare" %}
    ```
    {% endraw %}

It's far less easy to write.

Looks like a regression, that could break a few other projects READMEs, IMHO.

**Comment by lildude** [comment]
@nhoizey Unfortunately, this isn't likely to be due to Linguist, but more likely the Markdown parser, which recently switched to be more inline with Commonmark, as detailed in [A formal spec for GitHub Flavored Markdown](https://githubengineering.com/a-formal-spec-for-github-markdown/).

Please [contact our support team](https://github.com/contact) with these details and they'll raise an issue for this.

**Comment by goproslowyo** [comment]
I am necroposting here six years later to also thank the OP for the `{% raw %}  {% endraw %}`. Much appreciated! That is all.
