### ISSUE TITLE
Can't exclude vendored JavaScript

### ISSUE THREAD

**Issue by cooper** [github/linguist#3703]
On https://github.com/cooper/lunch-menu-manager, I can't seem to get the vendored JavaScript to be excluded from the language stats. As you can see from my recent commit history, I have tried a variety of things including
```
*.min.js linguist-vendored
scripts/*.min.js linguist-vendored
```
I then tried moving the vendored file to `scripts/vendored` and doing
```
scripts/vendored/* linguist-vendored
```
but that isn't working either. I even tried excluding the file by its full path
```
scripts/mootools.min.js linguist-vendored # or
scripts/vendored/mootools.min.js linguist-vendored
```
to no avail

**Comment by Alhadis** [comment]
Without checking out your repository locally, I can see that the excludes actually *are* working... it's [these files](https://github.com/cooper/lunch-menu-manager/search?l=javascript) that are contributing to the JavaScript usage in the codebase.

**Comment by cooper** [comment]
For me the page you linked shows the vendored file at scripts/vendored/mootools.min.js which should be excluded

**Comment by lildude** [comment]
> For me the page you linked shows the vendored file at scripts/vendored/mootools.min.js which should be excluded

Looking at the stats, I can confirm the vendored file _is_ being excluded and is not counting towards the Javascript total - the other three JavaScript files are the only ones counting. Vendoring only excludes the files from the stats, it doesn't hide them from the language search.

**Comment by cooper** [comment]
@lildude how are you able to confirm that it is being excluded? I tried forcing to include it with `linguist-vendored=false` just to see if the stats would change, but they did not...

**Comment by lildude** [comment]
> @lildude how are you able to confirm that it is being excluded?

Two ways: 

1. I'm a GitHub employee so have access to the backend implementation of Linguist which show me the break down shown in the next point.
2. I clone your repo, and manually assessed it using Linguist:

``` 
$ ~/github/linguist/bin/linguist --breakdown
40.73%  JavaScript
40.25%  PHP
19.02%  CSS

PHP:
administrator.php
api/api-json.php
api/fetch-day.php
api/fetch-month.php
calendar.php
embed/week.php
functions/date-input.php
functions/generate-pdf.php
functions/index.php
functions/month-nav.php
functions/session.php
functions/update-cell-notes.php
functions/update-menu.php
functions/update-notes.php
functions/update-top.php
functions/utils.php
index.php
login.php
logout.php
templates/administrator-tools.php
templates/calendar.php
templates/footer-navigation.php

JavaScript:
scripts/administrator-tools.js
scripts/calendar.js
scripts/menu-editor.js

CSS:
styles/administrator-tools.css
styles/blue/administrator-tools.css
styles/blue/calendar.css
styles/calendar.css
styles/crimson/administrator-tools.css
styles/crimson/calendar.css
styles/crimson/weekly.css
styles/crimson/window.css
styles/window.css

$
```

As you can see, `scripts/vendored/mootools.min.js` is not in the list indicating it has not been included in the stats totals.

> I tried forcing to include it with linguist-vendored=false just to see if the stats would change, but they did not...

This is expected as Linguist has two ways of catching and ignoring this file:

1. It is already considered a vendored file [here](https://github.com/github/linguist/blob/648720301d12fb12c9339a134b1f496bddc9e9ce/lib/linguist/vendor.yml#L147-L148)
2. If you changed the name, it would be detected as a generated file [here](https://github.com/github/linguist/blob/648720301d12fb12c9339a134b1f496bddc9e9ce/lib/linguist/generated.rb#L63) because all minified files are considered generated.

So that all being told, your `mootools.min.js` file has never been counted as part of the stats.

You should find experimenting with one of your other three JavaScript files will adjust the totals.

**Comment by cooper** [comment]
I am surprised that the `linguist-vendored=false` override does not work in this case.

Thank you for taking the time to confirm that the file is being excluded. Next time I will know to check `linguist --breakdown`.
