### ISSUE TITLE
nginx 'conf.d' is being reported as D.

### ISSUE THREAD

**Issue by ollien** [github/linguist#3729]
I have [this file](https://github.com/ollien/ollien.com/blob/master/nginx/conf.d) in my repository, named `conf.d`, named as such because that is what nginx calls its config. However, it's classified as a D file rather than an nginx config. Not sure what the best method of resolving this, is, but I figured I should report it.

**Comment by Alhadis** [comment]
Well, the classifier isn't perfect. Mistakes like these are bound to happen. That's why we have an override mechanism that allows users to correct misclassifications like these. =) You can read about it in detail [here](https://github.com/github/linguist#overrides), but the **TL;DR** of it is that you add a `.gitattributes` file to your repository's root directory, and add the following line:

~~~
conf.d linguist-language=Nginx
~~~

You could also use a modeline to achieve the same effect:

~~~nginx
# -*- nginx -*-
server {
	listen 8002;
	server_name homepage;
	root /home/ollien.com/www/;
	charset utf-8;

	location / {}

	location /index.html {}

	location /static {
		autoindex off;
	}
}
~~~

**Comment by ollien** [comment]
That's always an option. I just figured that because it's the default name for nginx, it made sense to report this as an issue. Thanks for the tip-off, though!

**Comment by Alhadis** [comment]
@pchaigno, @larsbrinkhoff Should we look at adding this as an Nginx filename?

**Comment by larsbrinkhoff** [comment]
Did a quick search.  `conf.d` seems to be used in many places, not just by Nginx.

**Comment by Alhadis** [comment]
Yup, thought so. Probably a very common abbreviation of `configure directory` or something to that effect.

@ollien As you can see, it's not an Nginx thing. You're best following the steps I explained to fix the misclassification.

**Comment by ollien** [comment]
Ah ok. Whoops! Closing, then. Thanks for your help!
