### ISSUE TITLE
Repository is being misclassified as HTML instead of Python

### ISSUE THREAD

**Issue by alexisCata** [github/linguist#3738]
https://github.com/alexisCata/tornado

**Comment by lildude** [comment]
This is because your single HTML file is vastly larger than the two Python files:

HTML 3.87 KB
Python 1.15 KB

... which works out to ~77% HTML and ~23% Python so the classification is correct.

If you don't want the HTML to count, you'll need to use a [manual override](https://github.com/github/linguist#overrides) or write more Python 😉
