### ISSUE TITLE
linguist-vendored=false doesn’t work for my commit

### ISSUE THREAD

**Issue by binki** [github/linguist#3757]
I added a `test/examples/.gitattributes` with:

```
*/node_modules/** linguist-vendored=false
```

And `git check-attr` tells me I set it correctly:

```
$ git check-attr linguist-vendored -- test/examples/package-errors/node_modules/x/index.js
test/examples/package-errors/node_modules/x/index.js: linguist-vendored: false
```

All those changes were completed in https://github.com/binki/flow-result-checker/commit/0042c9eaae2a0c8cbfd6916d7b6de9848fabd066. However, the diff for the subsequent commit (https://github.com/binki/flow-result-checker/commit/d9b78d0fad5ffcbbd42b86301c9c1b4b36bb29bd) shows:

> Some generated files are not rendered by default. [Learn more](https://github.com/github/linguist).

Why doesn’t this documented means of unvendoring code work?

**Comment by lildude** [comment]
> Why doesn’t this documented means of unvendoring code work?

This is because the file has been identified as "generated", not vendored:

![screen shot 2017-12-02 at 13 22 18](https://user-images.githubusercontent.com/627280/33516058-e22d3fd2-d763-11e7-8ba5-bbeacf635a66.png)

... and changes to generated files are _not_ shown in diffs. Confusingly, all files under node_modules are currently classified as generated and vendored, but that's a different topic.

Since you logged this issue, you can now use `linguist-generted=false` to override this behaviour.
