### ISSUE TITLE
IDL .pro files identified as prolog files

### ISSUE THREAD

**Issue by EllenWasbo** [github/linguist#3761]
2 of [my 3 IDL Projects](https://github.com/EllenWasbo) are identified as Prolog. 
I found [this closed older issue](https://github.com/github/linguist/issues/2305) of the opposite problem (Prolog identified as IDL). 
So the issue is not yet fixed from all points of view. Can I do anything to force it to be identified as IDL?

**Comment by lildude** [comment]
Whoops, a little late here.  Looks like a bit of work is needed to improve the classification here.  We'd welcome a PR to improve the classification.

If you're looking for a quick fix: an [override](https://github.com/github/linguist#using-gitattributes) to specify the correct language will do the trick.

**Comment by pchaigno** [comment]
#3931 fixes a slight defect of our Prolog heuristic identified while going through your IDL projects. It won't change the detection results for any of them unfortunately. The issue here is that we're often relying on the last-resort Bayesian classifier to classify `.pro` files. Two ways to improve this:

1. Improve [the IDL `.pro` heuristic](https://github.com/github/linguist/blob/8d27845f8caeb5bb5633d1e4b09b2d3c796e1d9a/lib/linguist/heuristics.rb#L388) to identify more IDL files. Our current heuristic is very basic and we could use your help to improve it.
0. Improve the last-resort Bayesian by adding more sample IDL files. I've noticed that your repositories are under GPL license so those files can't be used for Linguist (requires a permissive license), but maybe you know some other source for samples, or could relicense a few of your files under a permissive license?

**Comment by pchaigno** [comment]
Flagging as stale.
