### ISSUE TITLE
Javascript/JSX single-quote/apostrophe breaks syntax highlighting

### ISSUE THREAD

**Issue by helios1138** [github/linguist#3775]
Basically, this is the issue https://i.gyazo.com/45d9921e631ea8274d97c4af9c062628.png

**Comment by helios1138** [comment]
I know it says to report issues to specific language repo, but the JSX repo seems to be version-locked/deprecated: https://github.com/github-linguist/language-babel

**Comment by lildude** [comment]
Yeah, this is a bit of a known issue and stems from changes made to the upstream grammar that aren't compatible with the regex engine (Ruby's PCRE compiled without the `PCRE_UCP` flag - see https://github.com/github/linguist/issues/3291#issuecomment-255750842 why) forced us to lock to a particular version. More details in https://github.com/github/linguist/issues/3044

I've done a quick crude test and maybe switching to https://github.com/babel/babel-sublime may be the best solution going forward. It's not as actively developed as https://github.com/gandm/language-babel but it is recommended for Sublime by Facebook [here](https://github.com/facebook/react/wiki/Complementary-Tools#editor-integration) and doesn't experience the problem...

- with the apostrophe - [Lightshow example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbabel%2Fbabel-sublime%2Fmaster%2FJavaScript%2520%28Babel%29.YAML-tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbuzinas%2Flinguist%2Fb32fbbbec311cb11e666c7f2bbd56207ddc9fad1%2Fsamples%2FJSX%2Fsample.js&code=%27use+strict%27%3B%0D%0A%0D%0Aconst+React+%3D+require%28%27react%27%29%0D%0A%0D%0Amodule.exports+%3D+React.createClass%28%7B%0D%0A++render%3A+function%28%29+%7B%0D%0A++++let+%7Bfeeds%2C+log%7D+%3D+this.props%3B%0D%0A%0D%0A++++log.info%28feeds%29%3B%0D%0A++++return+%3Cdiv+className%3D%22feed-list%22%3E%0D%0A++++++%3Ch3%3ENews+Feed%27s%3C%2Fh3%3E%0D%0A++++++%3Cul%3E%0D%0A++++++++%7Bfeeds.map%28function%28feed%29+%7B%0D%0A++++++++++return+%3Cli+key%3D%7Bfeed.name%7D+className%3D%7Bfeed.fetched+%3F+%27loaded%27+%3A+%27loading%27%7D%3E%0D%0A++++++++++++%7Bfeed.data+%26%26+feed.data.length+%3E+0+%3F%0D%0A++++++++++++++%3Cspan%3E%7Bfeed.name%7D+%3Cspan+className%3D%27light%27%3E%28%7Bfeed.data.length%7D%29%3C%2Fspan%3E%3C%2Fspan%3E%0D%0A++++++++++++++%3A+%27feed.name%27+%7D%0D%0A++++++++++%3C%2Fli%3E%0D%0A++++++++%7D%29%7D%0D%0A++++++%3C%2Ful%3E%0D%0A++++%3C%2Fdiv%3E%3B%0D%0A++%7D%0D%0A%7D%29%3B)
- or the simple import lines - [Lightshow example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbabel%2Fbabel-sublime%2Fmaster%2FJavaScript%2520%28Babel%29.YAML-tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbuzinas%2Flinguist%2Fb32fbbbec311cb11e666c7f2bbd56207ddc9fad1%2Fsamples%2FJSX%2Fsample.js&code=import+%27js%2Fweb.jsx%27%3B%0D%0Aimport+%27console.jsx%27%3B)
- or the larger example from https://github.com/github/linguist/issues/3044 (though this does show correctly now because of the locking) - [Lightshow example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbabel%2Fbabel-sublime%2Fmaster%2FJavaScript%2520%28Babel%29.YAML-tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbuzinas%2Flinguist%2Fb32fbbbec311cb11e666c7f2bbd56207ddc9fad1%2Fsamples%2FJSX%2Fsample.js&code=import+React+from+%27react%27%3B%0D%0A%0D%0Avar+ExampleApplication+%3D+React.createClass%28%7B%0D%0A++render%3A+function%28%29+%7B%0D%0A++++var+elapsed+%3D+Math.round%28this.props.elapsed++%2F+100%29%3B%0D%0A++++var+seconds+%3D+elapsed+%2F+10+%2B+%28elapsed+%25+10+%3F+%27%27+%3A+%27.0%27+%29%3B%0D%0A++++var+message+%3D%0D%0A++++++%27React+has+been+successfully+running+for+%27+%2B+seconds+%2B+%27+seconds.%27%3B%0D%0A%0D%0A++++return+%3Cp%3E%7Bmessage%7D%3C%2Fp%3E%3B%0D%0A++%7D%0D%0A%7D%29%3B%0D%0A%0D%0Avar+start+%3D+new+Date%28%29.getTime%28%29%3B%0D%0A%0D%0AsetInterval%28function%28%29+%7B%0D%0A++ReactDOM.render%28%0D%0A++++%3CExampleApplication+elapsed%3D%7Bnew+Date%28%29.getTime%28%29+-+start%7D+%2F%3E%2C%0D%0A++++document.getElementById%28%27container%27%29%0D%0A++%29%3B%0D%0A%7D%2C+50%29%3B) 

Thoughts @Alhadis, @larsbrinkhoff & @pchaigno

**Comment by pchaigno** [comment]
> I've done a quick crude test and maybe switching to https://github.com/babel/babel-sublime may be the best solution going forward.

:+1:

**Comment by lewisblackwood** [comment]
Also an open PR with an attempt to fix #3677.

Would be so rad to see a fix for this, would be more than happy to help if someone can point me in the right direction of the fix you'd like to see.

**Comment by lildude** [comment]
@lewisblackwood Yup. Your fix is also feeling the apostrophe pain.  I'll spin up a PR to switch the source for the grammar.

**Comment by lewisblackwood** [comment]
@lildude I saw that your PR was closed on this. Is there anything we can do here to get this fixed? Still a big frustration for us!

**Comment by lildude** [comment]
> Is there anything we can do here to get this fixed?

Beg the original upstream maintainer to relax his ways would be ✨  but sadly that's not likely to happen. 😢 

The only alternative is to either update and keep maintaining our own fork of https://github.com/gandm/language-babel (not ideal) or find a better, yet still maintained, source for the grammar as https://github.com/babel/babel-sublime is lacking.

@Alhadis, I'm not an expert with writing/maintaining grammars, but how hard would it be to update https://github.com/github-linguist/language-babel with the upstream changes and tweak things to play nice with Linguist?  At the moment, that's looking like the quickest solution to this long running issue.  I'm not asking for any obligation for you to do it, just your expert opinion.

**Comment by Alhadis** [comment]
I don't imagine it'd be terribly difficult. Theoretically, it should be straightforward to hack together a script which converts Oniguruma-only grammars to PCRE-friendly ones. Both engines have different syntax for what're ultimately the same features.

This would be my preferred approach, because the actual grammar itself is [long and beastly](https://github.com/gandm/language-babel/blob/ea2430d/grammars/Babel%20Language.json). Updating that by hand would be absurd. 😀

**Comment by ncaq** [comment]
I have found one case to break.

~~~js
const a = ["I'm", "foo"];

switch (true) {
  case /I'm foo/.test(a.join(' ')):
    console.log(true);
    break;
}
~~~

**Comment by lunarraid** [comment]
I know this issue is closed, but I am still seeing the issue whenever using an apostrophe inside of a text node, which is really messing with my code reviews:
```
render () {
  return (
    <Text>
      It's an apostrophe!
    </Text>
  );
}
```

**Comment by Alhadis** [comment]
I'm guessing that using a `RIGHT SINGLE QUOTATION MARK` ([U+2019](https://graphemica.com/%E2%80%99)) would be out of the question, right? 😉

**Comment by lunarraid** [comment]
Ha! Obviously, I'd prefer the syntax highlighting handle the edge case, but this is a surprisingly good suggestion for my particular use case.

**Comment by lildude** [comment]
I hope to squeeze in a release this week or next and will experiment with @Alhadis's suggestion from https://github.com/github/linguist/issues/3044#issuecomment-452385154

**Comment by mohsinulhaq** [comment]
any update here?

**Comment by lildude** [comment]
> any update here?

Nope. This is still a problem with the grammar and my attempt to switch it out wasn't successful - see https://github.com/github/linguist/issues/3044#issuecomment-459420383

**Comment by lildude** [comment]
Actually, looks like the upstream Atom grammar will get updated to reflect this. See https://github.com/github/linguist/issues/3044#issuecomment-461474332 onwards with a reference to https://github.com/atom/language-javascript/issues/641 in the upstream grammar. So as it stands, we're waiting on the upstream grammar.
