### ISSUE TITLE
Krakatau assembly misclassified as Objective J

### ISSUE THREAD

**Issue by Storyyeller** [github/linguist#3798]
Some Krakatau assembly files (an extension/variant of Jasmin) are instead misclassified as Objective J.

Classifiying them as Jasmin, while not entirely accurate, would be much more reasonable.

https://github.com/Storyyeller/Krakatau/search?l=objective-j

**Comment by Storyyeller** [comment]
One possible heuristic is to check if any lines start with `.class `, because this should be true for every Jasmin file, but as far as I can tell is not valid Objective J.

**Comment by Alhadis** [comment]
👋 Hey @Storyyeller,

From what I can tell, Krakatau appears to be a language of [your design](https://github.com/Storyyeller/Krakatau). If it happens to have enough in-the-wild usage (hundreds of repositories across GitHub), don't hesitate to send a pull-request to have Krakatau formally recognised on GitHub. Please make sure you've read the [procedure for adding a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) first. =)

Otherwise, if Krakatau commands only a small usage on GitHub, we'll have to stick with the Jasmin classification for now. You can use the [`linguist-language`](https://github.com/github/linguist/#using-gitattributes) attribute to fix the Objective-J misclassification:

~~~
*.j linguist-language=Jasmin
~~~

Adding some Jasmin samples might help to train the Bayesian classifier better with telling the difference between Objective-J and Jasmin files, however. =)

**Comment by Storyyeller** [comment]
Would it be possible to add a heuristic as I suggested? That should solve the issue more reliably than the classifier.

**Comment by Alhadis** [comment]
Roughly how many files across GitHub do you predict are being misclassified this way?

**Comment by Storyyeller** [comment]
Well, there's 10 files in my own repo. I'm not sure how to search other repos, but I expect that there are at least a couple others with the same issue.

**Comment by Alhadis** [comment]
I'm sorry, but this isn't what the heuristics feature is for. Heuristics are used as something of a last resort, when the Bayesian classifier is failing to catch certain edge cases, or when the distinction between two formats is so obvious there's absolutely no room for misclassification.

This is simply a common case of the classifier making a humble mistake in its analysis. You can help improve its accuracy by submitting a pull-request with more detailed Jasmin and Objective-J files, and/or fix the files in your project manually using the solution I described earlier.

A heuristic would only be necessary if there were potentially hundreds of repositories being affected by this, and even then, these sorts of scenarios are often solved simply by adding more detailed samples.
