### ISSUE TITLE
.gitattributes not working to include markdown files as non-documentation files

### ISSUE THREAD

**Issue by bradywestveer** [github/linguist#3819]
I have `docs/* linguist-documentation=false` in my `.gitattributes` to count the files in the docs/ folder as actual code files, but the repo languages are unchanged and still not accurate.

**Comment by lildude** [comment]
This is expected as Markdown is categorised as prose so doesn't count towards the language statistics. 

The `linguist-documentation` is to tell Linguist to look for code in the directory referenced instead of ignoring the directory as a whole. It doesn't force Markdown to be considered for the language statistics and there is no way to force it to be either.

**Comment by ElnuDev** [comment]
I don't understand why this was closed. There should be a way to consider markdown files as not documentation.

**Comment by Alhadis** [comment]
@ElnuDev There is now. See [`linguist-detectable`](https://github.com/github/linguist#detectable), which was added after this PR was closed.
