### ISSUE TITLE
Githubs language statistics include vendored files, linguist's README says otherwise

### ISSUE THREAD

**Issue by karyon** [github/linguist#3825]
The README says `Click on the name of the language in the stats bar to see a list of the files that are identified as that language. If you see files that you didn't write, consider moving the files into one of the paths for vendored code, or use the manual overrides feature to ignore them.`.

However, https://github.com/fsr-itse/EvaP/search?l=javascript includes e.g. all `*.min.js` files in that repository, which should be vendored files.

So either githubs behaviour or the README seems to be wrong :)

**Comment by pchaigno** [comment]
Thanks for reporting this :zap: 

Your `*.min.js` files are actually recognized as vendored files by Linguist and not included in language statistics. Vendored files do appear in search results, so the README is incorrect. Not sure how we could improve this, since the only way I know to check whether a file is marked vendored is to run Linguist locally... @lildude @Alhadis Any idea?

**Comment by lildude** [comment]
Yeah, I've not felt too comfortable about the "use search" method of confirming Linguist is doing as you expect as search doesn't take into account various Linguist settings or behaviours. It's also got it's own constraints which don't affect Linguist.

I'll have to have a think about this as as you pointed out, there isn't a way within the public UI to confirm if files have been successfully ignored or not.

**Comment by pchaigno** [comment]
We'd really need a Heroku app to run Linguist on a repository...

**Comment by enlighter** [comment]
Hi, I am facing a similar problem. This is my github project structure:

![screenshot from 2017-12-11 15-06-53](https://user-images.githubusercontent.com/1504242/33824622-077b150c-de85-11e7-8fa3-f9bb527b3a29.png)

All Javascript and CSS files are within the `static/` folder, which should have been enough for linguist to consider them as vendored. When that didn't happen, I created the following `.gitattributes` file about a week back:

`
static/* linguist-vendored
static/admin/css/* linguist-vendored
static/admin/js/* linguist-vendored
*.css linguist-vendored
*.js linguist-vendored
`

But as you can see from the screenshot, the js and css files are being considered as language for the project, i.e. not vendored. And since there are no other js and css files other than in subfolders mentioned within `static/` path, isn't the conclusion that the linguist vendored functionality is not working correctly?

**Comment by lildude** [comment]
The `static/` folder on its own isn't vendored by default so it's expected that your files would _not_ be ignored by default. Your override should however work and does in my test repo at https://github.com/lildude/test-vendoring-static-js-css - I've used your entire override list though only the first line should do the trick.

Can you let me know the name of your repo so we can see what's happening.

**Comment by enlighter** [comment]
OK. Here's the repository link: https://github.com/enlighter/PSVA_server. Please check what's going wrong.

**Comment by lildude** [comment]
@enlighter It's a typo: you've misspelt `.gitattributes` as `.gitattribues`

Correcting the filename results in the correct behaviour.

**Comment by enlighter** [comment]
Ah! Thank you for the quick feedback. This is a bit embarrassing!

**Comment by lildude** [comment]
I think we can close this issue now. Docs have been updated to make it clearer as to how Linguist works and the search gotcha. Feel free to open a new issue if docs need further clarification.

**Comment by karyon** [comment]
@lildude fyi, in the PR #3955 are three more issues described as "fixed" which haven't been closed.
