### ISSUE TITLE
JS Repo being classified as CSS

### ISSUE THREAD

**Issue by Always-Sunny** [github/linguist#3827]
https://github.com/Always-Sunny/Ruby

When you click the code analytics bar, it says CSS is 89% of the code, but then when you click the CSS link, it says that it can't find the code. I've tried adding node_modules/ to .gitignore, and I've even deleted the repo and made a new repo, uploaded my code, and it still reports as mostly CSS. 

I've looked up similar issues, but they weren't JS being seen as CSS.

**Comment by lildude** [comment]
There are a few things happening here...

1. CSS is the predominant language thanks to all the SCSS files in the repo.
2. SCSS isn't displayed as its own language but is classified as part of the CSS group as you can see here https://github.com/github/linguist/blob/4cd558c37482e8d2c535d8107f2d11b49afbc5b5/lib/linguist/languages.yml#L3986-L3995 ... and this is why you are seeing CSS rather than SCSS in the language stats.
3. The search itself is looking for the group (CSS) rather than the actual language (SCSS), hence you don't see any files when clicking CSS in the language stats.

So why is (S)CSS the predominant language? Because of the total size of all the files. You have 56.3 KB of SCSS files versus only 5.69 KB of Javascript and 610 B of HTML.

So for all intents and purposes, the language stats are right and the search is a little obscure, but makes sense once you understand how things are working behind the scenes.

If you don't want the (S)CSS to count as part of the statistics, you will need to implement a manual override to either mark the files as vendored or generated.
