### ISSUE TITLE
Only one language is reported but not the main one

### ISSUE THREAD

**Issue by Ppjet6** [github/linguist#3830]
https://github.com/Ppjet6/movim-ansible-provisioning

I see `Nginx` being reported as 100%, when in fact [the search shows](https://github.com/Ppjet6/movim-ansible-provisioning/search?l=nginx) Yaml being the most present in the repository.

I am not asking to have it marked `Ansible` (#3114), just `Yaml` would be good for now.

**Comment by lildude** [comment]
The yaml files are being excluded from the language stats because Yaml is considered a `data` "language" as you can see https://github.com/github/linguist/blob/4cd558c37482e8d2c535d8107f2d11b49afbc5b5/lib/linguist/languages.yml#L5073-L5074

... and like XML, is not included in the language stats.

It _is_ however included in the search results as search is independent of language statistics.

**Comment by Ppjet6** [comment]
But nginx is also of type data apparently. What's the rationale here?

https://github.com/github/linguist/blob/4cd558c37482e8d2c535d8107f2d11b49afbc5b5/lib/linguist/languages.yml#L2874-2875

**Comment by lildude** [comment]
Ooops, I forgot to address that point.  GitHub.com is currently running with Linguist v5.2.0 which pre-dates the merging of https://github.com/github/linguist/pull/3751 which correctly flipped this from markup to data.  

The section in v5.2.0 looks is as such:

https://github.com/github/linguist/blob/edabdc75a5373e84dccc059a48cfc2d7c38bbde1/lib/linguist/languages.yml#L2843-L2844

The next release of Linguist will include these changes and GitHub.com's behaviour will then fall in line with what is currently in master of this repo.

**Comment by Ppjet6** [comment]
Fair enough, thanks for the reply.
I'll have to lookup what that behaviour will be then.
