### ISSUE TITLE
Repo tagged as html when no such files exist

### ISSUE THREAD

**Issue by peterhalpin** [github/linguist#3836]
I have a repo that is mainly R but its tagged as html. After clicking on the language details bar, I  see the image below -- there are no html files found in the repo. Any advice on how to fix this would be great. Thanks. 

https://github.com/peterhalpin/scirt

![screen shot 2017-09-23 at 6 14 45 pm](https://user-images.githubusercontent.com/8593617/30777573-5d782d2e-a08b-11e7-8b36-98772c442a8b.png)

**Comment by lildude** [comment]
What's happening here is a little odd due to the way Linguist works versus how search works.

Linguist is detecting `old_code/Collab_Outcomes.html` is HTML and thanks to its size (780KB) is responsible for for it being marked as the predominant language. 

Search on the other hand is ignoring the file because of its size. [Files larger than 384KB are not indexed](https://help.github.com/articles/searching-code/#considerations-for-code-search) hence it doesn't show up in the search results.

If you don't want this file to be counted in the language stats you'll need to implement a [manual override](https://github.com/github/linguist#overrides). Looking at the contents, a generated override may be best as it's almost entirely base64 encoded data so not human readable in the current form anyway.

**Comment by peterhalpin** [comment]
Thanks a lot @lildude !
