### ISSUE TITLE
Python multi line syntax highlighter

### ISSUE THREAD

**Issue by edulorandi** [github/linguist#3838]
Hello!
I couldn't help but notice that the github syntax highlighter does not identify the multiple line comment in python, where 3 consecutive quotes means the beginning and end of a comment block.

For example: 
![print](https://user-images.githubusercontent.com/20970873/30863366-3c85903e-a2a7-11e7-97ef-f3528e5ed63a.png)

**Comment by Alhadis** [comment]
Hi @edulorandi,

The string is actually highlighted: it's just being highlighted with a dark colour (`#032f62`). It's the same colour that's applied to every other type of string, too:

~~~python
def read_file(file_path: str) -> list:
	"Double-quoted string"
	'Single-quoted string'
	"""Triple-quoted string"""
	"""
	Open the file, read its lines and put it into a list.
	:param file_path: string path to the csv file
	:return: list of lines from the file
	"""
	my_list = [];
	with open(file_path, 'r') as csv_file:
		reader = list(csv.reader(csv_file))
		return reader[1:]
~~~

You'll have to contact [GitHub support](https://github.com/support) if you have suggestions about the colours used for syntax highlighting - that's actually not something Linguist has any control over. I'm afraid only GitHub's design team have any control over that.

Also, because I'm a Perl snob, here's your Python function in a single line of Perl code:

~~~perl
my @lines = do { local @ARGV = ("mess.1"); <>; };
~~~

(Sorry, I couldn't help it 😜)

**Comment by pchaigno** [comment]
Actually, I think it's a choice of [the grammar used for Python highlighting](https://github.com/MagicStack/MagicPython) to highlight [docstrings](https://stackoverflow.com/a/7057488/6884590) as strings rather than comments:
```python
# Highlighted in grey?
"""
Highlighted in dark blue?
"""
```
If you think this is incorrect (and have arguments), you should open an issue on their repository. Please make sure this issue wasn't raised before.

**Comment by Alhadis** [comment]
@pchaigno No, I checked the CSS rule that's targeting the highlighted region. The colour is applied by the same class used for ordinary string tokens. Furthermore, the grammar is also using the `string` scope: if for any reason GitHub prioritised `docstring` over `string`, it would still be a matter outside the grammar author's responsibility.

**Comment by stuarteberg** [comment]
1. I would like to second this request for a color change, no matter where the unfortunate color scheme is coming from.

2. Flame-war proposal:  :fire: **ACCEPTED** :fire:

   Your Perl code lacks the functionality of his original function. His function actually *parses* the CSV rows into a list-of-lists of strings, and it skips the header row (hence the `[1:]`).

   But your version would be even shorter if it were translated to Python:
    ```python
    lines = list(open(filePath))
    ```

    Heck, even the original, fully-functional version can be made quite short:

    ```python
    import csv; lines = list(csv.reader(open(filePath)))[1:]
    ```

**Pop quiz:** Which one is not like the others:

- COBOL
- ALGOL
- FORTRAN
- Perl

<details>
<summary>Click for Answer</summary>
Trick question!  For all intents and purposes, they're the same.
</details>
