### ISSUE TITLE
Using linguist in .gitattributes to override language in README.md doesn't work

### ISSUE THREAD

**Issue by Iolaum** [github/linguist#3842]
As said in the title.

The .gittattributes file is
```
$ cat .gitattributes
README.md linguist-language=Shell
```

The [repository](https://github.com/Iolaum/CompileTF) doesn't have any other file identified as code so the README should dominate the language stats (I 've put all the instructions there). I 'd like shell to appear as language because that's what all the relevant instructions use. But using the override option of linguist doesn't work in this case.

**Comment by lildude** [comment]
The reason this isn't having any effect is because `README` files are explicitly defined as documentation... https://github.com/github/linguist/blob/e98728595bc2f3e72b0668d60e31cbe441c48799/lib/linguist/documentation.yml#L19-L28 so excluded from the stats regardless of content or overrides. To get the behaviour you want you need to override the documentation attribute and set the language like I've done in the fork of your repo at https://github.com/lildude/CompileTF

**Comment by Alhadis** [comment]
Hey, wow! @lildude, how long has GitHub supported those embedded code frames? Is that a recent feature?

**Comment by lildude** [comment]
Yup. Announced in August https://github.com/blog/2415-introducing-embedded-code-snippets

**Comment by Iolaum** [comment]
Thanks a lot @lildude for the fix and explanation. 

Already PR'd your fix :smile:
