### ISSUE TITLE
My repository's language isn't JavaScript but Python.

### ISSUE THREAD

**Issue by junaid1460** [github/linguist#3850]
https://github.com/junaid1460/Student-Achievement-Portal check this repo. 
and also this repo https://github.com/junaid1460/google-foobar

**Comment by lildude** [comment]
Well, it does have a lot of Javascript files in it - https://github.com/junaid1460/Student-Achievement-Portal/search?l=javascript - waaaay more than python 😄 

If you don't want them to count towards the language stats, you'll need to implement an [override](https://github.com/github/linguist#overrides).

**Comment by Alhadis** [comment]
👋 Hey @junaid1460, welcome to Linguist

The reason JavaScript has topped the usage stats for your repositories is due to [the vendored files](https://github.com/junaid1460/Student-Achievement-Portal/search?l=javascript). they contain: [`karma.conf.js`](https://github.com/junaid1460/Student-Achievement-Portal/blob/278950141326e357d81c7069416486d282f11f50/client_source/student/karma.conf.js) and [`protractor.conf.js`](https://github.com/junaid1460/Student-Achievement-Portal/blob/278950141326e357d81c7069416486d282f11f50/client_source/student/protractor.conf.js), to name two such examples. These are generally files that we don't include in language statistics because they're not written by the codebase's author - they're checked into a project as third-party code.

You can exclude JavaScript libraries and framework files by targeting them with a `.gitattributes` rule that marks them as vendored:

~~~
path/to/vendored.js linguist-vendored
~~~

**Comment by junaid1460** [comment]
sure. thanks
