### ISSUE TITLE
BUILD(shell script) files misclassified as Python

### ISSUE THREAD

**Issue by Katsuke00** [github/linguist#3893]
The files named "BUILD", which are shell script, are misclassified as python.
link:https://github.com/eltanin-os/port

**Comment by pchaigno** [comment]
Is that a private repository? We can't access private repositories. Do you have a public example?

**Comment by lildude** [comment]
It's a typo... it should be https://github.com/eltanin-os/ports

The reason this is happening is because the `Filename` classifier, which takes specific filenames directly associated with a language in `languages.yml`, takes precedence over the `Shebang` classifier at https://github.com/github/linguist/blob/d968b0e9ee5cc0c1dcbb181a3f139bd43751b658/lib/linguist.rb#L60-L67

As a result the `BUILD` filename which is associated with Python at https://github.com/github/linguist/blob/d968b0e9ee5cc0c1dcbb181a3f139bd43751b658/lib/linguist/languages.yml#L3594 is being used to classify the file.

To get these files identified as shell you can either add a modeline entry to each file (PITA) or set a [language override](https://github.com/github/linguist#using-gitattributes) in your `.gitattributes`.

**Comment by Katsuke00** [comment]
I tried first to write: `BUILD linguist-language=Shell` in `.gitattributes` as i thought it would classify any file with that name as a shell script. I may have missed something, but i did not understand how to set the language with the `.gitattributes`.
