### ISSUE TITLE
repo programming language composition incorrect

### ISSUE THREAD

**Issue by tomecho** [github/linguist#3897]
I found what I believe to be a bug in github's programming language composition on a repo.  My repo tomecho/frat_wizard_master_server_lite is almost entirely ruby (it's a rails app) but linguist detects it as almost entirely javascript.

**Comment by lildude** [comment]
For future reference, it's a lot easier to troubleshoot these kinds of issues with public repos but as I work for GitHub, I have access to the backend analysis that Linguist does (I can't see your code, but I can see the filenames) and the reason javascript is the predominant language is because you've got about 23MB of Javascript under various combinations of `*?/assets/javascripts/`, most of which appears to be date or language related.  You can see these yourself by clicking the coloured bar and then clicking Javascript.

As you probably didn't write these yourself and clearly don't want them to count, your best bet is to implement a [manual override](https://github.com/github/linguist#overrides) to either mark those files as vendored or generated.

As an aside, once you've addressed those, CSS will be the next most popular language (this also appears to be due to files you probably consider "someone elses code") and only then Ruby:

JavaScript 23.7 MB
CSS 421 KB
Ruby 71.6 KB
HTML 39.7 KB
CoffeeScript 14 KB

**Comment by tomecho** [comment]
Hmm ok thank you, this just differs from my experience on my other rails projects so I incorrectly assumed something was wrong.  Thank you for the explanation!
