### ISSUE TITLE
Linguist not recognizing any python in my repo

### ISSUE THREAD

**Issue by creatornader** [github/linguist#3901]
Hi! I am working in a repo right now and noticed that github isn't recognizing any of the python code that I am writing. It's not misclassified, it just isn't classified at all. This is confusing to me. Could you check it out?

https://github.com/Spotcrowd/storenode

Thanks

**Comment by pchaigno** [comment]
Is this a private repository? We don't have access to private repositories :-/

**Comment by lildude** [comment]
This is indeed a private repository. As @pchaigno mentioned, things are much easier to troubleshoot if repos are public. That said, as I work at GitHub, I can see the backend analysis and filenames, but not your code.

I can confirm your Python code _is_ being recognised:

HTML 11.9 MB
Python 531 KB
C++ 30.1 KB
Jupyter Notebook 11.1 KB
C 3.58 KB
Shell 2.24 KB

... but as you can see, most of the files in your repo have been detected as HTML. This is because you have a _lot_ of HTML files under `Eve/GST-Mapping/` - you can see this for yourself by clicking the coloured language bar and then click HTML.

If you don't want these files to be countered in your language stats, you'll need to implement a [manual override](https://github.com/github/linguist#overrides) to either mark these as vendored or generated.
