### ISSUE TITLE
GAMS code is misclassified as C++, Assembly, Pascal, SourcePawn, PHP and CartoCSS

### ISSUE THREAD

**Issue by olejandro** [github/linguist#3908]
https://github.com/balmorelcommunity/Balmorel

**Comment by lildude** [comment]
This is all happening because of the `.inc` file extension you've got for most of your files. This extension is _not_ associated with GAMS https://github.com/github/linguist/blob/d8e5f3c96518aa8be8b58abfa5c89cf05a6c991a/lib/linguist/languages.yml#L1382-L1388 but _is_ associated with all of the languages you've listed. This means the incorrect classification is happening due to a combination of the extension, heuristics and finally the tokenizer classification.

The CartoCSS classification is happening because of the use of the `.mss` extension. This is only associated with CartoCSS: https://github.com/github/linguist/blob/d8e5f3c96518aa8be8b58abfa5c89cf05a6c991a/lib/linguist/languages.yml#L636-L644

I see you've also only got a single file with the `.gms` extension so it's waaaaay down on the list of languages associated with your repo.

The best thing to do to resolve this is to implement a [manual override](https://github.com/github/linguist/blob/master/README.md#overrides) to best suit your needs.

**Comment by olejandro** [comment]
Thanks for a very prompt response!
Would it be possible to associate .inc files to GAMS, in addition to .gms? .inc is very commonly used to include data or additional code in a GAMS programme.

**Comment by lildude** [comment]
> Would it be possible to associate .inc files to GAMS, in addition to .gms?

Yup. Feel free to raise a pull request with the change to the `languages.yml` file and include an example of a `.inc` file that is a good representation of the language usage licensed under one of these licenses https://github.com/github/linguist/blob/9c4dc3047ca36e810f4584361cb3f04d76bee4a2/test/test_grammars.rb#L50-L62

**Comment by olejandro** [comment]
Ok thanks!
