### ISSUE TITLE
Only one language is reported 100%

### ISSUE THREAD

**Issue by Sanchez3** [github/linguist#3909]
html 100%   but I also use js, css, etc. Other projects also have this issue.

https://github.com/Sanchez3/skeletal

thanks

**Comment by Alhadis** [comment]
Linguist deliberately ignores certain files when calculating language statistics. In your case, it's ignoring [minified and compressed](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L57) files (as determined by the [`.min.css`](https://github.com/Sanchez3/skeletal/search?l=CSS) and [`.min.js`](https://github.com/Sanchez3/skeletal/search?l=JavaScript) extensions).

If you prefer these files be included in your repository's language stats, you can [use an override](https://github.com/github/linguist#vendored-code). Simply add a `.gitattributes` file to the root of your project which contains the following lines:

~~~
*.min.css linguist-vendored=false
*.min.js linguist-vendored=false
~~~

If you aren't seeing any difference after adding the `.gitattributes` file, it might be because the language bar is cached. Simply push a small change to your repository's files to force GitHub to refresh the stat-bar.

**Comment by Alhadis** [comment]
I'm going to close this, as I see you've acknowledged my answer. =)

If you have any further questions, please don't hesitate to ask.

**Comment by Sanchez3** [comment]
I add 
```
*.min.css linguist-vendored=false
*.min.js linguist-vendored=false
```
but js 0%...
https://github.com/Sanchez3/skeletal

**Comment by Alhadis** [comment]
Ah... 😕 It seems like it isn't possible to unvendor minified files with extremely long lines. My mistake.

In this case, I'm afraid the usual overrides won't work. You'll simply need to upload the uncompressed copies of the files, as this is [hardcoded into Linguist](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L109).

If you don't have the uncompressed versions and you're *really* serious about including them in the repository's stat-bar, the hard solution is to insert line-breaks in each `.min.js` file to wrap each line to less than 110 characters

Please bear in mind the language statistics are to gauge code that *you* yourself have written. Things like minified files are deliberately excluded to give a more realistic summary of what authors themselves have coded.
