### ISSUE TITLE
Need to change language color.

### ISSUE THREAD

**Issue by vishuB** [github/linguist#3910]
In below image **Jupyter Notebook**  and **HTML** Language color is same.

![screenshot-2017-11-16 qiangxue machine-learning](https://user-images.githubusercontent.com/13677102/32887451-f3a7490a-cae9-11e7-8e92-d3b7efaddbc3.png)

https://github.com/qiangxue/machine-learning

**Comment by pchaigno** [comment]
Thanks for reporting this.

We have a proximity test in place to detect this kind of problem (#2298). It's not perfect obviously and I don't think we should necessarily increase the threshold because it failed once. Perhaps we could change the color for Jupyter Notebook. Any idea (color from logo, official color, etc.)?

**Comment by pchaigno** [comment]
Flagging as stale.
