### ISSUE TITLE
Eclipse Papyrus .di files erroneously recognized as D

### ISSUE THREAD

**Issue by DeBukkIt** [github/linguist#3914]
The diagrams created with the Eclipse plugin 'Papyrus' (actually **XML** format) have the .di file extension. Linguist recognizes them as language **D**, which is nonsense.
Analyzing the magic first line `<?xml version="1.0" encoding="UTF-8"?>` might help Linguist to guess correctly in the second attempt.

**Comment by lildude** [comment]
Linguist is detecting them at D precisely because of the`.di` extension. This extension is not associated with Papyrus at all. 

If this is a commonly and widely used extension of Papyrus, we'll gladly accept a PR adding support for it. Until then, you'll need a manual overdrive to identify these files as Papyrus.
