### ISSUE TITLE
incorrect qualification

### ISSUE THREAD

**Issue by mvit777** [github/linguist#3917]
My repo 
https://github.com/mvit777/custom_moodle 
gets classified as a javascript project 
but there is not a single javascript file in it.
To be precise there is nothing else but PHP files, so I doubt the .gitattributes file will fix anything

**Comment by lildude** [comment]
The classification is 100% correct. If you click the language bar and then Javascript, you'll see the culprit straight away: `local/customclasses/js/hello.js`

This one file is 47.3KB which is more than all of the PHP files added together which only accounts for 42KB.

You'll need to implement a manual override if you don't want this file included in the stats.

**Comment by mvit777** [comment]
Thank you very much, I did not realise the metric was based only on total bytes per language
Thought it also took in account the total number of files per language.
A .gitattributes like this should do the trick?

*.js linguist-language=PHP


      Da: Colin Seymour <notifications@github.com>
 A: github/linguist <linguist@noreply.github.com> 
Cc: mvit777 <7marvit@gmail.com>; Author <author@noreply.github.com>
 Inviato: Venerdì 24 Novembre 2017 19:04
 Oggetto: Re: [github/linguist] incorrect qualification (#3917)
   
The classification is 100% correct. If you click the language bar and then Javascript, you'll see the culprit straight away: local/customclasses/js/hello.jsThis one file is 47.3KB which is more than all of the PHP files added together which only accounts for 42KB.You'll need to implement a manual override if you don't want this file included in the stats.—

**Comment by pchaigno** [comment]
> A .gitattributes like this should do the trick?
*.js linguist-language=PHP

@mvit777 Yes, that will "fix" your language statistics. However, the JS file will be highlighted as PHP code. Another solution is to simply vendor the JS file so that it doesn't appear in statistics:

    *.js linguist-vendored

**Comment by desertgem** [comment]
Thank you for all the input and help on this. My grandson has autism and
I'm trying to get this done for him but also myself. I'm fairly new to the
ethical side of this. I was completely hacked and my identity was stripped
in 2012 by veteran who used his knowledge to stalk and control. I've got 3
phones here and I knew they were performing strangely. I got on internet
and started researching how to take my phone's back. I worked almost 20 hrs
a day for 5 days now and had things halted but was just a bandaid. I had
overridden the "parent" and phone was better but since I've got migraine
and dealing with 2 of my grandkids being taken from my daughter and I can't
live with this phone in my face. How can I "open" this project or start of
it so I can save my sanity. I can do this but don't have strength mentally
or physically to try to stay ahead of remote access to my devices. I called
Norton security and they synced directly into my newest phone and told me I
was definitely hacked and to take phones to carrier... I'm not in charge of
my time right now and every part of my life is devoted to everyone else's
lives but desperately want control of my internet, data, phones, life and
sanity back. I have no doubt this is not correct way to approach this but
I'm at point of not knowing what else to do... Please help!!!

Sincerely,

Sammy
Desertgem
Noob at GitHub & Wiki
