### ISSUE TITLE
Linguist not recognizing Eagle language

### ISSUE THREAD

**Issue by eeshiken** [github/linguist#3918]
My groups [repo](https://github.com/technovus-sfu/swarmbots) with only Eagle files, has no language detected. When I run linguist on the local repo with `--breakdown --json` it returns empty `{}`. When linguist is run on the specific `.brd` file, it returns:
```
Type: Text
mime_type: text/plain
language: Eagle
```
I think this is why it doesn't recognize any language because in `languages.yml`, Eagle's mime_type is shown as `text/xml`

**Comment by lildude** [comment]
Eagle isn't appearing in the language statistics because Eagle files are considered data and not as a programming language files: https://github.com/github/linguist/blob/7be6fb013864b59e7c9ba76e3c0062dd95cedc76/lib/linguist/languages.yml#L1130-L1131

Data does not count towards the language stats. Eagle was included in the stats before https://github.com/github/linguist/pull/3743 corrected the behaviour. 

Unfortunately there's no way to force Eagle to be considered a programming language and this included in the stats at the moment, however the PR I've referenced above did prompt the suggestion of allowing users to override this and it's currently waiting on the completion of https://github.com/github/linguist/pull/3807

**Comment by eeshiken** [comment]
Alright, I was wondering why some repos had Eagle stats. Thank you. I'll go ahead and close this.

**Comment by seppestas** [comment]
Also see #3805 for a more global discussing on supporting non-code languages in Linguist.
