### ISSUE TITLE
Misclassification of language - even though no files with language found

### ISSUE THREAD

**Issue by leecher1337** [github/linguist#3936]
My repository https://github.com/leecher1337/libmswstr is plain C, but it is classified as 94.1% Objetive-C. If I click on "Objective C" language, it (correctly) doesn't show any Objective-C files.
Why does it think, that the repo is Objective-C?

**Comment by lildude** [comment]
Your repo is being classified as objective-C because of this one file...https://github.com/leecher1337/libmswstr/blob/master/src/nlstables.h

It's being misidentified (which is a common problem with header files as they look very similar in both languages) and it's by far the largest file in your repo at 1.52MB.

You'll need to implement a manual override to identify this file as C.

As for why the search doesn't return the file, it's also because of its size... GitHub doesn't [index files larger than 384KB](https://help.github.com/articles/searching-code/#considerations-for-code-search).

**Comment by leecher1337** [comment]
Thank you for your detailled explanation, I did a manual override now, works fine!
