### ISSUE TITLE
Wrong language detection

### ISSUE THREAD

**Issue by maxis42** [github/linguist#3938]
https://github.com/maxis42/ML-DA-Coursera-Yandex-MIPT

I have no PLSQL files at all. However, GitHub shows that I have 50% of them.

**Comment by quiterodroo** [comment]
Yes

**Comment by lildude** [comment]
This is happening because Linguist is detecting the `.vw` files in https://github.com/maxis42/ML-DA-Coursera-Yandex-MIPT/tree/master/6%20Data%20analysis%20project/1%20Internet%20users%20pattern%20mining/Week%206%20Vowpal%20Wabbit/data as PLSQL - `.vw` extension is associate with PLSQL here:

https://github.com/github/linguist/blob/e7e64bf39abb90cce9df2f531873d316f5d6b18f/lib/linguist/languages.yml#L3206-L3229

In your repo, the `model.vw` is nearly 40MB alone!!

These files aren't appearing in the search results when you click the language bar and then PLSQL because they are all larger than [384KB and GitHub doesn't index files that large](https://help.github.com/articles/searching-code/#considerations-for-code-search).

The best thing to do here is create a [manual override](https://github.com/github/linguist#overrides) to ignore these files. As these appear to be data files you probably want to mark them as vendored or generated.

**Comment by maxis42** [comment]
Thank you!
