### ISSUE TITLE
C repo misclassified as Objective-C

### ISSUE THREAD

**Issue by goroda** [github/linguist#3941]
My repo is here

https://github.com/goroda/Compressed-Continuous-Computation

It is being misclassified as Objective-C, when I click on the Objective-C files in the language stats bar, it does not list any files.

**Comment by lildude** [comment]
This is happening because you have one heeeeaaawg file that is being identified as Objective-C: https://github.com/goroda/Compressed-Continuous-Computation/blob/master/src/lib_funcs/legtens.h

This file is 39.6MB!! As it's [larger than 384KB, it is not indexed](https://help.github.com/articles/searching-code/#considerations-for-code-search) by GitHub's search, hence it doesn't appear in the results when you click the language in the language bar.

Unfortunately, the various forms of C share header file formats that make it hard to get the language right all the time.

To resolve this, you'll need to implement an [override](https://github.com/github/linguist#overrides) to either ignore the file or mark it the language you prefer it to be identified as.

**Comment by goroda** [comment]
Thanks! added *.h to be interpreted as C
