### ISSUE TITLE
First language in language bar does not appear in search

### ISSUE THREAD

**Issue by thomasrebele** [github/linguist#3944]
Hello,

I just saw that the project https://github.com/yago-naga/yago3 was classified as "50.5% Perl", but it contains no Perl code at all. When I click on the language (https://github.com/yago-naga/yago3/search?l=perl), it finds no files. However, it correctly shows Java as the most used language.
If the search would have returned any Perl files, I could have used .gitattributes to ignore these files.

GitHub API shows the wrong language, too: https://api.github.com/repos/yago-naga/yago3/languages

Any hints on how to fix this?

**Comment by pchaigno** [comment]
I ran Linguist locally on your repository and [this file] is being reported as Perl. There are often caching issues with the search results (and they go out of sync. with the language statistics).

**Comment by lildude** [comment]
There's no problem with the search or sync with the language stats... that file isn't showing in the search results because it's larger (considerably at 10.7mb) than [384kb so isn't indexed at all](https://help.github.com/articles/searching-code/#considerations-for-code-search). Search is independent of Linguist hence it is still counted for language stats though.

Looking at your repo, it appears all the files under https://github.com/yago-naga/yago3/tree/master/data/wordnet are large files and incorrectly identified. These don't appear to be the language identified and don't appear to be code either so the best thing to do is use an [override](https://github.com/github/linguist#overrides) to mark the directory or files as vendored or generated.

**Comment by thomasrebele** [comment]
Thanks for the help, now it makes more sense to me. I'll create a .gitattributes
