### ISSUE TITLE
Varnish VCL syntax highlighting is out of date

### ISSUE THREAD

**Issue by rezan** [github/linguist#3957]
The VCL grammer for Varnish/VCL breaks on 4.0+.

Please see: https://github.com/varnishcache/varnish-cache/blob/4.0/bin/varnishd/builtin.vcl

Its breaking on the new `return(synth())` syntax.

**Comment by lildude** [comment]
Linguist currently uses https://github.com/brandonwamboldt/sublime-varnish for Varnish/VCL syntax highlighting. You'll need to open an issue in that repo in order to have the grammar updated. Alternatively, if you know of a more recent and more functional grammar, please review https://github.com/github/linguist/blob/master/CONTRIBUTING.md and send us a PR to change the grammar source.

**Comment by rezan** [comment]
So I have a PR which fixes this here:

https://github.com/brandonwamboldt/sublime-varnish/pull/6

**Comment by rezan** [comment]
I will give it a few weeks and see if the maintainer responds, otherwise I will PR directly here with a fork. Thanks

@brandonwamboldt

**Comment by rezan** [comment]
Looks like its been merged: https://github.com/brandonwamboldt/sublime-varnish/commit/a2089722e6377b665fe4f664b1d44f5da54ea8a0

**Comment by pchaigno** [comment]
@rezan Thanks for the fix!

The reference to the grammar submodule will be updated automatically with the next release of Linguist.
