### ISSUE TITLE
repository now showing right languages.

### ISSUE THREAD

**Issue by man-u-13** [github/linguist#3978]
My repository does show just CSS as its language while it should also show HTML and javascript along with css.

Link : https://github.com/man-u-13/StyleWell.com

**Comment by lildude** [comment]
Errm, your repo _is_ showing CSS, HTML _and_ JavaScript:

![screen shot 2018-01-07 at 18 06 37](https://user-images.githubusercontent.com/627280/34652426-8929548c-f3d5-11e7-924f-7435ef8fede6.png)

As the README states, the proportions are based on the bytes of code, which in your case breaks down to:

CSS 21.1 KB
HTML 13.6 KB
JavaScript 571 Bytes

... with CSS being only slightly higher than HTML thanks to these files: https://github.com/man-u-13/StyleWell.com/search?l=css

So Linguist has correctly identified the languages in your repo and determined CSS is the most prominent.

The only way you can change this is to write more HTML (assuming you expect HTML to be the primary language) 😉 or use an [override](https://github.com/github/linguist#overrides) to ignore some of your CSS files, though this probably isn't the best approach as these look like files you've legitimately written yourself rather than files you've pulled in from other sources.

The choice is yours, but as things stand, your classification is correct.

**Comment by man-u-13** [comment]
Isn't there any way by which I can show it as both HTML and CSS? That would
be great.

**Comment by lildude** [comment]
Nope. GitHub only shows one language everywhere a language is displayed, other than the language stats bar. The next closest thing you can do is [Classifying your repository with topics](https://help.github.com/articles/classifying-your-repository-with-topics/).

**Comment by man-u-13** [comment]
Okay. Thanks :)
