### ISSUE TITLE
Mislabeling My React Repo as CSS after adding FontAwesome

### ISSUE THREAD

**Issue by jesskrich** [github/linguist#3985]
How do I change it back?

**Comment by lildude** [comment]
You didn't provide a URL to the affected repo, but I've done a bit of digging and found it - I think it's the github_user_profiles repo.

Font-Awesome is normally excluded from the stats thanks to: https://github.com/github/linguist/blob/512f077da8afb4390db05dce44355febe6d66d42/lib/linguist/vendor.yml#L64-L66 ... however it's not catching your situation thanks to the inclusion of the version number in the directory in your repo.  We could probably relax our regex a bit to cater for this.

In the mean time, you've got two choices:

1. Rename `font-awesome-4.7.0` to `font-awesome`, or
2. implement an override. In this case, I'd suggest the [vendor override](https://github.com/github/linguist#vendored-code).

**Comment by jesskrich** [comment]
Removing the number did not do the trick. Pleas reopen.

**Comment by lildude** [comment]
Hmmm, it should have done. I'll have to dig into why it's not working. In the mean time, using the overdrive I suggested is the best option.

**Comment by rixardo84** [comment]
hyyh

**Comment by lildude** [comment]
Oh, I know why this is happening still... the second regex was only updated just over a month ago in https://github.com/github/linguist/pull/3932 - you're hitting https://github.com/github/linguist/issues/3726.

We've not made a new release of Linguist since that PR was merged so GitHub.com is still using the old behaviour.

I plan on making a new release by the end of the month, so any changes after that will pick up the changes. Until then, a manual override is the way to go.

**Comment by pchaigno** [comment]
There's been two new releases since then and it looks like it solved the issue. Closing.
