### ISSUE TITLE
Wrong language detection

### ISSUE THREAD

**Issue by silas229** [github/linguist#3987]
In my [repository](https://github.com/silas229/fussball-testspiel) is a wrong language detection.
GitHub says, my project is written in JS, but when I search by language there are many more php files.
![](https://image.prntscr.com/image/R7Ei355JSRWYA2h0dZQXBA.png)
![](https://image.prntscr.com/image/EsN_AO4PQViodmLLKxoj6A.png)

Pls help me

**Comment by lildude** [comment]
As the readme states, Linguist calculates the repository break down by the bytes of code, not the number of files. Whilst you have more PHP files, your Javascript files are much larger giving you a breakdown of:

JavaScript 364 KB
CSS 180 KB
PHP 112 KB

Most of this is due to `fussball-testspiel/src/js/materialize.js` which weighs in at 359KB alone.

`materialize.css` was only recently added to Linguist as a "vendored" file in https://github.com/github/linguist/pull/3943/  - the most recently merged PR in Linguist. Accordingly, GitHub.com will still count this file when calculating the stats but won't as soon as the next release is made (I'm aiming for by the end of the month).

When the next release is made, this file will automatically be excluded from the stats. Until then, you'll need to implement a manual override, in this case I recommend a [vendor override](https://github.com/github/linguist#vendored-code).

**Comment by silas229** [comment]
Thank you for your fast answer!

I added this code to my `.gitattributes` file:
```
js/* linguist-vendored
js/init.js linguist-vendored=false
css/* linguist-vendored
css/style.css linguist-vendored=false
```
But there is still this:
![](https://camo.githubusercontent.com/ce2fe611e9b8297bc79f3aa2e1e5b4dc1a2e1125/68747470733a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f523745693335354a5352575941326830645a515842412e706e67)
What did I do wrong?

**Comment by pchaigno** [comment]
@silas229 You need to specify an absolute path. One of the following will work for the first line, for instance:
```
src/js/* linguist-vendored # exact, absolute path
*/js/* linguist-vendored # wildcarded, absolute path with 2-dir levels
**/js/* linguist-vendored # wildcarded, absolute path with n-dir levels
```

**Comment by silas229** [comment]
Oh, I forgot the source folder🙈
