### ISSUE TITLE
my repo is in swift and it marks as it objective c

### ISSUE THREAD

**Issue by zoharIOS** [github/linguist#3996]
my repository include swift code but github classify it as objective c and not swift, please change it.
https://github.com/zoharIOS/Swift-IOS-Projects
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
my repository include swift code but github classify it as objective c and not swift, please change it.
https://github.com/zoharIOS/Swift-IOS-Projects

### URL of the affected repository:
https://github.com/zoharIOS/Swift-IOS-Projects

**Comment by Alhadis** [comment]
@zoharIOS You've checked every step. Did you really follow each one? Particularly this:

> - [x] considered implementing an [override](https://github.com/github/linguist#overrides),

**Comment by lildude** [comment]
This is happening because the files in question _are_ written in Objective-C and not Swift.

If you follow the very first step in the "My repository is detected as the wrong language" section of the README:

> Click on the name of the language in the stats bar to see a list of the files that are identified as that language.

... you'll see all these files have `.h` and `.m` extensions and are under the `fmdb` directory, which comes from https://github.com/ccgus/fmdb (https://github.com/ccgus/fmdb/tree/master/src/fmdb precisely) which clearly states right at the top of their README:

> This is an Objective-C wrapper around SQLite: http://sqlite.org/

So Linguist is 100% correct.

If you don't want them to count, you'll need to implement an override, but you know that already from reading the README 😉.

Closing as Linguist is working as expected.
