### ISSUE TITLE
Github repo shows wrong language

### ISSUE THREAD

**Issue by BnSalahFahmi** [github/linguist#3997]
My project is written in TypeScript but still git showing my repo written in css.
Please change it to TypeScript.

My repo link - https://github.com/BnSalahFahmi/Movie-store

**Comment by Alhadis** [comment]
I see those [issue templates](https://github.com/github/linguist/pull/3972) are workin' out great...

**Comment by pchaigno** [comment]
Wish we had a bot to automatically close issues that disregard the template...

**Comment by lildude** [comment]
From the README you were advised to read by the issue template:

> The percentages are calculated based on the bytes of code for each language as reported by the List Languages API.

Looking at your repo we can see you've clearly got waaaaaaaay more CSS than TypeScript when you look at the bytes of code:

CSS 162 KB
TypeScript 52.2 KB
HTML 3.95 KB
JavaScript 1.61 KB

Additionally, if you follow the very first point of the "My repository is detected as the wrong language" section of the README:

> Click on the name of the language in the stats bar to see a list of the files that are identified as that language.

... you'll see the two CSS files that are to blame. If you look at the size of each you'll see  `src/app/core/sidebar/sidebar.component.css` is 161KB on its own, thus making it responsible for almost all of the CSS figure.

So how do you fix this? Write more TypeScript 😉 or use an override to ignore the large CSS file. I'll leave you to review the README for details on how to do this.

On a side note, please in future read and acknowledge the issue templates you encounter in issues. They are added to help _you_ first and the repository maintainers second. This issue is 100% avoidable as it is answered entirely in the README.
