### ISSUE TITLE
Rust files are being misclassified as RenderScript files

### ISSUE THREAD

**Issue by urschrei** [github/linguist#3998]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Several files in the rust-geo repository are being mis-classified as RenderScript. Because they have large loc counts, the repo language is being mis-classified.
### URL of the affected repository:
https://github.com/georust/rust-geo
Mis-classified files: https://github.com/georust/rust-geo/search?l=renderscript
### Last modified on:

2018-01-23

### Expected language:

Rust

### Detected language:

RenderScript

**Comment by lildude** [comment]
This is happening because the content of those files doesn't match anything the heuristic at https://github.com/github/linguist/blob/8da6ddf9d97ee1cd1d7119f3e8a5249df7d1590a/lib/linguist/heuristics.rb#L427-L433 ...can use to distinguish the two languages.

The content doesn't give a good variance in the language structure for the classifier to get it right either. In fact the content of those files is hard for a human to guess the language as they don't look like code at all but rather a list of co-ordinates, which would technically make it data.

As the `vec` at the beginning of each file appears to be a custom function/method name, rather than a standard language keyword or method, there's nothing we can do to improve the automatic classification of these files either.  Your only option is to implement a manual override to mark those files as Rust or ignore them.
