### ISSUE TITLE
Linguist JSON output fails with ASCII-8BIT to UTF-8 encoding issue

### ISSUE THREAD

**Issue by lediur** [github/linguist#4028]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

**Ruby version:** 2.5.0
**GitHub-linguist version:** 6.0.1

When analyzing the Rails repository (https://github.com/rails/rails), both `git-linguist` and `linguist --json` fail with the following error:

### `git-linguist --commit 52c9af6c51fbf686762ad2330f36fe9f8ce3c5d7 breakdown`

```
/tmp/rails$ git-linguist --commit 52c9af6c51fbf686762ad2330f36fe9f8ce3c5d7 breakdown

"\xE3" from ASCII-8BIT to UTF-8
/home/derrick/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:224:in `encode'
/home/derrick/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:224:in `generate'
/home/derrick/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:224:in `generate'
/home/derrick/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:394:in `dump'
/home/derrick/.rvm/gems/ruby-2.5.0/gems/github-linguist-6.0.1/bin/git-linguist:131:in `block in git_linguist'
/home/derrick/.rvm/gems/ruby-2.5.0/gems/github-linguist-6.0.1/bin/git-linguist:35:in `linguist'
/home/derrick/.rvm/gems/ruby-2.5.0/gems/github-linguist-6.0.1/bin/git-linguist:130:in `git_linguist'
/home/derrick/.rvm/gems/ruby-2.5.0/gems/github-linguist-6.0.1/bin/git-linguist:149:in `<top (required)>'
/home/derrick/.rvm/gems/ruby-2.5.0/bin/git-linguist:23:in `load'
/home/derrick/.rvm/gems/ruby-2.5.0/bin/git-linguist:23:in `<main>'
/home/derrick/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/home/derrick/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
```

### `linguist --json`

```
/tmp/rails$ linguist --json

Traceback (most recent call last):
        8: from /home/derrick/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
        7: from /home/derrick/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
        6: from /home/derrick/.rvm/gems/ruby-2.5.0/bin/linguist:23:in `<main>'
        5: from /home/derrick/.rvm/gems/ruby-2.5.0/bin/linguist:23:in `load'
        4: from /home/derrick/.rvm/gems/ruby-2.5.0/gems/github-linguist-6.0.1/bin/linguist:47:in `<top (required)>'
        3: from /home/derrick/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:394:in `dump'
        2: from /home/derrick/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:224:in `generate'
        1: from /home/derrick/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:224:in `generate'
/home/derrick/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:224:in `encode': "\xE3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

Both seem to fail to encode a filename when writing the JSON output.

However, `linguist --breakdown` analyzes the `rails` repository just fine and outputs the expected output grouped by language.

### URL of the affected repository:

https://github.com/rails/rails

### Last modified on:

2018-02-08

### Expected language:

Ruby

### Detected language:

N/A

**Comment by tenderlove** [comment]
Hi.  I poked at this for a little bit and I just wanted to drop my thoughts in here about why this is breaking and what we can do about it.  It looks like we're getting this error because we're trying to dump out filesystem information (specifically file paths) as JSON.  Unfortunately:

1. JSON can only represent UTF-8 strings
2. Filesystems can use any encoding for file names
3. Git must support storing these paths
4. Git doesn't store encoding information about the paths, they are just a list of bytes

This means we can't know for sure what encoding was used for the file path when it was stored in Git.  This particular case is a filename that can't be represented in UTF-8.  Since we're dumping this information to JSON, and JSON only supports UTF-8 strings, I think we could deal with this in either of the following manners:

1. Encode the filename to something else before emitting to JSON (like uuencode)
2. Force encode the filename to UTF-8 then scrub any "bad bytes"

The first solution may make the filenames unreadable, and will also force people to do an additional decode step when loading the JSON.  The second solution will maintain "readability" but will lose data when serializing.

Personally, I think the second solution is the best one.  But it means that information in JSON may not line up with information stored in Git.

**Comment by Alhadis** [comment]
I have similar issues with encoding and ASCII-8BIT when running `bundle exac rake` on OpenBSD. I get swamped with spurious errors unless I set `LANG=en_AU.UTF-8` in my environment before running. My theory is it has something to do with `charlock_holmes` [defaulting to 8-bit ASCII](https://github.com/brianmario/charlock_holmes/blob/fee4cad36c4481b5bba98e060e5af78f1cf0e11c/lib/charlock_holmes/encoding_detector.rb#L45-L66) for any encoding it doesn't recognise, which could be influenced by system libraries like ICU.

I don't know enough about the underlying Ruby libraries to know if there's a connection or not. 😕 I get the same breakage when running `script/licensed` too, not just `bundle`.
