### ISSUE TITLE
Feature Request and Bug: JSON searchable: false and .json still appears in search & how to change searchable

### ISSUE THREAD

**Issue by zekrom-vale** [github/linguist#4045]
https://github.com/github/linguist/blob/1bbcfa5683c203eb92a0d9571f63043791bea695/lib/linguist/languages.yml#L2036
The code in https://github.com/zekrom-vale/ZekromsKazdraRecipes/search?l=JSON shows .json files and not files that I have added, this appers to be incorect as it is set to `searchable: false`. 
 However, I would like to change it to `searchable: true` in [.gitattributes](https://github.com/zekrom-vale/ZekromsKazdraRecipes/blob/master/.gitattributes) but I see no way of doing it `JSON linguist-searchable=true` does not work and it is annoying me that most of my files are not showing up.

Sincerely,
> zekrom-vale

P.S. I see the JSON formatting in the files so it appears to associate the file type.

**Comment by lildude** [comment]
What's happening here has nothing to do with the `searchable` attribute but rather the file extensions you're using... these aren't associated with any language in Linguist so it's falling through to the classifier to guess and it's guessing Javascript, not JSON. The syntax highlighting is that for JavaScript too.

What I'm not sure about is why they're not appearing in the JavaScript search results, though I can say is not because of Linguist.

That said, both problems can be resolved by implementing a [language override](https://github.com/github/linguist#using-gitattributes) for all the extensions that contain JSON but aren't being identified as such.
