### ISSUE TITLE
Wrong Language C++

### ISSUE THREAD

**Issue by Impulse21** [github/linguist#4049]
## Problem Description
My code base is C++ and Cmake and the repo is being marked as objective-c. The repo in questions is [BeyondCrisisEngine](https://github.com/Impulse21/BeyondCrisisEngine)

### Last modified on:
2018-02-28

### Expected language:
C++

### Detected language:
Objective-C

**Comment by lildude** [comment]
This is happening because https://github.com/Impulse21/BeyondCrisisEngine/blob/master/include/BeyondCrisis/ThirdParty/Catch2/catch.h is far bigger than all other code combined at 425kb and header files are incredibly difficult to determine the language they belong to as they look very similar for all the C-family languages. As it is over 384kb it won't appear in the search results when you click the language after clicking the language bar.

As this appears to be a third party header file, the best thing to do is implement an [override marking it or the ThirdParty directory as vendored](https://github.com/github/linguist#vendored-code).

**Comment by Impulse21** [comment]
Hi lildude,

Thank you for the quick response. I have updated the .gitattributes file as such

`include/ThirdParty/Catch2/* linguist-vendored`

but I am still seeing it marked as objective-C. Is there something I am doing wrong here? Does it take time of the change to reflect on the github's website?

Note: I have also tried the following:
`include/ThirdParty/Catch2/catch.h linguist-vendored`
`include/ThirdParty/Catch2/catch.h linguist-language=Cpp`
`include/ThirdParty/Catch2/catch.h linguist-language=C++`

**Comment by pchaigno** [comment]
Your file is in `include/BeyondCrisis/ThirdParty/Catch2/` not `include/ThirdParty/Catch2/`. Could that be the cause?

**Comment by Impulse21** [comment]
Well that is embarrassing!! It is.

Thank you very much for the help!!!

**Comment by pchaigno** [comment]
You're welcome!
