### ISSUE TITLE
languages missing in repository statistics

### ISSUE THREAD

**Issue by MartinNeumannBeTSE** [github/linguist#4055]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I have 16 files in my repository. Most of them are Java code. All the languages are determinted correctly (apart from the fact that the INI files are Java properties files).
![statistics](https://user-images.githubusercontent.com/35294231/36899638-56a0063a-1e20-11e8-8d53-34005ed41767.PNG)
But for some reason linguist only counts the one Batch and the one Shell file.
![overview](https://user-images.githubusercontent.com/35294231/36899635-4f1dbb78-1e20-11e8-9910-33006ead6b6e.PNG)

### URL of the affected repository:
https://github.com/springfox/springfox-javadoc
### Last modified on:

2018/03/01
### Expected language:

mostly Java
### Detected language:

Shell and Batch file

**Comment by lildude** [comment]
This is expected. From the README (emphasis is mine)...

> Linguist starts by going through all the files in a repository and _excludes_ all files that it determines to be binary data, vendored code, generated code, **documentation**, or are defined as data (e.g. SQL) or prose (e.g. Markdown) languages, whilst taking into account any overrides.

"javadoc" is considered documentation and not code so excluded from the language stats by default here https://github.com/github/linguist/blob/2b65318a61c0dc712bfdf3fd25eebb112750e036/lib/linguist/documentation.yml#L10-L17

... it is however still correctly recognised as Java https://github.com/springfox/springfox-javadoc/search?l=Java

If you wish for them to count as code, you'll need to implement an [override](https://github.com/github/linguist#documentation).

As for the ini file, this is because `.properties` is classified as an INI file:

https://github.com/github/linguist/blob/2b65318a61c0dc712bfdf3fd25eebb112750e036/lib/linguist/languages.yml#L1918-L1925

... which is correct as the format isn't really any different. Once again, if you'd prefer this identified some other way, an override will do the trick.

So Linguist is behaving correctly.

**Comment by MartinNeumannBeTSE** [comment]
ah, so the reason is that the package name and therefore the folder name contains the word "javadoc" - I never would have guessed that 😄
