### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by afterether** [github/linguist#4063]
## Problem Description

Our repository is detect as JavaScript language while all the code is being written in Go. We don't have any .js files at all.

### URL of the affected repository:
https://github.com/afterether/ethbot
### Last modified on:
2018-03-10

### Expected language:
golang

### Detected language:
JavaScript

**Comment by lildude** [comment]
As the README states, Linguist calculates the language statistics based on the bytes of code in the repo and your repo appears to include Javascript as you can see here https://github.com/afterether/ethbot/search?l=javascript . However none of those files are counted as they’re either vendored or minified. The culprit is https://github.com/afterether/ethbot/blob/master/internal/jsre/deps/web3.js which on its own is 392kb which is larger than all your Go files combined.

This file appears to be mostly minified JavaScript except for the large amount of unminified JSON beyond the first line. It is this that is causing the file to be so large and be detected. As it is [larger than 384kb it is also not included in the search results](https://help.github.com/articles/searching-code/#considerations-for-code-search) either.

If you don’t want it to count towards your repo language stats, you’ll need to either minify the file completely or implement an override to ignore it.

**Comment by pchaigno** [comment]
@afterether Any reason why you removed the checkboxes at the beginning of the template? Everyone seems to do so now...

**Comment by afterether** [comment]
thanks guys
