### ISSUE TITLE
C classified as PHP?

### ISSUE THREAD

**Issue by kasper3** [github/linguist#4082]
At https://github.com/mono/libgdiplus, github is showing these stats:

![image](https://user-images.githubusercontent.com/33230602/38056427-12c3094c-32e5-11e8-89db-0684b5608859.png)

When i clicked on `PHP 13.4%`, the result was empty.

Perhaps it is due to this huge file: https://github.com/mono/libgdiplus/blob/8eee7ba8daaacbc5b7c6e2f1fad28c5e2f1ffceb/src/metafile.c, that has a PHP URL in a code comment on line 119?

**Comment by lildude** [comment]
> Perhaps it is due to this huge file: https://github.com/mono/libgdiplus/blob/8eee7ba8daaacbc5b7c6e2f1fad28c5e2f1ffceb/src/metafile.c, that has a PHP URL in a code comment on line 119?

Nope. It's because of https://github.com/mono/libgdiplus/blob/master/src/alpha-premul-table.inc, which for some reason the search itself is detecting as "POV-Ray SDL"  https://github.com/mono/libgdiplus/search?l=POV-Ray+SDL 🤔 

The `.inc` extension is associated with several languages, including PHP and "POV-Ray SDL", but sadly the heuristic doesn't cater for anything other than PHP and "POV-Ray SDL" (I'm not sure why) so this file is being incorrectly classified as such.

You'll need to implement a manual override to force the language until such time as this heuristic is fixed.

**Comment by kasper3** [comment]
If the idea is to fix the heuristic, does it has to be closed?

**Comment by pchaigno** [comment]
The heuristic rule is not broken per se; it's more that it could be improved with a case for C files. If you have the bandwidth, please go ahead and send us a pull request (it's a matter of finding the keywords and constructs that identify C in the context of `.inc`).

In any case, `.inc` files are often difficult to classify, so you should definitely opt for an override too.
