### ISSUE TITLE
Perl file containing :- misidentified as Prolog

### ISSUE THREAD

**Issue by tpenguinltg** [github/linguist#4094]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

The file [`gdown.pl`](https://github.com/circulosmeos/gdown.pl/blob/master/gdown.pl) is being misidentified as Prolog when it is clearly Perl with a perl shebang.

Shebang:
```perl
#!/usr/bin/env perl
```
https://github.com/circulosmeos/gdown.pl/blob/178fa1061c858da375c4d4c2452b9ecb84789139/gdown.pl#L1

The line that I suspect causes it to be identified as Prolog (note the `:-` in the `:-(`):
```perl
    die "Couldn't download the file :-(\n" if ($check==0);
```
https://github.com/circulosmeos/gdown.pl/blob/178fa1061c858da375c4d4c2452b9ecb84789139/gdown.pl#L57

We'll add a manual file type override for now, but this seems like an issue in the detector.

### URL of the affected repository:
https://github.com/circulosmeos/gdown.pl

### Last modified on:

2018-04-10

### Expected language:

Perl

### Detected language:

Prolog

**Comment by pchaigno** [comment]
Thanks for the neat report!

I have a pull request in the works which should solve this issue and #4090. Basically the shebang ends up not being used because it matches both Perl and Pod (both have the `perl` shebang registered). We could also improve [our heuristic for `.pl`](https://github.com/github/linguist/blob/51d3711faf3e416bcbeac9404a557f753d263746/lib/linguist/heuristics.rb#L363-L371), but I'd prefer to avoid making it too complex. Unless we go down the path of explicitly excluding `:-` when followed by a parenthesis...

**Comment by pchaigno** [comment]
#4099 was just merged, so this issue should be fixed with the next release of Linguist. There's usually a new release every couple weeks.

**Comment by tpenguinltg** [comment]
Seems like a reasonable approach. Thanks!
