### ISSUE TITLE
linguist not detect file in sub dir

### ISSUE THREAD

**Issue by ngohungphuc** [github/linguist#4102]
## Problem Description

So I have the resource folder contain all of my reference code and picture for project. I want to ignore all file in that Resource folder including all of sub dir.
Here is my .gitattributes file
`Resource/Archive/**/* linguist-vendored`

And when I check in language graph is still show all css file 
![chrome_2018-04-16_10-07-32](https://user-images.githubusercontent.com/13591213/38788477-0b97c20c-415e-11e8-90f5-98537a2b85d1.png)

### URL of the affected repository:
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/search?l=css
### Expected language:

C#, JS
### Detected language:

C#, CSS, JS

**Comment by ngohungphuc** [comment]
@lildude I still see the same graph showing file in the Resource folder . You can look at this link
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/search?l=css

**Comment by lildude** [comment]
What specifically should I be looking at?

As I mentioned above, you are looking at the search results. Linguist has _no_ influence on the search results. It only affects the language determination and stats.

If you don't want CSS to be included in your language stats bar, you need to mark the `src/AwesomeCMSCore/AwesomeCMSCore/wwwroot/frontend/css/` directory as vendored too.

**Comment by ngohungphuc** [comment]
@lildude I just though that search results will affect base on my gitattributes

**Comment by Alhadis** [comment]
@ngohungphuc A common misconception is that `.gitattributes` works recursively the way `.gitignore` does. That is, it's not enough to simply add a directory in your `.gitattributes` and have it apply to every single file in every single subdirectory. In order to do that, you need to use a "globstar" (a fancy word for two asterisks: `**`):

~~~gitattributes
/path/to/base/**/* name=value
~~~

Git has a tool that enables you to see which attributes are being applied to a file:

~~~shell
git check-attr --all /path/to/file
~~~

Run `man gitattributes` for more info.

**Comment by lildude** [comment]
> @lildude I just though that search results will affect base on my gitattributes

Nope. It definitely doesn't. There's no way of controlling the search results.

**Comment by ngohungphuc** [comment]
@lildude thank you for your confirmation
