### ISSUE TITLE
.h files are not C++

### ISSUE THREAD

**Issue by gdonald** [github/linguist#4103]
I added a .gitattributes file as Github Support suggested:

https://github.com/gdonald/cpama/blob/master/.gitattributes

But new .h files are still be classified wrong, here's one from yesterday at the bottom of the page:

https://github.com/gdonald/cpama/search?l=C%2B%2B

**Comment by pchaigno** [comment]
I checked by running Linguist locally that it correctly classifies that file and all other `.h` files. So it does look like an issue with Linguist.

@lildude You recently wrote that Linguist has no control over the search results, but it's still Linguist that identifies the language of files that is then displayed in the search results, right?

**Comment by lildude** [comment]
> So it does look like an issue with Linguist:

I think you're missing a "not" in there 😉

> @lildude You recently wrote that Linguist has no control over the search results, but it's still Linguist that identifies the language of files that is then displayed in the search results, right?

Yup. The problem here is the language for each file at the time the repo was initially pushed is added to the search index and it isn't updated when subsequent changes to the gitattributes file is made.  That's why the local analysis and stats bar are correct as this is all 100% Linguist.

I've tried to reindex the repo but this doesn't seem to have done the trick. I'm not 100% au fait with the search code, but I think pushing a change in any of those files now the override is in place will cause the search index to update the language.

The files are however correctly syntax highlighted as C (note the `type-c`) as per the override:

![screen shot 2018-04-17 at 14 21 47](https://user-images.githubusercontent.com/627280/38872247-b2b6e0d0-424a-11e8-8c6e-8b15a1e374b5.png)

**Comment by jweinst1** [comment]
@lildude one spot i see here for improvement is `struct` as a namespace/type modifier

```c
int find_part(int number, struct part *inventory, int *num_parts);
void insert(struct part *inventory, int *num_parts);
void search(struct part *inventory, int *num_parts);
void update(struct part *inventory, int *num_parts);
void print(struct part *inventory, int *num_parts);
``` 

Using `struct` as part of a type in a parameter or otherwise isn't valid in C++, do you think this would be a good thing to add in the Cregex in the other PR? or would this be too hard to capture in a regex?

**Comment by gdonald** [comment]
Keyword `struct` is valid in the formation of a function parameter in C++:

https://ideone.com/t68gEn

How about just looking at the Makefile where it says clang and not clang++, or gcc and not g++? 
 Looking at the definition of the CC in the Makefile is a solid way to know if it's a C project or not.

**Comment by gdonald** [comment]
Right, so make it possible to work on a not per-file basis :)

```
if file is .h
  look at Makefile
  if CC is clang or gcc
    file is C
  else if CC is clang++ or g++
    file is C++
else
  do the usual thing
```

**Comment by Alhadis** [comment]
I'm sure we can arrange a major architectural change to GitHub's entire repository-indexing system in 5 minutes, don't worry...

**Comment by pchaigno** [comment]
@gdonald If you think there's an easy fix for this that doesn't require major changes on GitHub's side, we can discuss it around a pull request though.

**Comment by gdonald** [comment]
An if statement is a major architecture change?  That's hilarious.
Fix it or don't guys.  I've wasted enough personal time on this already.

**Comment by kunal-mandalia** [comment]
Update for anyone looking for a solution:

Setting the env var `CC=gcc` in Makefile made Github understand my `.h` files were `C` so files are now correctly classified.

**Comment by pchaigno** [comment]
@kunal-mandalia That's unrelated.
