### ISSUE TITLE
Add a new feature to highlight a specific line(s).

### ISSUE THREAD

**Issue by olegburov** [github/linguist#4125]
It would be super handy if the Linguist support such a feature as highlight a specific line(s).

For example, I put a block of code that is highlighted using C# language syntax.

```c#
public class UserProfileModel
{
  public string EmailAddress { get; set; }
  public string Name { get; set; }
  public string ProfileImage { get; set; }
}
```

Now what I want is, to highlight the following line (with yellow color):

```c#
  public string ProfileImage { get; set; }
```
See here what I mean: https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-2.1#customize-the-details-page

This is supper handy when writing docs and describing what you need to add in existent code.

**Comment by Alhadis** [comment]
I've wanted this for a long time too. Don't worry. =)

Have you submitted it as a feature request to [GitHub support](https://github.com/contact)? If not, you should. Linguist doesn't handle the literal code highlighting: this issue might be better filed at [`github/markup`](https://github.com/github/markup) instead of here.

@olegburov It still sucks, I know, but if you want to draw attention to a specific line, a crude hack is to use `~~~diff` with the respective line prefixed with a `+`:

~~~diff
 public class UserProfileModel
 {
   public string EmailAddress { get; set; }
   public string Name { get; set; }
+   public string ProfileImage { get; set; }
 }
~~~

It's obviously pretty horrible. :(

**Comment by olegburov** [comment]
@Alhadis Thanks for the trick with ~~~diff.

I filed the issue at GitHub org https://github.com/github/markup/issues/1197
