### ISSUE TITLE
Add `jsonc` (json with comments)

### ISSUE THREAD

**Issue by Haroenv** [github/linguist#4153]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Some files like VSCode settings, typescript.json, are json, but allow comments (similar to json5, but it doesn't allow any of the other features). 

Up until now I marked those as `json5` for correct highlighting, but recently prettier started formatting `json5` in markdown as the "simplest version of json5", which for example included taking the quotes off the keys when they aren't necessary. This will give an invalid JSON with comments in the end. However there's not a correctly highlighting on GitHub for `jsonc`. So I'm suggesting it here.

### URL of the affected repository:

https://github.com/prettier/prettier/issues/4611#issuecomment-393461346

### Last modified on:
2018-05-31

**Comment by Alhadis** [comment]
@lildude I think it's worth adding a separate language entry for JSON with comments, because `jsonc` isn't an isolated case. ESLint [supports comments](https://eslint.org/docs/user-guide/configuring#comments-in-configuration-files) in `.eslintrc.json` files, and the entire reason we [added Sublime configs](https://github.com/github/linguist/pull/3268) as a language was a workaround for how comments were being highlighted as errors.

Either we differentiate between "JSON" and "JSON with comments", or we switch to a more lenient grammar for highlighting JSON files (I'd be happy to hack one together, it'd barely take 10-25 minutes).

**Comment by lildude** [comment]
@Alhadis Go for it. Take your pick which you'd prefer to implement.

**Comment by Alhadis** [comment]
On it.

Gonna add it as "JSON with comments", because affecting the highlighting of existing JSON files could be hazardous for code review (an invalid JSON file could slip past a maintainer's notice if a less experienced contributor put a JS comment in JSON code, for example...)

**Comment by Alhadis** [comment]
2.5 hours later, I *still* can't get Bundler co-operating with my system. :sweat: Either I suck or Ruby seriously hates my guts.
