### ISSUE TITLE
No language statistics shown for repository

### ISSUE THREAD

**Issue by jackharrisonsherlock** [github/linguist#4194]
Linguist doesn't show any statistics for my repo 
https://github.com/jackharrisonsherlock/common

I've checked the command line but it doesn't return anything either?
![2018-07-12 at 9 04 06 pm](https://user-images.githubusercontent.com/23329559/42623510-2690341a-8617-11e8-98d4-a73fd1960d6a.png)

**Comment by pchaigno** [comment]
Any reason the template disappeared?

Linguist only counts files detected as having a programming and prose language minus any documentation, vendored, or generated file. In your case, readme.md is detected as Markdown, itself [classified as prose by Linguist](https://github.com/github/linguist/blob/1dc8e28f0f33d81001e58295fb2f0368d519f551/lib/linguist/languages.yml#L2696). READMEs are considered documentation though, so it's not displayed in statistics.

**Comment by lildude** [comment]
@pchaigno too quick for me again 😆 

It's also because you've only got one file in your repo that could be considered code and it's not clear to Linguist what language it should be as it's not using anything it could use to even start guessing.

You'll need to either, change the extension to something like `.zsh` or `.sh`, add a modeline to the file or a .gitignore override. I've demonstrated adding a modeline in a fork of your repo at https://github.com/lildude/common/ (the magic commit - https://github.com/lildude/common/commit/49077d9f1f74e62d7b696796bdc534662a5ad30f)
