### ISSUE TITLE
Pascal source misidentified as OpenEdge ABL

### ISSUE THREAD

**Issue by patrick-brian-mooney** [github/linguist#4216]
I recently pushed code I've been working on in an obsolete operating system to a new repository, patrick-brian-mooney/dump-resources (it's public). The code is designed to run under pre-OSX Macs and is written in Pascal. It's identified by linguist as OpenEdge ABL, which is not correct.

I wonder whether this problem might be in part because the source files use classic Mac OS line endings (CR instead of CR/LF or just LF)? 

## Preliminary Steps

Please confirm you have...
- [x ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:

https://github.com/patrick-brian-mooney/dump-resources

### Last modified on:
2018-08-02

### Expected language:
Pascal

### Detected language:
OpenEdge ABL

**Comment by lildude** [comment]
> I wonder whether this problem might be in part because the source files use classic Mac OS line endings (CR instead of CR/LF or just LF)?

Nope. It's nothing fancy like that. It's simply because the `.p` extension is _only_ associated with OpenEdge ABL:

https://github.com/github/linguist/blob/ed44c0b86d317b753c607742b137dce9594bed97/lib/linguist/languages.yml#L3192-L3204

You can have your files identified as Pascal by implementing a language override for the `.p` extension, or rename your files to use one of the extensions associated with Pascal:

https://github.com/github/linguist/blob/ed44c0b86d317b753c607742b137dce9594bed97/lib/linguist/languages.yml#L3405-L3421

**Comment by lildude** [comment]
I see you've implemented an override so I'm closing this issue.
