### ISSUE TITLE
Add gitignore as a supported file type/language tag (with syntax highlighting set to as atom/language-shellscript)

### ISSUE THREAD

**Issue by binki** [github/linguist#4225]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

Regarding overrides, I think gitignore should just be a first-class alias in linguist. Also, `.gitignore` files should be highlighted correctly without requiring any configuration.

## Problem Description

If I try to use `gitignore` as a language tag, I do not get any syntax highlighting. Example: https://gist.github.com/binki/8e9146122509a2bd1375c7b961e810ab where no syntax highlighting is shown when explicitly setting `lang=gitignore` and https://gist.github.com/binki/7e0710d92863276ba39091cb299725bd which shows that `.gitignore` is being detected as “text”.

I think linguist should provide at least an alias of `gitignore` and perhap just use the `shell` syntax highlighting for it.

### URL of the affected repository:

https://gist.github.com/binki/8e9146122509a2bd1375c7b961e810ab
https://gist.github.com/binki/7e0710d92863276ba39091cb299725bd
https://github.com/binki/promise-delay-ts/blob/1b1fc0c311e3442ff8050b95e66c1d1a8850ee98/.gitignore

### Last modified on:
2018-08-07

### Expected language:
`gitignore` with syntax highlighting configured to use `atom/language-shellscript` or `shell`.

### Detected language:
`text`

**Comment by pchaigno** [comment]
> If I try to use `gitignore` as a language tag, I do not get any syntax highlighting.

What's wrong with using `shell` as the language tag if you want your `.gitignore` file to be highlighted as Shell code?

In my opinion, detecting `.gitignore` files as Shell is a bit of a no-go because it would also affect language statistics, and most users wouldn't understand why they get a small percentage (or 100% if they have no programming files) of Shell code detected in their repositories for a configuration file.

**Comment by binki** [comment]
@pchaigno
> > If I try to use `gitignore` as a language tag, I do not get any syntax highlighting.
>
> What's wrong with using `shell` as the language tag if you want your `.gitignore` file to be highlighted as Shell code?

I think you answered your own question. See:

> In my opinion, detecting `.gitignore` files as Shell is a bit of a no-go because it would also affect language statistics, and most users wouldn't understand why they get a small percentage (or 100% if they have no programming files) of Shell code detected in their repositories for a configuration file.

gitignore should be a first class supported language tag and `atom/language-shellscript` should just be the syntax highligher for the gitignore language.

Additionally, one shouldn’t have to use `.gitattributes` to hackily set their `.gitignore` to `shell` just to get syntax highlighting to work when looking at their `.gitignore` in their own repository. It may be an acceptible workaround for fenced code blocks in markdown in the meantime, though.

**Comment by pchaigno** [comment]
Oh I see, my bad. So you want to add support for gitignore as a language and use the Shell grammar to highlight it? I think that would be ok. Do you want to submit a pull request?

**Comment by binki** [comment]
No problem!

I can try submitting a PR. It might take me a bit to get around to it, though.

**Comment by binki** [comment]
Is it best to cover all of [those various files](https://github.com/github/linguist/issues/4225#issuecomment-411096432) in this one issue or should they each be separate issues?

**Comment by Alhadis** [comment]
... errr , did I just reply to your last comnent by writing over the top of it?  <img src="https://e.vampirefreaks.com/emotes/disturbing.gif"/>

God *damn* i hate it when that happens. <img src="https://e.vampirefreaks.com/emotes/banghead.gif" alt=""/>

**Comment by Alhadis** [comment]
COME OUT FROM HIDING, i CAN'T SEE YOU. <img src="https://e.vampirefreaks.com/emotes/whine.gif"> I feel I'm in a thread with poltergeists at the moment. :D

**Comment by pchaigno** [comment]
@binki To give you a bit of context: as co-maintainers we can edit everybody's posts on the repository. I honestly think this is not something we should be able to do, but anyways. It happens to be handy to copy rendered code from someone you want to quote, such as your earlier link. @Alhadis, being very tired, apparently was in the process of doing so, but wrote in your comment instead of creating his own... I've always fear that would happen to me, but looks like @Alhadis is even more tired than I am at the moment.

@Alhadis You need to sleep.

**Comment by binki** [comment]
@pchaigno I figured something like that was happening. I wish GitHub had a readonly “raw markup” view for comments to make block quoting easier myself—it’s unfair how I have to manually rebuild all the markdown after copy/paste just because I’m not a contributer! :-p

**Comment by pchaigno** [comment]
Closing this one. @binki Feel free to send a pull request (even if it doesn't support all file types at first) when you have the bandwidth.

**Comment by ianfixes** [comment]
I see that this issue was closed, but I don't see the resolution.  Has this been added?  Is it `WONTFIX`?  If it's a feature that would be added but hasn't yet, where is that being tracked?

**Comment by Alhadis** [comment]
@ianfixes Support for `.gitignore` was added in #4343, albeit under the name `Ignore list` (since the language entry was used for several formats with similar or identical syntax to `.gitignore` files).

**Comment by ianfixes** [comment]
Testing 123, via https://webapps.stackexchange.com/q/119452

```Ignore list
# Common editor swap files
*.swp
*~
*\#*
```

Nice!

**Comment by Alhadis** [comment]
> This apparently has been added to linguist: https://github.com/github/linguist/pull/4343
>
> The tag you should use is Ignore list, as in

Two slight corrections:

1. The tag should be `ignore-list` (or simply `gitignore`, which is supported as an alias
2. You can replace the word _"apparently"_ with _"definitely"_. 😉

Note that fenced code-blocks must be tagged with a single-word identifier; i.e., something like `Ignore list` should be replaced with `ignore-list`. Note that GitHub performs some magic in order to pair a code-bock's tag with a language entry.
