### ISSUE TITLE
C++ repo is detected as Perl, but all files are classifed correctly

### ISSUE THREAD

**Issue by glumpo** [github/linguist#4244]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I have never commited  any perl files in this repo, but github shows, there are 99.9% of perl code. However, no one file is beeing classified as perl file, every file is classified correctly, so I can`t understand, why 99.9% of them are written in perl.

### URL of the affected repository:
https://github.com/glumpo/kmp
### Last modified on:
2018-08-18

### Expected language:
C++

### Detected:
Perl

**Comment by lildude** [comment]
This is happening because 99.9% of your repo, by bytes of code, are the three '.t' files under `tests/tests`. 

They total 5.99 MB with each file being considerably larger than the [384 KB limit for code search indexing](https://help.github.com/articles/searching-code/#considerations-for-code-search), hence they don't appear when you click "Perl" in the language bar.

So why are these being detected as Perl? Because several languages use the `.t` extension, one of which is Perl (none are C++), and things are falling through the heuristic to the naïve Bayesian classifier and it's taking a guess at it based on the content of these files. 

These files look to contain nothing but a lot of groups of numbers and appear to have been generated by the `test_generator.py` script so you probably don't want them included in your stats anyway. I'd question if you really need these files committed to your repo in the first place as they're easily regenerated, but if you really want to keep them, the best thing to do is [mark them as generated](https://github.com/github/linguist#generated-code).

**Comment by glumpo** [comment]
Thanks, I got it. Did not know about `.t` extension for Perl files. I marked them as generated and now detected language is C++. Sorry for wrong report.
