### ISSUE TITLE
classified is right, but the type is not right

### ISSUE THREAD

**Issue by fi3ework** [github/linguist#4254]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Hi, sorry to bother. But there's something strange with my code type.
The result is 44.4% code are JS (15 files), 44.1% are TS (83 files), but actually most of my code are written in TSX (The ratio may has been changed a bit cause I'm working on it).  
Here's the result that I test on local

![image](https://user-images.githubusercontent.com/12322740/44712885-752dc780-aae4-11e8-881c-36429d4affba.png)

### URL of the affected repository:
https://github.com/fi3ework/react-cloud-music
### Last modified on:

2018-08-28
### Expected language:

TypeScript
### Detected language:

JavaScript

**Comment by RobQuistNL** [comment]
The percentages are based on lines if I'm correct - not on file count.

Looking at your repo you have quite some big .js files, and a lot of smaller TSX files - which makes the count correct in my opinion.

**Comment by fi3ework** [comment]
Thanks for replying. I know the percentages is based on file size (or line number totally) instead of file count. I just wanna say most of my code are written in TS, and my line count (file size) of TSX is more than JS...

**Comment by RobQuistNL** [comment]
Well, there are a few big javascript files around:

https://github.com/fi3ework/react-cloud-music/tree/master/scripts
https://github.com/fi3ework/react-cloud-music/tree/master/config

If you match those against your TSX files I think the outcome of 40% TSX in the complete repo might be good, since the rest is mainly javascript

**Comment by lildude** [comment]
@RobQuistNL is spot on and you can confirm this yourself by adding the `--breakdown` flag to your local Linguist command. The two largest Javascript files, and by a long way are:

```
 20K	./config/webpack.config.prod.js
 16K	./config/webpack.config.dev.js
```

Your largest `.tsx` file is only 8K.

As for how it's measured, the README to the rescue (emphasis is mine):

> The percentages are calculated based on the **bytes of code** for each language as reported by the List Languages API.

**Comment by fi3ework** [comment]
Yes, both @RobQuistNL and @lildude are right 😄. I just use a plugin to count the lines of different languages. TS almost has 2265 lines and JS has 1373 lines. However, the average letter count of each line in JS is much more than TS (because of the comment) so the file size of JS and TS is nearly (I also ensured). 
So there isn't any wrong with my code statistical and I may add a .gitattribute later just as @Alhadis said. But I think there could be a  balance point between line count and file size count to deal with the situation like this 😆.

**Comment by RobQuistNL** [comment]
Disagree on the "balance point" since the only good way to measure size is bytes of code, as it currently is. Do agree with Alhadis to a certain degree - because where would you draw the line? Do makefiles for example count as vendored? 

I just think in the case of very small packages, you're going to end up with more configuration than code, and the count is still correct in that case.

**Comment by Alhadis** [comment]
@RobQuistNL That's an interesting argument, because Makefiles and Webpack are at two opposite spectrums in terms of the complexity-versus-efficiency trade-off. Launching two (!) local HTTP servers to develop locally involves a beastly amount of boilerplate and copy+pasta. A Makefile, OTOH, is direct and simple. One line is roughly one operation, broadly speaking. Webpack is something like *10* lines and a convoluted web of dependencies... and yes, each of those have their own configs as well.

It's no wonder that the most popular interface for Webpack remains [`create-react-app`](https://github.com/facebook/create-react-app), which essentially generates the configuration for you...

**Comment by RobQuistNL** [comment]
And I'm sure this is only going to get worse with the time, hehe.
