### ISSUE TITLE
95% Makefile?

### ISSUE THREAD

**Issue by sharpaper** [github/linguist#4320]
https://github.com/KevEdwards/CrazeeRiderBBC

**Comment by lildude** [comment]
This is because of your use of the `.mak` extension which is only associated with Makefiles: 
https://github.com/github/linguist/blob/58ef7278579a6dca0bc16729836833e19d6d28cd/lib/linguist/languages.yml#L2725-L2735

You'll need to use an override to set the correct language. We'll also consider a pull request to help identify the correct language in future.

**Comment by lildude** [comment]
Off the top of my head (on mobile right now) I'm not sure why the other files aren't being associated with any language.

**Comment by Alhadis** [comment]
It's because the repository's source files are using `.6502` as a file extension, which we don't currently associate with any language.

@sharpaper I suggest sending a pull-request to that repository's author to mark the files as assembly if you feel it should be corrected.
