### ISSUE TITLE
Wrong language in my repository

### ISSUE THREAD

**Issue by leakkari** [github/linguist#4337]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

In my DesignProject repo, the whole project is done in Java and GitHub keeps detecting it as html.
### URL of the affected repository:
https://github.com/leakkari/DesignProject
### Last modified on:

2018-11-27 
### Expected language:

JAVA
### Detected language:

HTML

**Comment by lildude** [comment]
This is happening because your repo has a lot of HTML files in it - from a quick look, almost ever directory has at least one - and their total combined size far outweighs the Java:

HTML 770 KB
Java 256 KB
CSS 25.1 KB
JavaScript 1.62 KB

As a result, GitHub is marking the most prominant language in your repo as HTML as it cleasrly is.
