### ISSUE TITLE
Who owns this repo?

### ISSUE THREAD

**Issue by asheren** [github/linguist#4338]
Hello! I have an update on textmate grammars that may affect how issues are resolved in this repo but i'm not sure who to tell about it? Which team owns this repo? Who is the best person to loop in?

**Comment by kytrinyx** [comment]
On a similar note, would the team who owns this repo also own the Languages API (which exposes this repo via the REST API) by any chance?

**Comment by lildude** [comment]
Well, that's an interesting question @asheren. Technically speaking, @github/sis "owns" Linguist, but that's only a recent development - it spent a long time in limbo without a real "owner". I've been the primary GitHub maintainer since @arfon left and I'm not part of that team 😄 (I'm part of the for-business team).

If there's any sort of breaking change to grammars, here/me is probably a good place to start. Here has the advantage that @Alhadis and @pchaigno, the two most active outside maintainers, can see the info too.

@kytrinyx I have no idea who own the Languages API. I've never touched it directly. I believe it uses info pulled from Linguist, but that's about as far as my knowledge extends on that side of things.

It's late here (🇬🇧) but am happy to chat on Slack tomorrow if you like.

**Comment by pchaigno** [comment]
What's @github/sis?

**Comment by josedab** [comment]
@pchaigno It is the "Software Intelligence Systems" team. I believe the team 'owns' linguist as it works closely with ML team helping them moving work to production and they need to be aware if major issues happen. Having said that, I think @lildude is completely right on this one, he is the "real owner" at least from the knowledge point of view ;)

> I've been the primary GitHub maintainer since @arfon left and I'm not part of that team 😄 (I'm part of the for-business team).
@lildude Yep, not the best scenario I can see. Feel free to raise this to the SIS team through an [issue](https://github.com/github/sis) and we can figure something out. Or drop by #sis channel on Slack and hopefully someone can help more :)
