### ISSUE TITLE
Supercollider being marked as Scala

### ISSUE THREAD

**Issue by khoin** [github/linguist#4352]
## Problem Description
SuperCollider being marked as Scala. This is thought to have been resolved by #1091 .
Check the repository below, unused.sc is thought to be Scala, even though there's `var` in it.

### URL of the affected repository:
https://github.com/khoin/dx463-final

### Expected language:
SuperCollider

### Detected language:
Scala

**Comment by lildude** [comment]
This is happening because that file doesn't match any of these regular expressions https://github.com/github/linguist/blob/fa493000a594f5fbd457bbd473ce791d95b227cc/lib/linguist/heuristics.yml#L347-L352

... so is falling through to the classifier and it's making a guess based on the samples we have for both languages and only just getting it wrong.

If you know of a good way to improve the heuristic, please feel free to submit a PR.

**Comment by khoin** [comment]
I will try and analyze some of the code and see if I can extend the Regex
this weekend.
As far as I see it now, it looks like the Regex is written as if it expect
SuperCollider class files only, not script files.

Stay tuned.

**Comment by pchaigno** [comment]
@khoin Did you get a chance to look into this? It really helps us if you find a way to improve the heuristic.

**Comment by khoin** [comment]
I'm quite filled right now with schedule so I haven't gotten a chance for
it.

I saw another repository also having the same problem. So I'll keep that in
mind when I get a chance to look around
https://github.com/ambisonictoolkit/atk-sc3
