### ISSUE TITLE
MSSQL file detected as PLpgSQL

### ISSUE THREAD

**Issue by mooseous** [github/linguist#4386]
## Problem Description
This file should be detected as SQL just like my others. It's a MSSQL syntax file with the sql extension. It seems only stored procedures are being identified incorrectly.

### URL of the affected repository:
It's private. But [here's the gist](https://gist.github.com/mooseous/f03de680679031640b6e3e88da865ab0).

### Last modified on: 
12/19/2019

### Expected language:
SQL

### Detected language:
PLpgSQL

**Comment by pchaigno** [comment]
It looks like this is happening because of an incorrect assumption in [the regex we use for PLpgSQL](https://github.com/github/linguist/blob/58193319b3a1daa8fae0fec897029137a958568e/lib/linguist/heuristics.yml#L362). `BEGIN TRANSACTION;`  is [not only a PostgreSQL instruction](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/begin-transaction-transact-sql?view=sql-server-2017). We should probably remove the `TRANSACTION` part.

/cc @Shoelace who added that PLpgSQL heuristic rule in #2082.

**Comment by Shoelace** [comment]
nice.. well there you go.. 4 years later and things are still improving..
I'm wasn't overly versed on pgPLSQL and MSSQL at the time so it doesn't surprise me that the heuristics require a little tuning.

a quick googling suggests that 'BEGIN TRY' and 'BEGIN CATCH' might be T-SQL specific   and so might make for a good start to a t-sql specific identification in future

**Comment by Shoelace** [comment]
sqlserver... see https://searchsqlserver.techtarget.com/definition/T-SQL for a good definition

> T-SQL (Transact-SQL) is a set of programming extensions from Sybase and Microsoft that add several features to the Structured Query Language (SQL), including transaction control, exception and error handling, row processing and declared variables.

> All applications that communicate with SQL Server do so by sending T-SQL statements to the server. T-SQL queries include the SELECT statement, selecting columns, labeling output columns, restricting rows and modifying a search condition.
