### ISSUE TITLE
Gnuplot files with .p extension classified as OpenEdge ABL

### ISSUE THREAD

**Issue by smola** [github/linguist#4388]
## Problem Description
Some repositories use the `.p` extension for Gnuplot. Linguist classifies these files as OpenEdge ABL.

### URL of the affected repository:
Test search: https://github.com/search?p=90&q=extension%3Ap+plot+set+output&type=Code

### Last modified on:
2019-01-21

### Expected language:
Gnuplot

### Detected language:
OpenEdge ABL

**Comment by lildude** [comment]
I think this is because the `.p` extension is only associated with the OpenEdge ABL language though I'm not sure why there are a few files that are successfully identified as GNUplot - I've not dug into it yet.

Adding the `.p` extension to GNUplot with a heuristic to differentiate it from OpenEdge ABL should "fix" this.

**Comment by smola** [comment]
@lildude Could you reopen the issue / remove the `Stale` label? I filed an updated PR at https://github.com/github/linguist/issues/4388 Thanks!
