### ISSUE TITLE
Question: How to retain syntax colors without being included in language stats?

### ISSUE THREAD

**Issue by Leedehai** [github/linguist#4390]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Hi this is a question, not an issue, but I don't know what the appropriate venue is..

I want some of my code be colored but **not included** in the language stats. In fact, these files are *not* vendor code, documentation, or generated. They are true code written by me, but I don't want them to be included in the stats anyway. Still, I want to have them colored.

How should I do it? Is the below ok?
```
*.css2 linguist-language=CSS
*.css2 linguist-detectable=false
```
It seems not working.. they don't appear in stats, sure, but are not colored.

**Comment by pchaigno** [comment]
I think you want to use `linguist-vendored`:

    *.css2 linguist-language=CSS
    *.css2 linguist-vendored

**Comment by Alhadis** [comment]
To be honest, there's no good reason `linguist-detectable=false` *shouldn't* work...

**Comment by Leedehai** [comment]
@Alhadis hi it worked - it seems it took time for the low-priority job to complete. Thanks! The issue may be closed.

**Comment by Leedehai** [comment]
> I think you want to use `linguist-vendored`:
> 
> ```
> *.css2 linguist-language=CSS

**Comment by Leedehai** [comment]
@pchaigno 
*these files are not vendor code, documentation, or generated* (please see the original description)

**Comment by pchaigno** [comment]
> @pchaigno
these files are not vendor code, documentation, or generated (please see the original description)

I've seen it. But whatever these files are, what you want is also the exact result from marking them vendored in Linguist. Marking them vendored also doesn't have any effect outside of Linguist. I thought I'd mention it since I wasn't sure you named them `.css2` on purpose or just to exclude them from statistics. If it was just to exclude them from statistics, then you wouldn't need to do that with `linguist-vendored`.
