### ISSUE TITLE
Forth .fs files misclassified as Renderscript

### ISSUE THREAD

**Issue by TG9541** [github/linguist#4398]
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

The statistics for Forth .fs files in my repository is either Renderscript (language statistics bar) or shown as Filterscript (statistics page). Indeed no Renderscript files are listed there.

I added a `.gitattributes` file with the following line:
```
*.fs linguist-language=Forth
```
Up to now there hasn't been an update (but maybe you'd like to use the data for training even if the overwrite works).

### URL of the affected repository:

https://github.com/TG9541/W1209

There is one more of my repositories where linguist classifies some .fs files as Forth and others as Filterscripts:

https://github.com/TG9541/stm8ef

### Last modified on:

2019-02-02
### Expected language:

Forth
### Detected language:

Renderscript (statistics bar) or Filterscript (inconsistent statistics page)

**Comment by lildude** [comment]
> The statistics for Forth .fs files in my repository is either Renderscript (language statistics bar) or shown as Filterscript (statistics page). Indeed no Renderscript files are listed there.

The "Renderscript" identification is because these files are being identified as "Filterscript" and it is grouped under "Renderscript":

https://github.com/github/linguist/blob/77e10e89801c2a50925758ca0ddfbb172fe6c475/lib/linguist/languages.yml#L1380-L1384

The reason the files are being identified as Filterscript is because their content matches the heuristic used to identified `.fs` for Filterscript and not Forth:

https://github.com/github/linguist/blob/77e10e89801c2a50925758ca0ddfbb172fe6c475/lib/linguist/heuristics.yml#L147-L156

All five files at https://github.com/TG9541/stm8ef/search?l=Filterscript will match Filterscript and not Forth because the files contain lines that match the `#include|#pragma\s+(rs|version)|__attribute__` regex but not `^(: |new-device)`.

> Update: the override did work for the statistics bar but the statistics page still shows "Filterscript".

Yeah, this is the caching performed by the code search (the statistics page is really a search page) and is independent of Linguist. IIRC this should be updated when you make a change to one or more of files identified by the respective language (modifying `.gitattributes` doesn't currently cause a reindex). If this isn't happening, I recommend contacting GitHub support.

**Comment by TG9541** [comment]
@lildude thanks a lot for the analysis :-)

Forth has a lot of variability and it's hard to detect with a simple regexp. I'll consider reformatting my code to make it match the existing regexp.

**Comment by pchaigno** [comment]
As you've certainly read in the README, you can also use overrides to tell Linguist how it should classify your files.
