### ISSUE TITLE
Incorrect detection of my repository's programming language

### ISSUE THREAD

**Issue by maxjiang93** [github/linguist#4424]
Here's our repository:
https://github.com/maxjiang93/DDSL

It's detected as an HTML repo, though it's mostly python+bash, and does not include a single html file in it.

**Comment by Alhadis** [comment]
The issue temple which you ignored (and even deleted) had a checklist and links to explanations which would probably have helped you solve your issue.

Please fill it out.

**Comment by maxjiang93** [comment]
Sorry about that... I do notice that my repo was detected as html because there was one huge html file, despite dozens of shorter python files. I guess I would suggest weighing the result not only by number of lines of code of each language, but also on the number of files?

Again sorry for ignoring the instructions... my bad.

**Comment by Alhadis** [comment]
That's okay. 👍

> I guess I would suggest weighing the result not only by number of lines of code of each language, but also on the number of files?

Well, that wouldn't work if an author had one giant file and lots of small, short test scripts. Understand that Linguist's method of classifying repositories isn't going to please everyone — which is why we offer users [an override](https://github.com/github/linguist/blob/master/README.md#overrides) as a way of correcting their project's classification.

A link to the override docs was included in the checklist, BTW.

**Comment by Alhadis** [comment]
I see you've [found and fixed this](https://github.com/maxjiang93/DDSL/commit/e43b5e069ab60757af471a7b72eebcad883c7857), so I'm marking this issue resolved. Don't hesitate to open a new issue if you're stuck and following the template's checklist  hasn't helped you. 👍

**Comment by maxjiang93** [comment]
Yeah thanks I fixed the issues ;)
