### ISSUE TITLE
.pyx codes with -> typing doesn't render correctly

### ISSUE THREAD

**Issue by initbar** [github/linguist#4438]
`.py*` renders `-> (default primitives)` correctly, but doesn't seem to render custom types from `typing` module. And based on [PEP404](https://www.python.org/dev/peps/pep-0484/) standard, the return type can be of an implemented type.

Example:

![screenshot](https://user-images.githubusercontent.com/12630151/53496686-8b571900-3a70-11e9-9f7f-f3036427465b.png)

## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### URL of the affected repository:
https://github.com/initbar/castar/blob/master/castar/grid.pyx

### Expected language:
Python, Cython

### Detected language:
Python (correct)

**Comment by lildude** [comment]
I'm not 100% sure what you're reporting here. Are you reporting a problem with the syntax highlighting of that particular file or about the fact you repo is showing a 100% Python?

If the former, you'll need to contact the grammar maintainer as [stated in the README](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file).

If the latter, this is expected because Cython is grouped with Python:

https://github.com/github/linguist/blob/e4560984058b4726010ca4b8f03ed9d0f8f464db/lib/linguist/languages.yml#L964-L967

... and as such appears as Python and not Cython.  The syntax highlighting is however cython:

![screenie](https://user-images.githubusercontent.com/627280/53498119-95dbd780-3a9d-11e9-965b-35dbb7073fe5.png)

**Comment by initbar** [comment]
Problem with syntax highlighting :) I'll close this issue and ping Magic Python for grammar updates. Thank you!
