### ISSUE TITLE
.gitattributes not working

### ISSUE THREAD

**Issue by ubalklen** [github/linguist#4454]
Linguist seems not to be working on my repo. I tried to override it with a very simple [.gitattributes](https://github.com/ubalklen/where-is-the-key/blob/master/.gitattributes) file, but it had no effect.

### URL of the affected repository
https://github.com/ubalklen/where-is-the-key

### Last modified on:
Today

### Expected language:
Python

### Detected language:
None

**Comment by lildude** [comment]
This isn't a problem with your `.gitattributes` having no effect... the problem is your repo tree size is heeeeawg so Linguist is silently returning without performing the analysis here: https://github.com/github/linguist/blob/0dc5bf140eb89457ddff64afeddb3ae4ff2a29a2/lib/linguist/repository.rb#L132-L135

If we take a look at your repo in `git-sizer` we can see a bit more:

```console
$ git clone ubalklen/where-is-the-key
[... output removed for brevity - it took a really long time to clone too 😉 ...]
$ cd where-is-the-key
$ git-sizer
Processing blobs: 243419   <---- HERE
Processing trees: 80
Processing commits: 18
Matching commits to trees: 18
Processing annotated tags: 0
Processing references: 3
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Biggest objects              |           |                                |
| * Trees                      |           |                                |
|   * Maximum entries      [1] |  17.2 k   | ******                         |  <---- AND HERE
| * Blobs                      |           |                                |
|   * Maximum size         [2] |  11.2 MiB | *                              |
|                              |           |                                |
| Biggest checkouts            |           |                                |
| * Maximum path length    [3] |   109 B   | *                              |
| * Number of files        [4] |   243 k   | ****                           |

[1]  07caf56c4d37e83e1a2092f251ba9e9957f57a64 (refs/heads/master:data/3-slices/augmented)
[2]  4f984faeee8f8b2b9653fe08132cce4ad27d9bda (refs/heads/master:data/2-no-panels/5-12-k-2173-461.jpg)
[3]  24f736cbcc81df09881ca82125eaa6d83cce1003 (refs/heads/master^{tree})
[4]  03183894bd39f15e41f0a133d0436e8ffc936f14 (refs/remotes/origin/HEAD^{tree})
$
```

I've highlighted to two points of interest. The second is the most pertinent. See https://github.blog/2018-03-05-measuring-the-many-sizes-of-a-git-repository/ for more details.

Essentially, storing all the `data` within the repository is what is preventing the analysis - it is also what makes cloning this repo take so long. Take a look at the [`git-sizer` project page](https://github.com/github/git-sizer/) for tips on how you can rectify this.

**Comment by ubalklen** [comment]
Thank you for your thoughtful analysis, @lildude 
Now it's up to me to decide if it's worth rearranging my repo to get the language right.
