### ISSUE TITLE
dont touch my repository

### ISSUE THREAD

**Issue by G0ncharovAA** [github/linguist#4492]
Actually, there are two issues:

first, language of my project was incorrect determined as Java instead of Kotlin.

second, this is mine project, so only i should determine its language. Add button "change language" in the settings menu.

**Comment by jaredlll08** [comment]
You can determine your own language, it just may not exactly be what you want,
https://github.com/github/linguist#using-gitattributes

Doing it this way will make the .java files be recognized as .kt files, but it will also try applying the .kt formatter to the .java files, not sure how well that one works.

Also the reason your repo was marked as Java is probably because you have a [single java file](https://github.com/G0ncharovAA/ForSuccess/blob/74fb91a677277827ee269a45db4631e466713dd8/app/src/main/java/ru/gonchar17narod/forsuccess/mvp/models/AppleResults.java) that has more lines than the rest of your kotlin files combined, so Github sees a majority of Java, and classifies it as such.

![image](https://user-images.githubusercontent.com/5553605/55991893-890cef00-5cab-11e9-8e8a-a734ba4ab908.png)

**Comment by RobQuistNL** [comment]
dont use github

this site is ours :P

**Comment by pchaigno** [comment]
Thanks @jaredlll08 for answering!

I think we can close this issue. @G0ncharovAA If you still have questions, please open an issue and fill the template.
