### ISSUE TITLE
ReasonML syntax highlighting highlights remaining code as comment

### ISSUE THREAD

**Issue by Risto-Stevcev** [github/linguist#4533]
Here on these lines it looks like the reasonml syntax highlighting fails to close the comments and continues highlighting the rest of the doc as a comment:

https://github.com/reasonml-community/bs-webapi-incubator/blob/bc0badfc40420e271f4b1703dd9c43bed7d68b13/src/Webapi/Webapi__Dom/Webapi__Dom__Node.re#L32-L55

**Comment by lildude** [comment]
😢 what's wrong with the lovely template we ask you to fill in when opening an issue? It's there for your benefit as much as ours.

If you'd read it, you'd see point 2 is:

- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,

Third heading down from where that link opens is: 

[There's a problem with the syntax highlighting of a file](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file)

... which tells you exactly what you need to do. This is precisely why we have that lovely template - it's to save you time and energy.

Is there anything we could have done better that would have encouraged you to read and or fill in the template and potentially help guide you in the right direction from the start?

**Comment by Risto-Stevcev** [comment]
Yeah sorry about that I skipped it -- it was quite long and the bug definitely exists and doesn't have a ticket. How do I find the upstream grammar repository for reasonml?

**Comment by Alhadis** [comment]
> I skipped it -- it was quite long

@Risto-Stevcev, that isn't fair on us, particularly since we went out of our way to make the documentation as clear and helpful as possible for users reporting the same issue.

> How do I find the upstream grammar repository for reasonml?

... if you'd bothered to follow what @lildude said, you'd notice the answer is in plain sight:

![figure-1](https://user-images.githubusercontent.com/2346707/58107957-49341280-7c2e-11e9-8774-3a1c4ecbc48f.png)

**Comment by Alhadis** [comment]
I've submitted a PR upstream that will fix the issue. See [`reasonml-editor/language-reason#6`](https://github.com/reasonml-editor/language-reason/pull/6).

Basically, the pattern that matched `// line-comments` was being (pointlessly) included inside `/* block comments */`, causing a pair of double-slashes to spill beyond the closing `*/`. That's exactly what's happening in the [affected file](https://github.com/reasonml-community/bs-webapi-incubator/blob/bc0badfc40420e271f4b1703dd9c43bed7d68b13/src/Webapi/Webapi__Dom/Webapi__Dom__Node.re#L32-L55):

~~~reason
  [@bs.send.pipe : T.t] external foo : Dom.node_like('a) => int = ""; /* https://url.com/ */
  [@bs.send.pipe : T.t] external bar : Dom.node_like('a) => bool = "";
  [@bs.send.pipe : T.t] external baz : Dom.node = "";
~~~

Notice what happens if I put a space between the two slashes:

~~~reason
  [@bs.send.pipe : T.t] external foo : Dom.node_like('a) => int = ""; /* https:/ /url.com/ */
  [@bs.send.pipe : T.t] external bar : Dom.node_like('a) => bool = "";
  [@bs.send.pipe : T.t] external baz : Dom.node = "";
~~~

**Comment by Risto-Stevcev** [comment]
Yeah again sorry about that. I did read that section but I didn't connect that that link had anything to do with the upstream urls. Shortening the guidelines to half a page even if it ends up being a summary checklist would really help
