### ISSUE TITLE
`.ts` file is identified as Javascript

### ISSUE THREAD

**Issue by arzyu** [github/linguist#4558]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

`src/zero-webpack.ts` is identified as Javascript.

```shell
$ github-linguist --breakdown
80.41%  JavaScript
19.59%  TypeScript

TypeScript:
src/index.ts

JavaScript:
src/zero-webpack.ts
```

### URL of the affected repository:

https://github.com/arzyu/zero-webpack

### Last modified on:
2019-06-18

### Expected language:
Typescript

### Detected language:
Javascript

**Comment by lildude** [comment]
This is happening because of the shebang at the top of that file:

```
#!/usr/bin/env node
```

The shebang strategy takes precedence over the file extension:

https://github.com/github/linguist/blob/3a1bd3c3d3e741a8aaec4704f782e06f5cd2a00d/lib/linguist.rb#L60-L69

... and as `node` is _not_ a valid TypeScript interpreter (see the discussions in https://github.com/github/linguist/issues/4469 and https://github.com/github/linguist/pull/4470) it is _only_ associated with Javascript, hence the classification.

If you wish to have it identified as TypeScript, you'll need to use an override in `.gitattributes` or a modeline in the file itself.

**Comment by arzyu** [comment]
Thank you for pointing this out, I will set up an override. 👍

**Comment by JanTheHun** [comment]
I'm having the same problem. My repo is purely TypeScript but it gets misidentified as JavaScript.

I think I have a valid use case for a TypeScript file to include ```#!/usr/bin/env node``` shebang, it's a CLI that needs to be running from command line. Let me point out the fact that ```.ts``` files are are being transpiled to ```.js``` files, the only - well, the convenient - way to include shebang in the output ```.js``` file is to include in the source ```.ts``` file.

If I may: adding node as a TypeScript interpreter was not a mistake, though removing it was based on a misunderstanding regarding the workings of TS and JS. My proposition is to prioritize extension-based strategy over the shebang, so that proper TypeScript files including shebang are being identified as TypeScript as long as they have the right ```.ts``` extension.
