### ISSUE TITLE
Incorrect C code block highlight in pull requests

### ISSUE THREAD

**Issue by beltekylevi** [github/linguist#4562]
## Problem Description

The asterisk character in fenced C code block behaves strangely. I included an example pull request.  You can check line 50 where it gets bold in the code block.

### URL of the affected repository:

https://github.com/beltekylevi/asterisk-pull-request-bug/pull/2/files

**Comment by lildude** [comment]
Why did you delete the template?  The second point links to the troubleshooting docs which details precisely where you should be logging this issue - hint: it's not here 😉.

**Comment by lildude** [comment]
> The second point links to the troubleshooting docs which details precisely where you should be logging this issue - hint: it's not here 😉.

Scrap that part. I've just seen the file itself renders correctly, as does the preview diff, but not in the code diff view.

This is still not the right place. This looks to be a problem with the rendering of code blocks within diffs which is not something Linguist has control over. You're best contacting GitHub support.

**Comment by lildude** [comment]
Looking closely at the HTML code, it appears this is because the rendering is correctly marking the file as prose (because it's markdown) and using it's syntax highlighting for the markdown parts of the file, but then getting confused when it sees the `**` within the code block which is the start of **bold** markdown syntax and it is that that is being applied from that point on.

This is going to be something awry with the rendering of code blocks within READMEs within diff views and outside of the scope of Linguist.

**Comment by beltekylevi** [comment]
@lildude thanks for your answer and sorry for removing the issue template.

I contacted GitHub support at the first place and I was told to contact you guys. I am going to message them attaching this issue.

**Comment by beltekylevi** [comment]
@lildude @stevecat created an issue for the responsible GitHub team hence I am closing this issue.
