### ISSUE TITLE
ActionScript detected as AngelScript

### ISSUE THREAD

**Issue by gmattie** [github/linguist#4580]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Recently added ActionScript projects (old code added for archiving purposes) have been incorrectly tagged as AngleScript.

### URL of the affected repository:

- https://github.com/gmattie/Drop-Swatch
- https://github.com/gmattie/Disco-Desktop

### Last modified on:
2019-07-11

### Expected language:
ActionScript

### Detected language:
AngelScript

**Comment by lildude** [comment]
Can you please add back and complete the template. We request this to be filled to help you and help us.

**Comment by pchaigno** [comment]
> We request this to be filled to help you help us.

@lildude I think you meant to help us help you :smiley: 

It looks like there is [some issue with newlines](https://github.com/gmattie/Disco-Desktop/blob/dd5bd50fc7c8d0d90269c7e0d3c6e42c9188e701/DiscoController.as) in these ActionScript files. Because of that, [our current `.as` heuristic](https://github.com/github/linguist/blob/001ca526694a32a5ac4c977a79032ced0b8c0aca/lib/linguist/heuristics.yml#L51) is unable to match those files and falls back to AngelScript. I'd recommend using an override or fixing your newlines.

**Comment by Alhadis** [comment]
> It looks like there is [some issue with newlines](https://github.com/gmattie/Disco-Desktop/blob/dd5bd50fc7c8d0d90269c7e0d3c6e42c9188e701/DiscoController.as) in these ActionScript files

Technically, there's nothing wrong with the files. They're simply saved using old Mac line-terminators (`\r`, carriage returns), as opposed to `\r\n` or `\n` (used by Windows and POSIX, respectively).

The underlying issue is actually our fault, as Linguist/GitHub don't acknowledge plain carriage returns as line-endings. See #2988.

@gmattie *did* say "old code added for archiving purposes", and it'd be callous of us to expect users to modify old codebases for addressing a shortcoming that's primarily our oversight...

**Comment by pchaigno** [comment]
Hm, you're right. Do we have a fix for that?

**Comment by Alhadis** [comment]
At a rough guess, I'd say it's probably something that needs to be fixed on GitHub's end... @lildude could probably confirm.

**Comment by lildude** [comment]
> At a rough guess, I'd say it's probably something that needs to be fixed on GitHub's end... @lildude could probably confirm.

🤔 I don't think this is something that should be addressed on the GitHub side of things as it interprets the CR/LF chars like git does and the syntax highlighting has no problems once the language has been detected correctly. I think this sits squarely in Linguist's realm as this is where the language detection is taking place, which in this case is right about here...

https://github.com/github/linguist/blob/001ca526694a32a5ac4c977a79032ced0b8c0aca/lib/linguist/heuristics.yml#L50-L52

This isn't matching because we're not taking into account the `^M` chars. It would be a PITA to update all the heuristic regexs but I think this could probably solved a few `.gsub()` calls just after loading the data here https://github.com/github/linguist/blob/001ca526694a32a5ac4c977a79032ced0b8c0aca/lib/linguist/heuristics.rb#L24

**Comment by pchaigno** [comment]
@gmattie Do you want to submit a pull request for that (with the change suggested by @lildude)? We could use one of your files as a test case.

**Comment by gmattie** [comment]
The files have already been converted locally and I replaced the archives, so the old files with the mac line terminators are gone.

I wanted the (old and slightly embarrassing) code to be readable on GitHub and there weren't too many files to update so I used Notepad++ to convert the EOLs from CR to CR LF and reuploaded and archived the repos.
