### ISSUE TITLE
Can't detect md

### ISSUE THREAD

**Issue by imba-tjd** [github/linguist#4591]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I have set these in [my `.gitattributes`](https://github.com/imba-tjd/LeetCode/blob/md/.gitattributes):

```
*.md linguist-detectable=true
*.md linguist-language=Markdown
*.md linguist-documentation=false
```

But it still can't detect md.

I tried the first override in my another repo and it works. So I doubt whether it's my problem.

### Last modified on:

2019-7-26

### Expected language:

C#, Markdown, other

### Detected language:

C#, other

**Comment by lildude** [comment]
This is going to be due to the way the language results are cached. Updating your `.gitattributes` file alone won't cause a reanalysis.

Modifying one of the Markdown files should force a reanalysis.

**Comment by imba-tjd** [comment]
I have push two commits just now and it seems the same 😢

**Comment by lildude** [comment]
🤦‍♂ I see why now. The `.gitattributes` only applies to your default branch, which in your case is `master`. You'll need to make your `.gitattributes` changes to the default branch in order for it to take effect.

Once you've done that, you should get results similar to this (I manually ran linguist against your `md` branch):

```
71.30%  C#
27.28%  Markdown
0.71%   C
0.63%   TSQL
0.07%   Batchfile
```

**Comment by imba-tjd** [comment]
Works, thank you! 😂

**Comment by 0xdevalias** [comment]
In case you end up here from google (like I just did), this article is a good overview of how to solve this: https://joshuatz.com/posts/2019/how-to-get-github-to-recognize-a-pure-markdown-repo/

**Comment by Alhadis** [comment]
Or you could, y'know, read [our readme's _"Troubleshooting"_ section](https://github.com/github/linguist#troubleshooting), which contains a [solution](https://github.com/github/linguist#detectable) to this very problem. 😉

**Comment by 0xdevalias** [comment]
@Alhadis I did read it, and used it to fix a different similar issue, but it in and of itself wasn't sufficient information to make it simple/easy/obvious for my problem. Likely why I have seen multiple issues on it when searching here, and why people need to write blog posts about it. Since this came up near the top of the google results when I was searching, and it took more focussed searching/thread following to source the linked blog (which i'm not affiliated with in any way, but which provided a concise and detailed solution to my problem), I figured I would make future searchers lives easier by pointing them in the right direction.
