### ISSUE TITLE
Unicode ldml files identified as Lasso

### ISSUE THREAD

**Issue by jasonleenaylor** [github/linguist#4597]
Our repo has test data files with the extension .ldml which conforms to the unicode standard locale data markup language (http://unicode.org/reports/tr35/)

These files are misidentified as Lasso

## Problem Description

xml format .ldml files should either be counted as data or as xml.

### URL of the affected repository:
https://github.com/sillsdev/FieldWorks

### Last modified on:
2019-07-31

### Expected language:
Data, or XML

### Detected language:
Lasso

**Comment by lildude** [comment]
> These files are misidentified as Lasso

This is because this is the only language associated with the `.ldml` extension:

https://github.com/github/linguist/blob/72542687adfc47a5d8b941bb3d8a5311edaa10e1/lib/linguist/languages.yml#L2630-L2638

...  and the extension takes priority over the XML strategy:

https://github.com/github/linguist/blob/72542687adfc47a5d8b941bb3d8a5311edaa10e1/lib/linguist.rb#L60-L69

The `.ldml` extension was added to Lasso waaaaaay back in https://github.com/github/linguist/pull/1451 in August 2014 so has been in place for a very very long time.  

By today's usage requirement standards, we wouldn't have added this extension to Lasso as the usage is incredibly low at 54 files 😀. The XML usage appears to be higher, though still only 225 files so not very popular itself and certainly not popular enough for inclusion under XML.

Given the low usage of Lasso `.ldml` files and the fact we have other Lasso files, I suspect removing the extension from Lasso would solve this whilst still allowing the Lasso files to be correctly identified.

I don't have the time to test this right now, but maybe you, @Alhadis or @pchaigno do.

Until then, an override is the only way to get those files correctly identified.

**Comment by pchaigno** [comment]
> Given the low usage of Lasso .ldml files and the fact we have other Lasso files, I suspect removing the extension from Lasso would solve this whilst still allowing the Lasso files to be correctly identified.

Removing the extension from Lasso will break identification of these few files. Given the low number of files, I think this is fine. @jasonleenaylor Do you want to open a pull request to remove `.ldml` extensions from `languages.yml`?
