### ISSUE TITLE
incorrect language bar

### ISSUE THREAD

**Issue by pojozhang** [github/linguist#4598]
## Problem Description

The language bar shows that TSQL is at 90.6%,  but when l click the TSQL button  l get no result at all. The calculation also seems incorrect because l didn't write so many TSQLs.

![image](https://user-images.githubusercontent.com/26052846/62407967-72d8c500-b5f3-11e9-8740-ab9092a1d7f6.png)

![image](https://user-images.githubusercontent.com/26052846/62407999-03afa080-b5f4-11e9-8378-06882296ff49.png)

### URL of the affected repository:

https://github.com/pojozhang/playground

### Last modified on:

2019-08-01

**Comment by Kilo-411** [comment]
Wow.. That's different.. Like a broken nuculear missile laying out there..
This site is infected.

**Comment by lildude** [comment]
> The language bar shows that TSQL is at 90.6%, but when l click the TSQL button l get no result at all. The calculation also seems incorrect because l didn't write so many TSQLs.

The calculation is 100% correct due to this one huge file: https://github.com/pojozhang/playground/blob/master/problems/mysql/resources/sakila-data.sql - the file alone if 3.2MB in size and is disproportionately large compared to the rest of the repository. 

As this is larger than 384KB as detailed in the [Considerations for code search](https://help.github.com/en/articles/searching-code#considerations-for-code-search) as linked to in the README.md, it will not show up in the search results when you click the language in the language bar. Linguist doesn't have this constraint, hence it is included in the language statistics.

As for the file being identified as TSQL, this is because the content matches this heuristic:

https://github.com/github/linguist/blob/72542687adfc47a5d8b941bb3d8a5311edaa10e1/lib/linguist/heuristics.yml#L399-L403

If you don't want TSQL to be reported as the predominant language in your repository, you'll need to implement an override that best suits your preference as per the README.md.

**Comment by pojozhang** [comment]
> > The language bar shows that TSQL is at 90.6%, but when l click the TSQL button l get no result at all. The calculation also seems incorrect because l didn't write so many TSQLs.
> 
> The calculation is 100% correct due to this one huge file: https://github.com/pojozhang/playground/blob/master/problems/mysql/resources/sakila-data.sql - the file alone if 3.2MB in size and is disproportionately large compared to the rest of the repository.
> 
> As this is larger than 384KB as detailed in the [Considerations for code search](https://help.github.com/en/articles/searching-code#considerations-for-code-search) as linked to in the README.md, it will not show up in the search results when you click the language in the language bar. Linguist doesn't have this constraint, hence it is included in the language statistics.
> 
> As for the file being identified as TSQL, this is because the content matches this heuristic:
> 
> https://github.com/github/linguist/blob/72542687adfc47a5d8b941bb3d8a5311edaa10e1/lib/linguist/heuristics.yml#L399-L403
> 
> If you don't want TSQL to be reported as the predominant language in your repository, you'll need to implement an override that best suits your preference as per the README.md.

ok, thanks a lot!
