### ISSUE TITLE
Python/Bash repository detected as Roff

### ISSUE THREAD

**Issue by Jyouhou** [github/linguist#4636]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
I have a repository that has more than 50% of python and 40% bash, but the language is displayed as Roff(98%)

### URL of the affected repository:
https://github.com/Jyouhou/ICDAR2019-ArT-Recognition-Alchemy

### Expected language:
Python

### Detected language:
Roff

**Comment by yansheng836** [comment]
Have you read this <https://github.com/github/linguist#overrides>?

**Comment by Alhadis** [comment]
@yansheng836 He probably has, because clicking on Roff in the language-bar brings up [an empty search result list](https://github.com/Jyouhou/ICDAR2019-ArT-Recognition-Alchemy/search?l=roff). Given the repository's files are only recent, I'd say this isn't a typical caching issue with GitHub.

/cc @lildude

**Comment by lildude** [comment]
Nope. The reason this is happening is you have one really big file at https://github.com/Jyouhou/ICDAR2019-ArT-Recognition-Alchemy/blob/master/Source/datasets/lexicon/iiit5k.1k which is over 19mb and accounts for over 98% of the total size of your entire repo. You'll need to use an override to ignore this file.

**Comment by yansheng836** [comment]
So that explains it.

I found another strange thing: I  am using a chrome extension([github-repo-size](https://github.com/harshjv/github-repo-size)) to show the repo size which is shows 3.69MB,but that file is 19.1MB.

the repo size:
![image](https://user-images.githubusercontent.com/45334066/64074074-04158700-ccd9-11e9-86ac-7562b9da49d7.png)

---
a one file of the repo:
![image](https://user-images.githubusercontent.com/45334066/64074071-f3fda780-ccd8-11e9-9256-35b9714c02ee.png)

**Comment by pchaigno** [comment]
> I found another strange thing: I am using a chrome extension([github-repo-size](https://github.com/harshjv/github-repo-size)) to show the repo size which is shows 3.69MB,but that file is 19.1MB.

Your repository is 27MB in size, so you might want to open an issue on the repository for that extension.

**Comment by yansheng836** [comment]
@pchaigno Ok, thank you.

**Comment by Jyouhou** [comment]
Thank you all so much! This seems to be the reason for the misclassification.

I added a `.gitattributes` file to the root of my repo:

`./Source/datasets/lexicon/* linguist-language=Python`

But the stats did not change.

**Comment by lildude** [comment]
You'll need to modify one of the affected files as implementing an override alone is insufficient to initiate a reanalysis.

**Comment by Jyouhou** [comment]
I added all the non-python and non-shell stuff to the gitattributes. Now it displays python.

Thank you all!
