### ISSUE TITLE
Measuring Data & Media Files

### ISSUE THREAD

**Issue by ForgivenNin** [github/linguist#4651]
## Measuring Data Files (Last Modified on 2019-09-25)
- [x] reviewed how Linguist works
- [x] verified an issue has not already been logged for your issue

For some, it is general practice that one tries to keep the file size of their programs as small as possible, especially when you're hosting something yourself. This applies when it comes to making web applications. A developer would want to know the size of media files in comparison to their code. So, as you can see where I'm going with this, I am suggesting that there should be an option to _enable_ these types of things to be detectable.

Already, to some degree, you have done this with the `.json` file. Though it is not automatically noticed, we can add a `.gitattributes` configuration to make it do just that (which I'm, personally, thankful for). The concept can be applied to this suggestion, too.

**Comment by Alhadis** [comment]
Linguist (and by extension, GitHub) doesn't index or classify binary files (I'm assuming you mean "media files" as in images, videos, audio, et alia). Adding an option to do otherwise would probably necessitate a huge amount of work for very little gain.

That being said, you might find [this browser extension](https://github.com/harshjv/github-repo-size) useful. =)
