### ISSUE TITLE
Python language is not detected on repo with python modules marked executable

### ISSUE THREAD

**Issue by wesinator** [github/linguist#4690]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
https://github.com/Th3Hurrican3/PEpper 
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/5124946/67785071-1430b500-fa43-11e9-958a-0cc3fad42a71.png">

Python does not show up at all in the languages, even though there are multiple modules
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5124946/67785088-1a269600-fa43-11e9-8db7-fd668de68cd0.png">

The python modules are marked "executable file"

### Last modified on:

2019-07-15

### Expected language:

Python (included)

### Detected language:

YARA, Other

**Comment by lildude** [comment]
> Python does not show up at all in the languages, even though there are multiple modules

Well, it technically does... but first an import bit of info from the README:

> The percentages are calculated based on the bytes of code for each language as reported by the List Languages API.

So that means your Python is going to be part of the "Other 0.9%" because all files that aren't identified as YARA total less than 1% of the entire repo content:

YARA 5.46 MB
Python 53 KB
Shell 2.01 KB

As you can see those YARA files are clearly the predominant force in your repo.

If you want Python to show, you're gonna need to write a lot more Python 😉 or use an override to ignore the YARA files when calculating the language stats. As those appear to all be under `rules` and appear to be from a third party, you probably want to mark them as vendored.

**Comment by wesinator** [comment]
> > The percentages are calculated based on the bytes of code for each language as reported by the List Languages API.
> 
> So that means your Python is going to be part of the "Other 0.9%" because all files that aren't identified as YARA total less than 1% of the entire repo content:
> 
> YARA 5.46 MB
> Python 53 KB
> Shell 2.01 KB
> 

ok, that makes sense
