### ISSUE TITLE
decksh files mistaken for Makefiles

### ISSUE THREAD

**Issue by ajstarks** [github/linguist#4723]
The repo ajstarks/dubois-data-portraits contains decksh (deck shell) files with extension '.dsh'
This repo is marked as "Makefile"

### URL of the affected repository:

https://github.com/ajstarks/dubois-data-portraits

### Last modified on:

2019-11-23

### Expected language:

decksh

### Detected language:

Makefile

**Comment by ajstarks** [comment]
desksh is described here:

https://speakerdeck.com/ajstarks/decksh-a-little-language-for-decks

**Comment by lildude** [comment]
They're only "mistaken" because Linguist has no idea what the "decksh" language is so has had to make a guess based on the samples we have for the three languages it knows about that have the `.d` extension, with Makefile being the closest. 

The only way this can be changed is for support to be added to Linguist. Please review our contributing guidelines and if you feel decksh meets the requirements, especially the popularity requirement, please feel free to submit a PR adding support.
