### ISSUE TITLE
Language erroneously reported as Objective-C (vs C++) but then not existing on query search

### ISSUE THREAD

**Issue by Jakz** [github/linguist#4744]
## Problem Description

I've given a look to similar issues, the more relevant seems to be [this one](https://github.com/github/linguist/issues/1626) which is still open but in this case no file is currently reported of a different language.

The repository is [this](https://github.com/Jakz/impossible), the code is C++with a Flex/Bison parser (but .ypp file, which is a C++ Bison file, is not assigned to any type).

According to the preview the repository should contain 74.4% of Objective-C code but clicking on the [link ](https://github.com/Jakz/impossible/search?l=objective-c
) which search in the repository by language gives no results.

So there's a discrepancy between the reported language and the search, the latter is not able to provide any result in Objective-C. It looks like more a caching issue to me?

### URL of the affected repository:
https://github.com/Jakz/impossible

### Last modified on:
2019-06-30

### Expected language:
C++

### Detected language:
Objective-C but only in the preview so it doesn't look like a problem of heuristics

**Comment by lildude** [comment]
> So there's a discrepancy between the reported language and the search, the latter is not able to provide any result in Objective-C. It looks like more a caching issue to me?

Nope. It's the first point of the first troubleshooting section in the README.md, which I note you've decided not to confirm you've read by removing that section of the template 😉 

The file in question is https://github.com/Jakz/impossible/blob/master/src/tests/catch.h - that file is 466 KB which is considerably larger than all of the other code in the repo combined... 

Objective-C 466 KB
C++ 155 KB
Lex 5.63 KB

... hence it's position as the primary language.

The fact it's detected as Objective-C is going to be due to the common issue that happens with the `.h` files in the C-family of languages... they all share the same extension and the files can often be used in all of the C-family languages without any changes making it neigh on impossible to determine the desired language when looking at the file in isolation, which Linguist does.

The only solution is to implement an override.

**Comment by Jakz** [comment]
> Nope. It's the first point of the first troubleshooting section in the `README.md`, which I note you've decided not to confirm you've read by removing that section of the template

Oh sorry, I thought I had to read it (which I did), not that I had to keep the text in the actual report. So mine was a genuine lack of understanding because I saw a huge chunk of code being Objective-C but I couldn't find any code matching the description, now I understand that .h files can be misreported, but then is it filtered out from because of its size (max is 384 KB) and everything makes sense. The problem is that I wasn't able to see it.

I guess that renaming it to `.hpp` would solve the problem too.

Sorry for bugging 😔
