### ISSUE TITLE
repository language not detected

### ISSUE THREAD

**Issue by sayashraaj** [github/linguist#4746]
Hi I am new to GitHub. 
I have made a simple tic tac toe game in C++ in my repository: 
[Link to repository: tictactoe](https://github.com/sayashraaj/tictactoe)
GitHub is not displaying any language for my repository, pls help

**Comment by lildude** [comment]
You need to rename your `tictactoedraft.txt` file to something like `tictactoedraft.cpp` as the `txt` extension indicates plain text which isn't considered a programming language. The `cpp` extension will tell Linguist this is a cpp file.

**Comment by lildude** [comment]
Like I've done in a fork of your repo - https://github.com/lildude/tictactoe.

You don't need any overrides either so you can delete the `.gitattributes` file.

**Comment by sayashraaj** [comment]
Thank you! Solved

**Comment by Sukarnascience** [comment]
Can you Please check mine too why is my repo... is not showing the language.. i went through your provided documentation but still cant able to fix So... here is [My Repo...](https://github.com/Sukarnascience/React_Learning)

**Comment by lildude** [comment]
@Sukarnascience  this should really have been a new discussion as this issue is closed. That said, in your case it's because all your code is either under `demo` which is considered documentation:

https://github.com/github/linguist/blob/16c70aef8cd62ca071231a380c69050f5e83c900/lib/linguist/documentation.yml#L18

… or `node_modules` which is considered vendored.

I doubt you want to count the `node_modules` but to count your other code you'll need to use an override to tell Linguist to not consider `demo` as documentation.

**Comment by Sukarnascience** [comment]
> I am extremely sorry @lildude sir, I am recently started exploring the features So, i keep on messing things here and there... Sorry

Ouuu.. I see. As you said i have seen after i changed it , it's worked ... huraa :partying_face: ... Thanks a lot once again sir
