### ISSUE TITLE
F90 File syntax highlighting broken?

### ISSUE THREAD

**Issue by jacobwilliams** [github/linguist#4799]
###  Problem Description

GitHub's highlighting of Fortran `.f90` files is broken. GitHub Developer Support tells me that it is a linguist issue. 

An example can be seen for any `.f90` file on GitHub. For example: [here](https://github.com/jacobwilliams/bspline-fortran/blob/master/src/bspline_oo_module.f90)

* The comment lines (that start with `!` are not being recognized).
* A lot of key works aren't being highlighted (for exampled `select case`).

This used to work, but was broken sometime fairly recently (maybe the last couple months or so, at least that's when I noticed it).

**Comment by lildude** [comment]
Why did you not complete the template? The second point would have taken you to https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file and you'd have saved yourself some time and effort 😉 . 

Closing as this is not a Linguist issue but an issue with the upstream grammar.

**Comment by jacobwilliams** [comment]
Thanks for pointing me in the right direction! Turns out there's already an issue here: https://github.com/textmate/fortran.tmbundle/issues/25

However, I note that repo hasn't been modified in 2 years... so I don't see how that could be source of the problem.

**Comment by Alhadis** [comment]
I'm not sure what's happening either. The file @jacobwilliams linked to is [highlighted correctly](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.fortran.modern&grammar_format=auto&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fjacobwilliams%2Fbspline-fortran%2Fraw%2Fmaster%2Fsrc%2Fbspline_oo_module.f90&code=) on Lightshow, and the file is correctly identified as Fortran:

<img src="https://user-images.githubusercontent.com/2346707/74901941-a137b980-53f8-11ea-941b-6d5b24e60074.png" alt="Figure 1" />

**Comment by lildude** [comment]
🤔 I've looked into this and I don't see how this was ever correctly highlighted, though it os possible it was prior to a recent change to the way we perform syntax highlighting.

The Fortran grammar provides two grammars:

```console
$ rg -A2 scopeName fortran.tmbundle/
fortran.tmbundle/Syntaxes/Fortran - Modern.tmLanguage
391:    <key>scopeName</key>
392-    <string>source.fortran.modern</string>
393-    <key>uuid</key>

fortran.tmbundle/Syntaxes/Fortran - Punchcard.tmLanguage
801:    <key>scopeName</key>
802-    <string>source.fortran</string>
803-    <key>uuid</key>
$
```

... and the `grammars.yml` file has these two and has remained unchanged in over 5 years:

https://github.com/github/linguist/blame/b545f1c6befe87c2074e5e608f47ca0f6334d355/grammars.yml#L313-L315

The issue here is going to be the `source.fortran` grammar being applied to these files and not `source.fortran.mordern` that is being applied in the Lightshow link @Alhadis provided as we can see from [this example directly using the `source.fortran` grammar](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Ftextmate%2Ffortran.tmbundle%2Fblob%2Fmaster%2FSyntaxes%2FFortran%2520-%2520Punchcard.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fjacobwilliams%2Fbspline-fortran%2Fraw%2Fmaster%2Fsrc%2Fbspline_oo_module.f90&code=).

At the moment there's no way to force the correct grammar, but there will be once https://github.com/github/linguist/pull/4753 has been finished (nudge @ararslan 😉), merged and deployed:

> Currently all Fortran files are recognized as fixed-source (think FORTRAN 77 style), which is provided by the TextMate bundle as `source.fortran`. However, the old style really only applies for a few file extensions.

**Comment by Alhadis** [comment]
> though it is possible it was prior to a recent change to the way we perform syntax highlighting.

Just out of curiosity, could you elaborate on that?

**Comment by lildude** [comment]
> Just out of curiosity, could you elaborate on that?

Nope, that would be revealing our ~dirty laundry~ secrets 😉 

In short, we're moving away from a dedicated PrettyLights service which only uses TextMate compatible grammars provided solely by Linguist (as it is quite a resource hog and grows all the time), to a [Tree-sitter](https://tree-sitter.github.io/tree-sitter/) based service which must more performant and easier on resources which in turn relies on PrettyLights as a fallback for everything it doesn't know about.

**Comment by Alhadis** [comment]
I was hoping the answer wasn't going to involve Tree-Sitter... ugh.

> which is much more performant and easier on resources

It's also rigid and horribly complex when it comes to authoring grammars. Hence why I refuse to touch it with a parsec-long broom handle.

**Comment by ararslan** [comment]
> nudge @ararslan :wink:

Sorry, I've had no time to revisit that. If anyone feels they could get to it sooner, they're welcome to base their work off of my branch in #4753 without attribution, but see the comments on that PR. Once that PR is finished, I believe merging it will resolve this issue. I'll see if I can get to it within the next week but no guarantees...

**Comment by ararslan** [comment]
> it has not had activity in a long time

Yeah...

**Comment by ararslan** [comment]
This issue has not yet been solved.

**Comment by ararslan** [comment]
Same deal
