### ISSUE TITLE
Run linguist on text

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [github/linguist#4825]
Hello!
Is it possible to run linguist or some part of it on text instead of files? I am trying to solve following problem: detect, is there any piece of code in user message or not.

Thank you!

**Comment by pchaigno** [comment]
No. Linguist heavily relies on the file extension to detect languages. Without the file extension, results are going to be poor, if not arbitrary.

**Comment by ZaMaZaN4iK** [comment]
I think at least two methods (heuristic-based and bayes-classifier based) can be runned on a text. But thank you - I think it can be closed.

**Comment by pchaigno** [comment]
Yes, but as I said, results will be poor. The Bayesian classifier has very poor accuracy and that's why we run it last. With all languages as candidates, it'd be even worse. The heuristic rules are built to distinguish between a specific set of languages; a heuristic rule for `.h` files might give incorrect results if you add Python files to the mix.
