### ISSUE TITLE
Linguist not updating after adding .gitattributes for vendored code

### ISSUE THREAD

**Issue by sumanthratna** [github/linguist#4837]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
    - that's what I did
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).
    - this issue has been raised before, but no workaround has worked

## Problem Description
Shortly after I pushed to my repo, the color bar was updating to include new code I added (Smarty), which wasn't present before. However, when it updated, it didn't update based on the .gitattributes file I added, which added `linguist-vendored` to many files. I'm not sure if this is a caching issue, GitHub's servers just taking their time (as mentioned in the README), or whatever else, since the new language was added relatively quickly. 

Further, `css/animate.css`, `css/bootstrap.css`, `css/jquery-ui.min.css`, etc. are all showing up as CSS, even though they're listed in  https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml. 

### URL of the affected repository: 
https://github.com/sumanthratna/website

### Last modified on:
2020-04-03

### Expected language:
n/a

### Detected language:
n/a

Note: I would run `linguist` locally to investigate myself, but I can't install it, as I'm on a macOS beta. I'll raise another issue for this if I can't fix it, but for now, this issue is of higher priority for me.

**Comment by lildude** [comment]
You've not clearly stated what you're seeing but are expecting to see so I'm going to take a guess from your other comments that you don't expect CSS to be the predominant language. 

I can confirm your `.gitattributes` _is_ taking effect. The reason CSS is the predominant language is because your two remaining CSS files that count, count for more bytes of code than the rest of your files:

CSS 61.5 KB
Smarty 59.4 KB
PHP 12.5 KB
JavaScript 4.03 KB

```console 
$ github-linguist --breakdown .
44.77%  CSS
43.21%  Smarty
9.09%   PHP
2.94%   JavaScript

PHP:
admin.php
auth.php
contact.php
index.php
setup.php

CSS:
css/style.scss
style.css

JavaScript:
js/main.js

Smarty:
templates/footer.tpl
templates/header.tpl
templates/pages/about.tpl
templates/pages/admin/login.tpl
templates/pages/admin/manage.tpl
templates/pages/blog/index.tpl
templates/pages/blog/post.tpl
templates/pages/contact.tpl
templates/pages/home.tpl
templates/pages/search.tpl
templates/socials.tpl

$
$ /bin/ls -lh css/style.scss style.css
-rw-r--r--  1 lildude  staff    29K  5 Apr 09:42 css/style.scss
-rw-r--r--  1 lildude  staff    33K  5 Apr 09:42 style.css
$
```

As you can see, none of the vendored files have been included in the analysis. 

As you're vendoring your other SCSS files, you might want to vendor `css/style.scss` too.

As for:

> Further, css/animate.css, css/bootstrap.css, css/jquery-ui.min.css, etc. are all showing up as CSS…

They're not. See output above. What you're looking at are the search results which are completely independent from Linguist and deliberately ignore the `.gitattributes` content. If it didn't, you'd never be able to search for your vendored files 😄.
