### ISSUE TITLE
GLSL language showing with 0 GLSL code present

### ISSUE THREAD

**Issue by DOWRIGHTTV** [github/linguist#4852]
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

repo is showing a language that doesnt even have 1 line of code throughout.

### URL of the affected repository:
https://github.com/DOWRIGHTTV/dnxfirewall-cmd

### Last modified on:
2020-04-06

### Expected language:
Python/ Python3

### Detected language:
GLSL

**Comment by lildude** [comment]
This is because you're using the `.geo` extension for several of your files  and this extension is associated with GLSL:

https://github.com/github/linguist/blob/309acde92e04c86466441afc12992274be938473/lib/linguist/languages.yml#L1622-L1647

You'll need to implement an override to have these reflected at the language you want or exclude them entirely.

**Comment by DOWRIGHTTV** [comment]
oh, right. thanks! lets pretend this never happened? ;)
