### ISSUE TITLE
PHP syntax highlighting does not work without <?php

### ISSUE THREAD

**Issue by Dibbyo456** [github/linguist#4865]
## Preliminary Steps

Please confirm you have...
- [ ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

From last 2-3 days I noticed that PHP syntax highlighting stopped working not only on my repos but many repos I follow. After investigating I found that when code blocks start without `<?php` then php syntax highlighting does not generate.

### Without PHP start tag:
![chrome_2020-05-17_18-05-30](https://user-images.githubusercontent.com/18257605/82146592-06207580-9869-11ea-8ba9-b132f45e0ddf.png)

### With PHP start tag:

![chrome_2020-05-17_18-06-08](https://user-images.githubusercontent.com/18257605/82146612-26e8cb00-9869-11ea-8cba-3a30526659c7.png)

### URL of the affected repository:
https://github.com/Dibbyo456/mysqli-database-class

### Last modified on:
May 16, 2020

### Expected language:
PHP

### Detected language:
None

**Comment by lildude** [comment]
🤔 Are you sure this changed recently? I think this behaviour (which is part of [markup](https://github.com/github/markup), not Linguist) has been around for quite some time and there's even issue for it in the markup repo - https://github.com/github/markup/issues/1230

It doesn't look like markup has been updated recently and I've not deployed an update to Linguist since March, so if you're 100% certain this worked before 16 May, please contact GitHub Support using the "Contact GitHub" link at the bottom of the page and report it to them as something outside of Linguist and markup is responsible for this change in behaviour.

**Comment by Dibbyo456** [comment]
> 🤔 Are you sure this changed recently?

Yes. A week ago everything was working just fine. I noticed it 5 days ago that markup wasn't showing up. At first I thought I broke it but then while browsing through other repos I realized the issue coming from Github itself. 

> please contact GitHub Support using the "Contact GitHub"

Okay. Will do. I will report back here. Thanks.

**Comment by mfn** [comment]
This 200% worked without requiring `<?php`.

I daily write such fenced code blocks with PHP on the company repos and today I realized they're not colored anymore. This never needed an explicit PHP tag.

=> also contacted github support, this is quite a regression on whatever end

**Comment by Dibbyo456** [comment]
> => also contacted github support, this is quite a regression on whatever end

It's been 24 hours, Github support haven't replied. :/

**Comment by johannesnagl** [comment]
same here. definitely changed

**Comment by Alhadis** [comment]
Pretty sure the culprit is either [recent changes](https://github.com/tree-sitter/tree-sitter-php/compare/e37bd5752d383c240f0bc3b0568e9af3bf72637f...7df04601aa3e3ea8e2c9390da452c195f5436636) to [`tree-sitter/tree-sitter-php`](https://github.com/tree-sitter/tree-sitter-php/commits/master), or a recent change to GitHub's closed-source fork of TextMate's highlighting engine. The change(s) in question more than likely concern the handling of injections, which PHP's grammar makes extensive use of.

That's about as much as I'm able to tell, as I've no knowledge of `tree-sitter` or GitHub's internals.

/cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Yeah, I think I broke this while optimizing GitHub.com's highlighting of embedded code blocks. It appears that there was some special casing of PHP to avoid this problem, and I failed to replicate that special casing in my parallelized implementation.

It isn't a Linguist issue, but let's leave this open until I ship the fix. Thanks for the reports, everyone, and sorry for the poor experience.

**Comment by Alhadis** [comment]
> It appears that there was some special casing of PHP to avoid this problem

Would that, perchance, have anything to do with `injections` being used instead of `injectionSelector`? Because I've noticed Atom isn't 100% consistent with the patterns defined on a grammar's `injections` object, and the patterns of a grammar which defines an `injectionSelector` string.

Another observation I've made is that injections don't affect the contents of a fixed-size capturing group:

~~~regexp
­­injectionSelector: string.body

# This won't work:
name: string.quoted.double
match: /"([^"]+)"/
captures:
	1: name: string.body

# However, this will:
name:  string.quoted.double
begin: /"/
end:   /"/
contentName: string.body
~~~

**Comment by maxbrunsfeld** [comment]
No, the problem here wasn't tied to either the TextMate or Tree-sitter parsers, it was actually some PHP-specific preprocessing in GitHub itself.

**Comment by maxbrunsfeld** [comment]
```php
$php.highlighting($within_code_blocks, IsNow(), FIXED_ON, "github.com")

// No need to include a `<?php` tag at the beginning.

?>

<p>
  Like before, you can <em>still</em> return to HTML mode.
</p>
```

**Comment by Dibbyo456** [comment]
@maxbrunsfeld The issue isn't fully resolved yet. When browsing a repo, Github isn't highlighting php blocks but when viewing README.md explicitly code highlighting works.

## Example:

Browsing repo (https://github.com/catfan/Medoo)

![](http://put.nu/files/sLP96Sc.png)

Browsing README.md (https://github.com/catfan/Medoo/blob/master/README.md)

![](http://put.nu/files/An3L12Z.png)

**Comment by maxbrunsfeld** [comment]
@Dibbyo456 Thanks for the detailed report; I see the problem.

**Comment by maxbrunsfeld** [comment]
I believe the problem is just that GitHub has cached some incorrectly-rendered READMEs. I just [forked](https://github.com/maxbrunsfeld/Medoo) the `catfan/Medoo` repo, and the README renders correctly in my fork.

I will look into busting this cache, but I don't have an ETA for when this will be fixed. Thanks for your patience.

**Comment by maxbrunsfeld** [comment]
I believe all of the incorrectly-rendered data is gone.

**Comment by Dibbyo456** [comment]
Yup. Thank you for taking care of this. 🤟
