### ISSUE TITLE
question: Why github mark C header files as C++?

### ISSUE THREAD

**Issue by delata** [github/linguist#4875]
it's confusing.

**Comment by lildude** [comment]
This has been discussed many many times; simply search the previous issues as suggested in the template you removed 😉 .

https://github.com/github/linguist/issues/1626 is the issue that is still open. Take a look at the discussion (it's a looooong issue) and all the linked issues and PRs.

In short, there is no easy way to differentiate between a header file for C, C++, or Objective-C in every circumstance because many header files are perfectly valid in all three languages without modification. As a result, it falls through to the classifier to make take a guess and it doesn't always get it right.

**Comment by delata** [comment]
then they should be marked as Header File.
not C++.

**Comment by lildude** [comment]
> then they should be marked as Header File.

That would be identifying the function or type of file, not the language. Linguist is for identifying programming languages.

**Comment by delata** [comment]
the system is broken
