### ISSUE TITLE
files with .org not showing in language stats bar

### ISSUE THREAD

**Issue by ojedavidea** [github/linguist#4880]
I have multiple files with .org and they are not showing in the repository language stats bar. I don't understand why.

**Comment by lildude** [comment]
Well, we can't really help you if you don't fill in the template as one of the key methods of being able to help is see the repo in question 😉 

It also allows us to confirm any assumptions about reading the documentation etc referenced in the template.

Please add the original template to the OP.

**Comment by ojedavidea** [comment]
Thank you! My apologies. I guess we can close this issue because I don't know what to write into the template. My comment was a result of my frustration because I didn't know where to get help from. And I just didn't understand how linguist work, why this feature from GitHub for the language stats bar isn't already anywhere available and editable in my repo or account. I understand there are some actions required outside of GitHub but I am not a developer and I can't find out where to start... yet.

**Comment by lildude** [comment]
This is all within your control thanks to you having the ability to write to your repo and add a `.gitattributes` file.

The reason your `.org` files don't count is because that extension is associated with the Org language which is considered "prose", ie written words, and not a programming language:

https://github.com/github/linguist/blob/2a6d952df870807034c3830738f95ad33222aca0/lib/linguist/languages.yml#L3758-L3765

If you want them to be counted, you need to set the `linguist-detectable` attribute for those files as per https://github.com/github/linguist#detectable

**Comment by ojedavidea** [comment]
It worked writing :

`*.org linguist-detectable`

in a new file named :

`.gitattributes`

Thank you !
