### ISSUE TITLE
Typescript repo beeing recognized as Javascript

### ISSUE THREAD

**Issue by rafmst** [github/linguist#4923]
## Problem Description

Could it be because of the .json files? Still, it should show 1% Typescript at least

### URL of the affected repository: 
https://github.com/rafmst/propor

### Last modified on:
2019-07-10

### Expected language:
Typescript

### Detected language:
Javascript

**Comment by lildude** [comment]
> Could it be because of the .json files?

Nope. It's because of the [shebang](https://github.com/rafmst/propor/blob/1d155142ede6996b72b54caa65fe83e4dea2f862/src/index.ts#L1): 

```
#!/usr/bin/env node
```

Linguist considers `node` as an interpreter for Javascript, not Typescript:

https://github.com/github/linguist/blob/775b07d40c04ef6e0051a541886a8f1e30a892f4/lib/linguist/languages.yml#L2564-L2569

For Typescript, you'd need to either use `deno` or `ts-node`:

https://github.com/github/linguist/blob/775b07d40c04ef6e0051a541886a8f1e30a892f4/lib/linguist/languages.yml#L5595-L5602

**Comment by rafmst** [comment]
That explains it, I will try to fix it like you suggested. Thanks for the help, have a nice weekend 😁

**Comment by pchaigno** [comment]
@lildude I associated the `node` interpreter with TypeScript in #4261. When did we remove that?

**Comment by lildude** [comment]
When @Alhadis merged https://github.com/github/linguist/pull/4470 😁 

The OP of the PR states:

> **UPDATE:** This PR's been updated to remove `node` from TypeScript's interpreters list as well, following [conversation](https://github.com/github/linguist/issues/4469#issuecomment-475683753) between @pchaigno and @grant. Merging this PR will now also fix #4469.
