### ISSUE TITLE
.gitattributes file is ignored on GitHub

### ISSUE THREAD

**Issue by DanChaltiel** [github/linguist#4927]
## Preliminary Steps

Please confirm you have...
- [x ] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I use a GitHub Pages website to document an `R` package. This generates a lot of HTML files in a "docs" folder, that represent only documentation.

Reading the documentation, I overrode this behavior using a .gitattributes file saying only `docs/* linguist-documentation`.

However, this had absolutely no effect, and my GitHub repository still shows a 97.8% HTML language distribution.

This is rather unexpected, as a similar repo used the exact same .gitattributes, and the language is rightly identified as `R`: https://github.com/davidgohel/flextable/blob/master/.gitattributes

I tried to refine this and add `docs/reference/* linguist-documentation` or switch to `linguist-vendored` but it was obviously unsuccessful.

**Comment by lildude** [comment]
You don't need the `.gitattributes` at all because Linguist already considers everything under `docs/` as documentation:

https://github.com/github/linguist/blob/99a06bad587cee7426aab26656d2ef37e1cf8202/lib/linguist/documentation.yml#L10-L12

Your changes are also having no effect because your high HTML count is due to one massive HTML file: https://github.com/DanChaltiel/crosstable/blob/master/pkgdown/index.html

It's 6.9MB on it's own, which far outweighs the amount of R code in your repo.

**Comment by DanChaltiel** [comment]
Oh, I see, sorry for the false alert
