### ISSUE TITLE
ReasonML files classified as C++

### ISSUE THREAD

**Issue by jisensee** [github/linguist#4930]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Some Reason-files are classified as C++ for no apparent reason (no pun intended). I can't make out any pattern in this, the majority is being classified correctly.
Explicitly mapping *.re files to Reason in .gitignore doesnt seem to make any difference here.

### URL of the affected repository:
https://github.com/jisensee/charly/
However, I have seen this issue is other repos as well.

### Last modified on:
2020-07-25

### Expected language:
ReasonML

### Detected language:
C++

**Comment by lildude** [comment]
This will be because the `.re` extension is associated with both Reason and C++ and we don't have a heuristic for the extension so we fall back to the naïve Bayesian classifier which is making a guess based on the limited samples we have.

If you're up for it, please feel free to submit a PR implementing a heuristic to help improve the language detection.

> Explicitly mapping *.re files to Reason in .gitignore doesnt seem to make any difference here.

This should be in the `.gitattributes`, but I see you've worked this out already 😉

**Comment by jisensee** [comment]
Alright, thanks for the explanations, makes sense to me.

Me saying I put the override in .gitignore was just a typo, it was late 😛 
After adding it I have 100% Reason shown on the repo but when I check the breakdown of files, I still see some classified as C++ there. That seems weird to me or do I understand the override mechanism wrong? I would expect both views to be in sync.

**Comment by lildude** [comment]
Yeah, that difference is because you're looking at the indexed search results which as you can see haven't been reindexed for a few days. We don't go back and retrospectively update all files if you change the language in `.gitattributes` file. The search index will be updated as you touch the files though.

**Comment by smola** [comment]
Bump.
