### ISSUE TITLE
Misclassified language

### ISSUE THREAD

**Issue by flybd5** [github/linguist#4939]
## Problem Description

Linguist does not pick up on .yml files in my repo

### URL of the affected repository:

https://github.com/flybd5/ansible-role-aws-rds

### Last modified on:

2020-08-03

### Expected language:

YAML

### Detected language:

Python

**Comment by flybd5** [comment]
* linguist-vendored
*.yml linguist-vendored=false

...in .gitattributes fixed the problem. This tool needs work.

**Comment by lildude** [comment]
> Linguist does not pick up on .yml files in my repo

It most definitely does, but YAML is considered data by Linguist by default so is _not_ included in the language statistics:

https://github.com/github/linguist/blob/96ad1185828f44bb9b774328a584551ee57ed264/lib/linguist/languages.yml#L6225-L6231

The reason your repo was showing predominantly as Python is because of this file: https://github.com/flybd5/ansible-role-aws-rds/blob/master/filter_plugins/get_attr.py

Your override has simply marked everything in your repo as vendored so _none_ of your files are considered in the language statistics.

If you really want your YAML files to be counted, you can implement a [detectable](https://github.com/github/linguist#detectable) override. If you were to implement just detectable override for `.yml` files in your repo and remove all of your vendored overrides, you can get a breakdown of:

```console
$ github-linguist . --breakdown
92.49%  YAML
5.00%   Python
2.52%   Makefile

Makefile:
Makefile

YAML:
defaults/main.yml
meta/main.yml
tasks/_facts_subnet_by_filter.yml
tasks/create_rds.yml
tasks/create_rds_paramgroup.yml
tasks/create_rds_subnet.yml
tasks/gather_facts_subnets.yml
tasks/main.yml

Python:
filter_plugins/get_attr.py
$
```

> This tool needs work.

No it doesn't. It's working as designed. 😁

**Comment by flybd5** [comment]
> ...but YAML is considered data by Linguist by default...

...and that is why the tool needs work, an outright incorrect design assumption. In Ansible, YAML -is- the code. :)

**Comment by pchaigno** [comment]
> > This tool needs work.
> 
> No it doesn't. It's working as designed. grin

I think I agree with @flybd5. Linguist needs work, like all software :-)

> ...and that is why the tool needs work, an outright incorrect design assumption. In Ansible, YAML -is- the code. :)

Yes, we're aware of that issue. Ansible YAML is code, but most YAML files are data. We would welcome a PR to differentiate Ansible YAML from other YAML files. In the meantime, please use overrides.

**Comment by flybd5** [comment]
From my point of view, it doesn't make any difference if YAML is being used for data or for code. Correctly representing the content of a repo without requiring the owner of the repo to jump unnecessary hoops is more important. It's all about the user experience vs. the religious preferences of the developer. :)

**Comment by pchaigno** [comment]
> Correctly representing the content of a repo without requiring the owner of the repo to jump unnecessary hoops is more important. It's all about the user experience vs. the religious preferences of the developer. :)

I agree, but that requires distinguishing some languages and isn't always easy.

> But now someone apparently disabled Linguist entirely from my repo. Interesting development.

Care to detail? :-)

**Comment by lildude** [comment]
> But now someone apparently disabled Linguist entirely from my repo. Interesting development.

You effectively did with this line: https://github.com/flybd5/ansible-role-aws-rds/blob/870b418e5d9b544f25299c1f594ee3c105e7a664/.gitattributes#L1

From my earlier response:

> Your override has simply marked everything in your repo as vendored so none of your files are considered in the language statistics.

**Comment by flybd5** [comment]
The linguist analysis disappeared.

@lildude When I made that change I refreshed my browser page and it did exactly what I wanted it to do. The analysis was then correct. Since then the entire analysis has disappeared.

**Comment by lildude** [comment]
> @lildude When I made that change I refreshed my browser page and it did exactly what I wanted it to do. The analysis was then correct. Since then the entire analysis has disappeared.

The analysis of a repo is performed by a background job that can take some time to run, depending on how busy GitHub's job servers are at the time - they're busier during US work hours than EU mornings so can take longer to run then. 

The first change which you say had the desired effect would be due to one of the 6 commits you made to your `.gitattributes` before the final commit which is the one taking effect now.

Looking at your commit history, we can see that it's your final commit at https://github.com/flybd5/ansible-role-aws-rds/commit/870b418e5d9b544f25299c1f594ee3c105e7a664 that "broke" things:

```diff
- tasks/*.yml linguist-detectable
- filter_plugins/*.py -linguist-vendored
+ * linguist-vendored
+ *.yml linguist-vendored=false
```

The first line (`tasks/*.yml linguist-detectable`) is what would have made some of your YAML files count in the language stats and show YAML in the list of languages.

You removed that and replaced it with `* linguist-vendored` which marked everything as vendored and `*.yml linguist-vendored=false` which tells Linguist to consider those files to _not_ be vendored, however they're not considered vendored normally, so this has no effect, thus putting your YAML files back to their default behaviour of being considered data and thus "undetectable".

The commit before the last (https://github.com/flybd5/ansible-role-aws-rds/commit/b8da8598c85882d7f07141aa9b56f6aa1f9717c8) is the one that made YAML visible in the language stats and it would have been after the analysis kicked off by this commit that you most likely noticed things working as you expect.

If you want a complete analysis of your repo displaying _all_ languages actually in the repo, including YAML, with it being the predominant language, which you are expecting, you can get this with this one line:

```
*.yml linguist-detectable
```

This will produce this in the sidebar:

![Screenshot 2020-08-04 at 10 16 00](https://user-images.githubusercontent.com/627280/89276516-a6ea2a00-d63b-11ea-88b2-ff755b38801a.png)

... and this in your list of repos:

![Screenshot 2020-08-04 at 10 16 18](https://user-images.githubusercontent.com/627280/89276533-ae113800-d63b-11ea-8f5f-f84d9e4ae963.png)

This was taken from my [fork of your repo](https://github.com/lildude/ansible-role-aws-rds) in which I've implemented just that line.

**Comment by flybd5** [comment]
Thank you for the complete explanation. That accomplished what I wanted. :)
