### ISSUE TITLE
Rust repo misclassified as RenderScript

### ISSUE THREAD

**Issue by ethanboxx** [github/linguist#4996]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

All of the Rust files in this repo are classified as RenderScript files. I saw #3998 but it does not look like the same issue as my files contain many of the keywords under Rust in the heuristics file.

### URL of the affected repository:

https://github.com/ethanboxx/rust-logging-examples

### Last modified on:

2020-08-25

### Expected language:
Rust

### Detected language:
RenderScript

**Comment by smola** [comment]
Your `examples` directory is ignored by linguist since it's considered documentation. You can override this behavior ([docs](https://github.com/github/linguist#documentation)). The only detected file is `src/main.rs` Given its length, it's going to be hard to get linguist to classify it correctly. You can also override this ([docs](https://github.com/github/linguist#using-gitattributes)).

In short, you can add `.gitattributes` to your repository with something like this:

```
/examples/** -linguist-documentation
*.rs linguist-language=Rust
```

**Comment by ethanboxx** [comment]
Thank you very much for your detailed help. This `gitattributes` setup 100% fixed my issue so I will close this.
