### ISSUE TITLE
.al files are associated with Perl, and not the AL language (D365 BC)

### ISSUE THREAD

**Issue by borisimple** [github/linguist#5010]
All repositories on the GitHub with Dynamics 365 Business Central projects, will show that the language used is Perl, and not AL.

Under you will find only one example, but literally every repository is affected. -> [Waldo repo](https://github.com/waldo1001/waldo.restapp)

Based on [#2362](https://github.com/github/linguist/issues/2362), .al extension is used for *Perl autoload files*.

**Comment by Alhadis** [comment]
@borisimple Could you include some links to AL language documentation? That way we'll have something to use when filtering search results to determine whether it's eligible for support by GitHub/Linguist.

**Comment by borisimple** [comment]
@Alhadis [Here's the link](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-reference-overview)

**Comment by Alhadis** [comment]
Thanks. I also found the [relevant repository](https://github.com/microsoft/AL) on GitHub, which provides a syntax highlighting grammar we can use (provided it meets eligibility).

**Comment by Alhadis** [comment]
Ugh, I didn't notice that [we already support it](https://github.com/search?l=AL+Code&q=extension%3Aal+NOT+nothack+codeunit&type=Code) (I assumed the highlighting was coming from the Perl grammar…) That'll teach me for being lazy. 😅

In that case, we can solve this by adding a heuristic to match commonly-used AL constructs; [`codeunit`](https://github.com/search?l=AL+Code&q=extension%3Aal+NOT+nothack+codeunit&type=Code) looks tempting, but we'd need to be very specific about how it's matched, since it's easy to match valid Perl code, too.

**Comment by borisimple** [comment]
Hmm, it seems that I did not research it well, as somebody already did this a few days ago!

**Add Microsoft AL Code Language #4916**

**Comment by Alhadis** [comment]
Currently, the AL language entry is named **AL code**, which sounds redundant. Should we rename it to simply **AL**…?

**Comment by borisimple** [comment]
I think that would be great!

**Comment by lildude** [comment]
> Hmm, it seems that I did not research it well, as somebody already did this a few days ago!
> 
> **Add Microsoft AL Code Language #4916**

Yup, and it's already live on GitHub.com

> Under you will find only one example, but literally every repository is affected. -> [Waldo repo](https://github.com/waldo1001/waldo.restapp)

This will be because the repo hasn't been touched since support was added. We do not go back and reassess every repo when we make a new Linguist release as it would be incredibly resource intensive for little gain. That, and any other AL repo, will be re-analyzed the next time a change is pushed.

**Comment by borisimple** [comment]
@lildude 

This makes sense now. Thanks for the feedback.

Although it would still be nice that extension is called "AL" only instead of "AL Code" 😏

I am closing this issue now.
