### ISSUE TITLE
Submodule somehow affects language percentage

### ISSUE THREAD

**Issue by softmarshmallow** [github/linguist#5043]
I think it's a bug. when i click js, no files will appear.
It was 100% ts, after adding submodule it got js.

https://github.com/bridgedxyz/assistant

Just to confirm the case. once confirmed, I'll open a new issue.

![image](https://user-images.githubusercontent.com/16307013/95731907-0a877800-0cbb-11eb-9341-cb0ea914a02a.png)

**Comment by lildude** [comment]
Thanks for opening a new issue @softmarshmallow 

In the time, I've cloned your repository and I can confirm this isn't a Linguist issue, nor is it due to your addition of a submodule.

From your repo, I can see the submodule you've added is at the path `packages/flutter-builder`.

If I perform an analysis of your repo, we can see these files are responsible for the Javascript in the stats:

```
$ github-linguist . --breakdown
94.78%  JavaScript
4.76%   TypeScript
0.25%   Dart
0.06%   Pug
0.05%   HTML
0.05%   Swift
0.04%   CSS
0.01%   Kotlin
0.00%   Objective-C

[... truncated for brevity ...]

JavaScript:
figma/webpack.config.js
sketch/assistant.sketchplugin/Contents/Sketch/__my-command.js
sketch/src/my-command.js
zeplin/src/fixtures/index.js
zeplin/src/index.js
zeplin/src/index.test.js

[...]
```

As you can see, none of those files are in the submodule path so it isn't responsible. Looking at your commit history, I can see why you think it is the addition of the submodule that caused this. It's because you added this very large file in the same [commit](https://github.com/bridgedxyz/assistant/commit/7437aa884d480136e408ffc0e0d3a88f565b9475) as adding the submodule.

The high percentage being attributed to Javascript is because this file is very large at 2.21MB:

- [`sketch/assistant.sketchplugin/Contents/Sketch/__my-command.js`](https://github.com/bridgedxyz/assistant/blob/7437aa884d480136e408ffc0e0d3a88f565b9475/sketch/assistant.sketchplugin/Contents/Sketch/__my-command.js)

The search will never index this file because it is over 384kb, but Linguist will still count it in the statistics.

You'll need to use an override if you don't want this or other files to be counted in the stats.

Going back to you point initial point:

> when i click js, no files will appear

This is completely unrelated to Linguist. 

When you click the language, you are actually performing a `language:Javascript` search within your repository (look at the URL).  As it is not returning anything, it indicates the search index for your repository hasn't been fully updated yet. If I [search for all files with the `.js` extension](https://github.com/bridgedxyz/assistant/search?q=extension%3Ajs+NOT+nothack), I get the six files listed from my CLI analysis above so some of the content has been indexed, but not all. I'm not sure why this happens, but it normally corrects itself as you push more code.

**Comment by softmarshmallow** [comment]
Oh, I see. sorry to waste your time. really sorry. Thanks for helping me out!

**Comment by lildude** [comment]
> Oh, I see. sorry to waste your time. really sorry. Thanks for helping me out!

No problem. You're welcome.
