### ISSUE TITLE
"AL" language is not being recognised

### ISSUE THREAD

**Issue by matthewmartin-nvg** [github/linguist#5044]
Please see the pull requests where the "AL" language was added:
-- https://github.com/github/linguist/pull/4916
-- https://github.com/github/linguist/pull/5023

### Expected language:
AL

### Detected language:
Perl

### Example page:
https://github.com/Navengers/TotalFitness
-- has multiple subfolders with ".al" files.

**Comment by lildude** [comment]
Your repo is private so we can't see what you're trying to point out. 

One thing to keep in mind is that a repo will _not_ be re-analysed after a Linguist update. If you've not pushed any content since those two PRs were merged and the new Linguist release made (v7.11.1 was made on 2 Oct and went live on GitHub.com later that day), you will need to push code for your repo to be reanalysed.

**Comment by lildude** [comment]
Whilst I can't view your repo content, I can see from the backend side of things that your repo is now showing  your repo is predominantly made up of files identified as "AL" so I'm going to close this issue.
