### ISSUE TITLE
beef files detected as HyPhy or brainfuck

### ISSUE THREAD

**Issue by C34A** [github/linguist#5066]
## Problem Description
Any file ending in .bf seems to get marked as HyPhy or brainfuck, usually incorrectly. This primarily affects beef repos, but I was able to find [this repo](https://github.com/laboon/esolangs) containing code in something called befunge which is also affected, though this matters more for beef.

### URL of the affected repository:
every beef repo as far as I can tell. for example:
https://github.com/beefytech/beef
https://github.com/MineGame159/glfw-beef
https://github.com/qzole/imgui-beef
### Last modified on:

2020-10-23
### Expected language:

beef
### Detected language:

HyPhy or brainfuck

**Comment by lildude** [comment]
This would be because Linguist doesn't know about Beef and only associates the `.bf` extension with HyPhy or brainfuck.

In order for your files to be identified as beef, Linguist would need to be taught all about it. It the `.bf` extension for Beef is sufficiently popular for inclusion (see the CONTRIBUTING.md file), we'd appreciate a pull request to add support.

**Comment by Nixinova** [comment]
Usage seems to check out; [keyword using](https://github.com/search?q=extension%3Abf+%22using%22&type=) gives just under 3K results. Will make a PR.
