### ISSUE TITLE
CSS file not detected

### ISSUE THREAD

**Issue by ABHISHEK-G0YAL** [github/linguist#5073]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

My CSS file is not at all being shown by linguist, I have tried 2 overrides :- 
1. Manually marking file to be CSS
2. Making all files vendored=false

### URL of the affected repository:
https://github.com/ABHISHEK-G0YAL/Hacktoberfest-2020

### Expected language:

HTML, CSS, js

### Detected language:

HTML, js

**Comment by lildude** [comment]
Linguist is detecting your CSS file as generated because your average line length is over 110 chars which is quite common in minified CSS files.

Your two `background-image: url("data:image/png;base64,...` lines are heavily swaying this calculation.

You can override this by using the generated override: `* -linguist-generated` or `* linguist-generated=false`.

**Comment by ABHISHEK-G0YAL** [comment]
Thank for you help, I would try overriding it as you suggested.
