### ISSUE TITLE
files are just don't considered in the whole repo

### ISSUE THREAD

**Issue by darkRaspberry** [github/linguist#5082]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description
Files are not considered for language detection.

### URL of the affected repository:
https://github.com/darkRaspberry/Forest

### Expected language:
All files are (including in docs folder) should considered for languages %

### Detected language:
none in docs folder only.

**Comment by darkRaspberry** [comment]
I have locally tested and found that docs are not considered or linguist can't see docs files

**Comment by darkRaspberry** [comment]
i have moved files to different place still no response

**Comment by lildude** [comment]
As you've correctly identified, your files are not being considered for the language stats because they're in the `docs` folder and thus being determined by Linguist as documentation thanks to:

https://github.com/github/linguist/blob/5da91555329a1371a602f10a9719439219d280de/lib/linguist/documentation.yml#L12

> I have moved files to different place still no response.

It should do, though you could have checked before the background job that does the analysis had run. Your commit history doesn't show any commits that moved the files either.

> I have locally installed linguist and it doesn't return anything. (It works with another repo).

Did you commit your changes? Linguist only acknowledges committed changes:

```console
$ git clone -q git@github.com:darkRaspberry/Forest.git
$ cd Forest/
$ github-linguist . --breakdown

$ git mv docs another-name
$ git commit -m 'Rename docs to another-name'
[main b3a0ec5] Rename docs to another-name
 7 files changed, 0 insertions(+), 0 deletions(-)
 rename {docs => another-name}/404.html (100%)
 rename {docs => another-name}/CNAME (100%)
 rename {docs => another-name}/index.html (100%)
 rename {docs => another-name}/static/assets/css/css.css (100%)
 rename {docs => another-name}/static/assets/img/gatewayTree.png (100%)
 rename {docs => another-name}/static/assets/js/transit.js (100%)
 rename {docs => another-name}/static/assets/js/ui.js (100%)
$
$ github-linguist . --breakdown
76.75%  JavaScript
18.63%  HTML
4.62%   CSS

HTML:
another-name/404.html
another-name/index.html

CSS:
another-name/static/assets/css/css.css

JavaScript:
another-name/static/assets/js/transit.js
another-name/static/assets/js/ui.js

$
```

You can also implement an override to force your `docs` directory to be considered, but there's a catch: you're also using a path that matches a "vendored" path...

https://github.com/github/linguist/blob/5da91555329a1371a602f10a9719439219d280de/lib/linguist/vendor.yml#L242

... so you need to implement two overrides if you're going to keep the `docs` directory name. Carrying on from the illustration above:

```console
$ git revert HEAD
[main 571ec80] Revert "Rename docs to another-name"
 7 files changed, 0 insertions(+), 0 deletions(-)
 rename {another-name => docs}/404.html (100%)
 rename {another-name => docs}/CNAME (100%)
 rename {another-name => docs}/index.html (100%)
 rename {another-name => docs}/static/assets/css/css.css (100%)
 rename {another-name => docs}/static/assets/img/gatewayTree.png (100%)
 rename {another-name => docs}/static/assets/js/transit.js (100%)
 rename {another-name => docs}/static/assets/js/ui.js (100%)
$ github-linguist . --breakdown

$
$ echo '* -linguist-documentation' > .gitattributes
$ echo '* -linguist-vendored' >> .gitattributes
$ git add .gitattributes
$ git commit -m 'Implement Linguist overrides'
[main 06243c5] Implement Linguist overrides
 1 file changed, 1 insertion(+), 1 deletion(-)
$ github-linguist . --breakdown
76.75%  JavaScript
18.63%  HTML
4.62%   CSS

HTML:
docs/404.html
docs/index.html

CSS:
docs/static/assets/css/css.css

JavaScript:
docs/static/assets/js/transit.js
docs/static/assets/js/ui.js

$
```

**Comment by darkRaspberry** [comment]
Thanks
