### ISSUE TITLE
Detecting YAML format on Ansible repositories

### ISSUE THREAD

**Issue by julien-langlois** [github/linguist#5105]
## Problem Description

Since most repositories related to Ansible are mostly composed of YAML files, why is this not taken into account for language detection? 
It is often displayed HTML or Shell depending on the files present that are necessary for the roles or playbooks to work properly.

### URL of the affected repository:
https://github.com/geerlingguy/ansible-role-nginx

### Last modified on:
2020-12-07

### Expected language:
YAML

### Detected language:
Either HTML or Shell most of the time

**Comment by lildude** [comment]
> Since most repositories related to Ansible are mostly composed of YAML files, why is this not taken into account for language detection?

Because YAML isn't considered a programming language by Linguist (note: `type: data`) and as such is ignored when calculating the statistics:

https://github.com/github/linguist/blob/633d196c170e002bcccb4143d6906787f360e08b/lib/linguist/languages.yml#L6357-L6383

If you really want your repo to count the YAML files, you can implement the [detectable](https://github.com/github/linguist#detectable) override.
