### ISSUE TITLE
Delphi file reported as PHP

### ISSUE THREAD

**Issue by EricGrange** [github/linguist#5115]
The following Delphi/Pascal file is being reported a PHP in GitHub
https://github.com/EricGrange/cefHtmlSnapshot/blob/main/cef.inc

## Problem Description

The following Delphi/Pascal file is being reported a PHP in GitHub as seen in
https://github.com/EricGrange/cefHtmlSnapshot/search?l=php

### URL of the affected repository:
https://github.com/EricGrange/cefHtmlSnapshot/blob/main/cef.inc

### Expected language:
Delphi or Pascal

### Detected language:
PHP

**Comment by Alhadis** [comment]
Why did you remove the checklist from the issue template?

**Comment by lildude** [comment]
Ditto to what @Alhadis said; the checklist is for everyone's benefit so we know we're all starting on the same page in terms of basic knowledge of how Linguist works and how to control its behaviour. The rest of my comment is based on the basis you have read all the links.

As for the reason, this is happening because you're using the very generic `.inc` extension which is currently associated with 12 languages, _none_ of which are Delphi. 

As a result it is falling through to the heuristics:

https://github.com/github/linguist/blob/8fc4898d34dbe9323bc1bb7971652998d3d39b4f/lib/linguist/heuristics.yml#L227-L243

... which won't match your file so then things move on to the classifier which is taking a guess based on the languages Linguist knows about that have `.inc` extensions. As the extension is not associated with Delphi, we don't have a sample for the classifier to use for training, so it's made a guess based on what it does know.

If Delphi-specific usage is widespread enough, feel free to review the CONTRIBUTING.md file and submit a PR to associate this extension with Delphi.

In the mean time your only solution is to implement an override to force the language.

**Comment by EricGrange** [comment]
Sorry, TBH I removed it because I did not see it as a checklist to be submitted but more as a generic comment paragraph. :/

As for notability I ran a search the .inc extension and two common terms found in those (the major compilers), from a quick look the results are actual Delphi /Pascal files with no false positives in the first result pages

https://github.com/search?q=extension%3Ainc+delphi&type=Code    -> 19852 results
https://github.com/search?q=extension%3Ainc+fpc&type=Code   -> 44596 results

That is more than for some languages currently in the heuristics you cited, though much less than for PHP, as .inc is not a "main" extension for Delphi/Pascal, but more of a utility file, so there is just a few occurrences per project.

As for contribution, the contributing.md looks a bit too daunting...
In case someone wants to look at the subject, a very typical patterns found in Delphi/Pascal .inc files would be "{$define" or "{$ifdef" (both case insensitive, but very unlikely to be of a mixed case, if that can help performance for the classifier), with the "{$" being quite specific to Delphi/Pascal AFAIK.

Thanks!
