### ISSUE TITLE
PHP file shows up as Hack

### ISSUE THREAD

**Issue by JakeDarb** [github/linguist#5118]
## Preliminary Steps

Please confirm you have...
- [o] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x ] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I have written a program that mostly uses PHP. For some reason, GitHub thinks it is written in the Hack language.
I have this problem with 3 files: "index.php", "succes.php" and "failed.php".

### URL of the affected repository:
https://github.com/JakeDarb/Welzijnszorg_Sleutelhangers.git

### Last modified on:

2020-12-22

### Expected language:

PHP

### Detected language:

Hack

**Comment by lildude** [comment]
This is happening because your PHP files aren't really 😁

As they have a `.php` extension, they match two languages: PHP and Hack, which means we fall through to the heuristics to determine if this is PHP or Hack:

https://github.com/github/linguist/blob/8fc4898d34dbe9323bc1bb7971652998d3d39b4f/lib/linguist/heuristics.yml#L231-L232

But, as your files contain _no_ PHP at all, the heuristic doesn't match for PHP so falls through to the classifier which makes a guess based on the content of your files and the samples Linguist has, and it has guessed Hack.

There are two solutions:

- write some PHP into your files 😉... given how new your repo is, I suspect your plan to do this soon
- implement a language override to force PHP on all `.php` files regardless of content

Or, save on server processing and use `.html` as the extension as that is all these files contain.
