### ISSUE TITLE
Add support for hash sum files (tools like sha256sum)

### ISSUE THREAD

**Issue by theonlypwner** [github/linguist#5130]
Tools like `md5sum`, `shasum`, `sha1sum`, `sha256sum`, `sha3sum`, and `b2sum` output one line per input file:
- hash digest in hexadecimal
- space
- space or asterisk (indicates text or binary mode, respectively)
- file name
- newline

If the file was stdin, the file name is `-`.

For example, in binary mode, the output looks like this:
```
0000000000000000000000000000000000000000 *file0
0000000000000000000000000000000000000001 *file1
```

In text mode, the output looks like this:
```
0000000000000000000000000000000000000000  file0
0000000000000000000000000000000000000001  file1
```

`cksum` is similar, but it outputs the checksum in decimal, a space, the file size (with all trailing null bytes trimmed), a space, and the file name. If the file was stdin, the last two parts are omitted.

**Comment by theonlypwner** [comment]
[Ubuntu uses `SHA256SUMS`](https://help.ubuntu.com/community/HowToSHA256SUM) as the file name.

The list should include file names for various hashes (MD5, SHA1, SHA224, SHA256, SHA384, SHA512, etc.) like
- \<HASH>
- \<HASH>.txt
- \<hash>.txt
- \<HASH>SUM
- \<HASH>SUMS

plus file names that do not include the hash type, like
- CHECKSUM.txt
- CHECKSUMS.txt

It should also support \``` blocks, possibly something like one of these: \```hash, \```sum, \```sums

**Comment by Alhadis** [comment]
@theonlypwner If you feel like submitting a pull-request, I've added a [basic grammar](https://github.com/Alhadis/language-etc/commit/2f8309a73fcffcd82ebf158e8c202d6a3ae31f80) that highlights checksum lists. Since the `language-etc` repository is already used by Linguist, there's no need to add a new submodule (although you may need to bump the submodule's commit).

**Comment by theonlypwner** [comment]
What changes need to be made to Linguist? Is it just adding an entry to 3 files (`lib/linguist/languages.yml`, `grammars.yml`, `vendor/README.md`) and updating the submodule `vendor/grammars/language-etc`?

Also, in Alhadis/language-etc@2f8309a73fcffcd82ebf158e8c202d6a3ae31f80, would `(?=\\S{24})` work for short hashes? For example, cksum might output `0 4 filename` or `0 4` (for 4 bytes from stdin that have a checksum of zero). Would another entry be needed to handle cksum, where the third capture group would be a file size instead of a file name? Should we just not support cksum?

**Comment by Alhadis** [comment]
> What changes need to be made to Linguist?

The process is documented in [`CONTRIBUTING.md` § Adding a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). It's okay if you don't have the time or motivation; I'm sure I'll get around to adding it when I have the time. 👍

The time-consuming part isn't so much the changes to Linguist, but researching in-the-wild usage using [Harvester](https://github.com/Alhadis/Harvester). Of course, that step becomes moot if a search tosses up a six-figure number of results, at which point we can safely assume there's 100+ users among them. 😉

> Should we just not support cksum?

Ah sorry, I could have been clearer on that point... it's common for checksum lists to contain blocks of prose before and/or after the actual checksums. I wasn't comfortable highlighting `cksum(1)` output, as it has a wide potential for errant matches. Consider a line of the form `date time some arbitrary string`:

	20200112 3 files removed john.doe

Such a line would match a CRC-32 of `20200112` for a 3-byte file named `files removed john.doe`. Whether it's computationally feasible isn't really relevant; it's better to have *no* highlighting than wrong highlighting. 😉

(Also, I reasoned that cyclic redundancy checks are the least likely to be stored on-disk, since CRCs are fast to compute—it would behove authors to pick a secure algorithm if they wanted to prepare a checksum list ahead-of-time).

**Comment by theonlypwner** [comment]
My Ruby environment has issues, and I don't have time to fix them right now. I added it manually in a draft PR and will run the scripts after I fix the issues.

I asked
> Should we just not support cksum?

because I was wondering whether it'll be too tricky to support, with the false positives. It looks like we shouldn't detect it, but is there a way to highlight it when it is explicitly specified, such as \```hash blocks in Markdown?

**Comment by Alhadis** [comment]
> but is there a way to highlight it when it is explicitly specified, such as ```hash blocks in Markdown?

Unfortunately not. ` ```hash ` blocks are highlighted by the same mechanism responsible for highlighting a file's source-code. For all intents and purposes, they're exactly the same.

**Comment by smola** [comment]
Would it make sense to cover single-hash files that are usually identified with the extension (e.g. `xxx.sha1`, `xxx.md5`)?

**Comment by theonlypwner** [comment]
Yes, I've added entries under `extensions`.

**Comment by theonlypwner** [comment]
> Unfortunately not. `` ```hash `` blocks are highlighted by the same mechanism responsible for highlighting a file's source-code. For all intents and purposes, they're exactly the same.

Don't the blocks below highlight differently? One is a ` ```c ` block, and the other is a ` ```html ` block.

```c
int main() {} // <strong attr="val">HTML</strong>
```

```html
int main() {} // <strong attr="val">HTML</strong>
```
