### ISSUE TITLE
C# Detected as Smalltalk!

### ISSUE THREAD

**Issue by kirtan0000** [github/linguist#5141]
## Problem Description

I have a project with c# files but on GitHub it says that the language fir the extension .cs is Smalltalk.

On other repos it shows as c# but on this repo it is Smalltalk?

### URL of the affected repository:

https://github.com/kirtan0000/Pizza-Clicker/

### Last modified on:

2021-01-14

### Expected language:

C#

### Detected language:

Smalltalk

**Comment by lildude** [comment]
🤔 you've not stated which file(s) and now you have an override we can't see it in action either.

That said, I've downloaded your repo, emptied the `.gitattributes` and everything is reporting as C#:

```console
[~/t/trash]$ git clone -q git@github.com:kirtan0000/Pizza-Clicker.git
[~/t/trash]$ cd Pizza-Clicker/
[~/t/t/Pizza-Clicker master ●]$ echo > .gitattributes
[~/t/t/Pizza-Clicker master ●]$ git commit -am 'No over'
[master 7cc2a32] No over
 1 file changed, 1 deletion(-)
[~/t/t/Pizza-Clicker master]$ github-linguist . --breakdown
100.00% C#

C#:
Assets/Scripts/Click.cs

[~/t/t/Pizza-Clicker master]$
```

Looking through your history, I can see why this has happened: it's because all your files were stored on LFS which means each file is actually a pointer to the code and not the actual code:

```console
[~/t/t/Pizza-Clicker master]$ git checkout -q 93da694
https://git-lfs.github.com/spec/v1 is not a valid attribute name: .gitattributes:1
sha256:509c125aa04560abe851d57aa3367cf77b945df385cf25751a7c6b4d8be01338 is not a valid attribute name: .gitattributes:2
[~/t/t/Pizza-Clicker (93da694f…)]$
[~/t/t/Pizza-Clicker (93da694f…)]$ /bin/cat Assets/Scripts/Click.cs
version https://git-lfs.github.com/spec/v1
oid sha256:de93e2d1b3b6aebcd040332e5817f62d5254cc840d85e70e600dbc30c6538fd6
size 11719
[~/t/t/Pizza-Clicker (93da694f…)]$ LINGUIST_DEBUG=2 github-linguist Assets/Scripts/Click.cs
Click.cs: 3 lines (3 sloc)
  type:      Text
  mime type: text/plain
                          #        C# Smalltalk
                     -    1         -     8.386
                 https    1     7.319         -
                  size    1         -     9.616
               version    1         -     6.828
        C# =   -108.043 +  -5.998 =   -114.040
 Smalltalk =    -90.533 +  -5.487 =    -96.020
  language:  Smalltalk
[~/t/t/Pizza-Clicker (93da694f…)]$
```

As the content doesn't match the heuristics:

https://github.com/github/linguist/blob/9edd34988273d307180a1bfc4dfa30a9f2f79105/lib/linguist/heuristics.yml#L117-L122

... the analysis has fallen through to the classifier and used the samples of these two languages to make a guess, and as you can see above, the best guess it could make was that the pointer info looks more like Smalltalk than C#.

Your repo is no longer showing Smalltalk without an override because you've removed the LFS references which means you can remove your `.gitattributes` and `.gitignore` files too; they're not having any impact on the analysis now you've removed the LFS files:

```console
[~/t/t/Pizza-Clicker (93da694f…)]$ git checkout -q master
https://git-lfs.github.com/spec/v1 is not a valid attribute name: .gitattributes:1
sha256:509c125aa04560abe851d57aa3367cf77b945df385cf25751a7c6b4d8be01338 is not a valid attribute name: .gitattributes:2
[~/t/t/Pizza-Clicker master]$ git rm .gitattributes .gitignore
rm '.gitattributes'
rm '.gitignore'
[~/t/t/Pizza-Clicker master ●]$ git commit -m 'Remove'
[master 7d88b14] Remove
 2 files changed, 63 deletions(-)
 delete mode 100644 .gitattributes
 delete mode 100644 .gitignore
[~/t/t/Pizza-Clicker master]$ github-linguist . --breakdown
100.00% C#

C#:
Assets/Scripts/Click.cs

[~/t/t/Pizza-Clicker master]$
```

When repos are stored on the GitHub servers, they contain the pointer info, not the destination source code, so analysis is performed on those files. The destination files are not considered at all, and never will be, as LFS is designed to be used to store large (and often binary) files and GitHub doesn't index or analyse very large or binary files.
