### ISSUE TITLE
Linguist vendored not acting as expected?

### ISSUE THREAD

**Issue by Therkelsen** [github/linguist#5250]
I have [a C++ repo](https://github.com/Therkelsen/CPP-Learning) for my uni C++ class, but it's showing a bunch of other languages that I don't want shown. I've previously used `linguist-vendored=true` to have it exclude specific file extensions from being vendored, but it doesn't seem to work [here](https://github.com/Therkelsen/CPP-Learning/blob/main/.gitattributes).

**Comment by lildude** [comment]
> I've previously used `linguist-vendored=true` to have it exclude specific file extensions from being vendored, but it doesn't seem to work [here](https://github.com/Therkelsen/CPP-Learning/blob/main/.gitattributes).

That's because that's not what you've done in that repo; you've done the complete opposite: 😁 

```
*.c linguist-vendored=false
*.cmake linguist-vendored=false
*.make linguist-vendored=false
*.xml linguist-vendored=false
```

You're telling Linguist to _not_ consider all of these files as vendored so it _will_ count them. If you don't want them to be counted, you need to use `true` or completely remove `=false` (which implies true) instead.

**Comment by lildude** [comment]
I see you've now fixed your config. Closing.
