### ISSUE TITLE
Syntax highlighting for Kotlin stops working after viewing a large amount of files in a pull

### ISSUE THREAD

**Issue by l1ving** [github/linguist#5252]
## Describe the bug
After viewing a large amount of files in a pull request, the syntax highlighting just stops working. I've mostly experienced this once I hit around ~200 viewed files but in some cases it can happy with much less files. In the attached screenshot it's only after about 55 viewed files.

### Expected behaviour
The syntax highlighting kept working no matter how many files you viewed.

### Related discussion
You can view an example pull request here: https://github.com/kami-blue/client/pull/1773

### Additional notes

![image](https://user-images.githubusercontent.com/17222512/110196086-25948900-7e10-11eb-9aa0-511e9e0c084c.png)
![image](https://user-images.githubusercontent.com/17222512/110196090-2e855a80-7e10-11eb-8252-11027d070af4.png)

**Comment by lildude** [comment]
Unfortunately, this isn't due to Linguist or the grammar it uses as the highlighting works on the files in isolation and if you use split-diff:

![CleanShot 2021-03-08 at 09 52 24](https://user-images.githubusercontent.com/627280/110304906-08b8ab00-7ff4-11eb-93dd-289508d68369.png)

This looks to be an issue with the way the GitHub site itself handles such a scenario. I'd suggest you use the "Contact GitHub" link from the PR page showing the problem to contact GitHub support.

**Comment by l1ving** [comment]
Thank you, I'll close this in a minute once I do so
