### ISSUE TITLE
.gitattributes linguist-generated no longer working

### ISSUE THREAD

**Issue by myitcv** [github/linguist#5288]
## Describe the bug

The following PR changes:

https://github.com/govim/govim/pull/1065/files

shows the diffs of files within the `cmd/govim/internal/golang_org_x_tools` directory fully expanded by default:

![Screen Shot 2021-03-26 at 05 24 32](https://user-images.githubusercontent.com/3374574/112586375-9fa6a500-8df3-11eb-874a-011d68145add.png)

Despite the current `.gitattributes` for the project marking those files as generated:

https://github.com/govim/govim/blob/720525cdb19cd36f2fbc0f05baa7bf75928d0b4b/.gitattributes#L1

### Expected behaviour

Per previous PRs in this project, for the `cmd/govim/internal/golang_org_x_tools` to not be automatically expanded in the diff, but instead to show the message:

```
Generated files are not shown by default.
```

(although interestingly, looking at those PRs _now_ those files show as expanded... so it looks like a more general problem as opposed to a specific one with this PR in this project)

### Related discussion

n/a

### Additional notes

n/a

**Comment by lildude** [comment]
🤔 _if_ this was working before and not now, then it has nothing to do with Linguist as this side of things hasn't changed in Linguist in a long time. I've also not made an update since I released v7.13.0.

That all said, I'm doubtful it worked before because the override isn't recursive:

```gitattributes
cmd/govim/internal/golang_org_x_tools/* linguist-generated
```

This means the override will only apply to files in that specific directory. The files you've modified are in a subdirectory of that directory so aren't affected - `cmd/govim/internal/golang_org_x_tools/jsonrpc2_v2`.

You can see that this is the case in the draft PR - https://github.com/lildude/govim/pull/1/files -  I've made against a fork of the repo in which I'm reverting your commit.

Without the change to the `gitattributes` the full diff showed as you've reported. Now I've put the correction for the `gitattributes` in place, the PR suppresses the diffs as you expect.

**Comment by myitcv** [comment]
Hi @lildude, thanks for the analysis.

> I'm doubtful it worked before because the override isn't recursive

Very interesting. I'm certain this was working before, and by working I mean the files were not auto-expanded in the diff. @leitzler will be able to confirm. Reason being, this particular kind of PR is the update of a vendored translation of a dependency, and we do them fairly regularly, always checking the diff in order to confirm whether or not there are any changes outside of the vendored code in a given PR (that would need specific review):

https://github.com/govim/govim/pulls?q=is%3Apr+%22deps%3A+update%22+is%3Aclosed+

So we would have noticed if this was broken before now.



> I've also not made an update since I released v7.13.0.

So this perhaps points to a change/fix elsewhere. 



> Without the change to the `gitattributes` the full diff showed as you've reported. Now I've put the correction for the `gitattributes` in place, the PR suppresses the diffs as you expect.

Wonderful, thank you for demonstrating the proper way of doing this. I'm totally comfortable therefore that this issue is not a real problem and instead needs to be fixed on our side so will close this issue. But please feel free to re-open/re-title etc as you wish if you think there is something that needs to be tracked.

**Comment by leitzler** [comment]
> @leitzler will be able to confirm.

Yeah, I did notice this change yesterday as well. The diffs has been hidden the past months at least so something did change.

Thanks @lildude for the input on how `gitattributes` works!

**Comment by lildude** [comment]
Re...

> So this perhaps points to a change/fix elsewhere.

... and ...

> Yeah, I did notice this change yesterday as well. The diffs has been hidden the past months at least so something did change.

I've dug into the changes deployed over the past few days and the one that makes the most sense and could explain this correction in behaviour is we upgraded our internal copies of libgit2 and rugged to match those used upstream. I suspect this has pulled in a fix or two that has corrected this behaviour that we'd not noticed before.
