### ISSUE TITLE
Mustache

### ISSUE THREAD

**Issue by Yash-Singh1** [github/linguist#5297]
## Language name

`Mustache`

## URL of example repository

https://github.com/mustache/mustache

## URL of syntax highlighting grammar

https://github.com/atom/language-mustache

## Most popular extensions

- `mustache`
- `mo`

## Detected language

`HTML+Django`

**Comment by lildude** [comment]
Linguist already supports Mustache:

https://github.com/github/linguist/blob/736df2bb2a78ccc23115cdeb33aef31156f3efac/lib/linguist/languages.yml#L3509-L3518

If you're seeing files identified as `HTML+Django` it'll be because those files probably haven't been touched since Mustache was added and deployed to GitHub.com in Linguist v7.11.0 deployed to GitHub on 7 Sep 2020 or you're seeing the name in the search results.

If the latter, unfortunately, this is a problem with Search and not Linguist and Linguist has no control over this. My first few paragraphs in the response at https://github.com/github/linguist/discussions/5249#discussioncomment-428558 explains the Search issue.

As Mustache is already supported and correctly identifying files on GitHub.com, I'm going to close this issue. If you need help resolving identification with a particular repository, please start a new [Discussion](https://github.com/github/linguist/discussions).
