### ISSUE TITLE
Fluent language files are incorrectly identified as FreeMarker

### ISSUE THREAD

**Issue by sandalwoodbox** [github/linguist#5340]
## Language name

Fluent

## URL of example repository

https://github.com/FanvidDB/fanviddb-server

## URL of syntax highlighting grammar

https://github.com/projectfluent/fluent/tree/master/spec

## Most popular extensions

`.ftl`

## Detected language

FreeMarker

**Comment by alerque** [comment]
I was the one that reported this in #4026 and have looked into it several times since. There shouldn't be any barrier to this happening, there are plenty of repos out there that would benefit now. The only catch I know of is that it's a little tricky to find them and also a bit tricky to write a heuristic to disambiguate them from FreeMarker. Both FreeMarker and Fluent are designed as wrapper languages that can contain other syntax. Most typical FreeMarker files are XML based, but there don't have to be. It's a templating language that can be used in almost any other language. You could even have a Fluent language file that had FreeMarker tags or the other way around.

I've tried to work on a submission for this several times and keep getting stuck on how to write a working heuristic. I'm inclined to take the naive assumption that FreeMarker will always start with XML-ish tags and Fluent not and make people specify otherwise in their gitattributes if that is incorrect for their project, but there are a small handful of existing repos that will break.

If anybody wants to work on this I'd be happy to collaborate. Somebody with experience in Ruby and working with the Linguist build system (which seems crazy pants to me) would be quite handy, I've been stabbing in the dark.

**Comment by MikkCZ** [comment]
Yeah, Fluent can contain strings that contain code in any language, however the whole structure of the file is similar to properties, or YAML in some aspects.
