### ISSUE TITLE
.env.example is recognized as `Shell`

### ISSUE THREAD

**Issue by Zerotask** [github/linguist#5431]
## Describe the bug
I have a project written in pure Go with a single `.env.example` file. This file is listed as Shell, but that's wrong.

### Expected behaviour
Since Environment Variables are something special, they could be treated as a new language `Env` or just ignore it.

### Additional notes
Example: https://github.com/Zerotask/go-web-api
https://github.com/Zerotask/go-web-api/search?l=shell

**Comment by lildude** [comment]
> Since Environment Variables are something special, they could be treated as a new language Env or just ignore it.

🤔  I'm not sure that's really the right thing to do as they only apply to shells so it makes sense the files are classified as such. If you don't want it to count, you can implement an override.

**Comment by Zerotask** [comment]
> as they only apply to shells

That's not true.


Many env variables are read by several programming languages to use it for a program which has nothing to do with shells.

**Comment by lildude** [comment]
They do indeed read them but they almost always use them as they would environment variables. The file is also called `.env` suggesting it contains environment variables which are technically written in (Bourne) shell script. This file is also traditionally used for this precise purpose… setting environment variables and many many languages don't expect anything different, including your Go project thanks to the [godotenv](https://github.com/joho/godotenv) pkg which is…

> A Go port of Ruby's dotenv library (Loads environment variables from `.env`.)

**Comment by Zerotask** [comment]
>  The file is also called .env suggesting it contains environment variables which are technically written in (Bourne) shell script.

an `.env` file has nothing to do with bourne shell scripts. It's just a text configuration file format.

> setting environment variables and many many languages don't expect anything different, including your Go project thanks to the godotenv pkg which is…

This doesn't contradict with what I wrote. It's still a file format which is not a shell script. It's wrong to count it as `shell`.
As an alternative to my suggested `env`, you can also change `.env` files from `shell` to `text`

**Comment by lildude** [comment]
> an .env file has nothing to do with bourne shell scripts. It's just a text configuration file format.

It may be in your usage however it's way more than that and more on par with a shell script: https://github.com/bkeepers/dotenv#usage

**Comment by Alhadis** [comment]
It's actually *not* shell. I [wrote a grammar](7d9e4f8704ceeadd244b21eeb7ac69a9b2405f8b) for `dotenv` files quite recently, and was surprised by the number of syntactic discrepancies (particularly its wacky handling of quotes). Because `FOO = bar` is a legal variable assignment in a `dotenv` file, I'd pin the format as being closer to an INI file than a shell-script.

**Comment by lildude** [comment]
Really?  TIL. @Alhadis Could your experience be specific to the newer nodejs implementation you referenced in that commit as opposed to the original and older Ruby implementation which doesn't handle spaces etc like that? I guess that means all those others added as part of https://github.com/github/linguist/pull/4922 incorrect too then?

**Comment by Alhadis** [comment]
> Could your experience be specific to the newer nodejs implementation

@lildude Until I read your comment, I wasn't aware there even *was* a non-Node.js based implementation (Bear in mind I only learned of this pseudo-format a month ago in [`file-icons/icons#91`](https://github.com/file-icons/icons/issues/91)). From a squiz of the original `dotenv`'s readme, it appears the two implementations aren't mutually compatible:

~~~text
NODE_JS=This # isn't a comment
RUBY=But # This is a comment
~~~

However, the Ruby implementation isn't compatible with shell syntax, either:

<ol><li><details><summary><b><code>SECRET_HASH=something-with-a-#-hash</code></b></summary>

**Shell:**  
~~~console
$ export SECRET_HASH=something-with-a-#-hash
$ echo $SECRET_HASH
something-with-a-#-hash
~~~

**Ruby:**  
~~~ruby
require "dotenv"
Dotenv::Parser.call("SECRET_HASH=something-with-a-#-hash", true)
# => {"SECRET_HASH"=>"something-with-a-"}
~~~

</details></li><li><details><summary><b><code>9FRONT=yes</code></b></summary>

**Shell:**
~~~console
$ export 9FRONT=yes
-bash: export: `9FRONT=yes': not a valid identifier
~~~

**Ruby:**
~~~ruby
require "dotenv"
Dotenv::Parser.call("9FRONT=yes", true)
# => {"9FRONT"=>"yes"}
~~~

</details></li></ol>

Aside from bringing to mind [a famous quote](https://en.wikiquote.org/wiki/Unix#:~:text=Those%20who%20don't%20understand%20Unix%20are%20condemned%20to%20reinvent%20it,%20poorly.) by Henry Spencer, discrepancies like this convince me there's no standardised format for `.env` files any more than there is one for INI files. On that note, I have to question the wisdom in reimplementing a very narrow subset of shell syntax instead of simply exporting variables declared in an `.env` file before bootstrapping the `ruby` process… then again, maybe it's a Rails thing. 😉

**Comment by szepeviktor** [comment]
When overriding in gitattributes GitHub generates this HTML
```html
<table data-hpc class="highlight tab-size js-file-line-container js-code-nav-container js-tagsearch-file" data-tab-size="8" data-paste-markdown-skip data-tagsearch-lang="INI" data-tagsearch-path=".env.example">
```

Note the `data-tagsearch-lang="INI"` part. But its syntax highlight is definitely not `INI`.

**Comment by lildude** [comment]
Yes. This is being corrected in https://github.com/github/linguist/pull/6199 which will be merged and deployed 🔜 (I don't have a date yet).
