### ISSUE TITLE
Docker image is not providing the line of code

### ISSUE THREAD

**Issue by bhuvi11** [github/linguist#5477]
Hello Team,

The docker version of the code is not providing the line of code?
When i give docker run --rm -v C:/Users/bhuvaneshwari/eclipse-workspace/ecom-service:/CLI -w /CLI -t linguist_new github-linguist
99.74%  Java
0.26%   Dockerfile

It gives only the percentage not the line of code.
Can someone help me with this?

**Comment by lildude** [comment]
Do you mean the bytes of code, ie the new size column introduced in https://github.com/github/linguist/pull/5464 that was only merged two days ago?

If so, this is expected as a new release of Linguist (and gem that is installed [here in the Dockerfile](https://github.com/github/linguist/blob/1ccad01fb025f1418fd2d94be2e606e02a1d82e4/Dockerfile#L9)) hasn't been made since that PR was merged. 

I'm not going to be able to publish a new gem until next week at the earlier now.

If this isn't what you're referring to, what are you expecting to see that isn't being shown that is when run outside of docker?

**Comment by bhuvi11** [comment]
Hello , 

Yeah i meant the new size column.
Is there a roadmap to publish a docker image for lingist ?

**Comment by lildude** [comment]
https://github.com/github/linguist/issues/4613

**Comment by bhuvi11** [comment]
Cool

**Comment by lildude** [comment]
> Yeah i meant the new size column.

It does now:

```console
$ docker build --no-cache -t linguist .
[...]
$ docker run --rm -v $(pwd):$(pwd) -w $(pwd) -t linguist
66.81%  264172     Ruby
24.70%  97685      C
6.57%   25999      Go
1.29%   5098       Lex
0.32%   1257       Shell
0.31%   1212       Dockerfile

$
```
