### ISSUE TITLE
`*.tsx` files are not recognised as Typescript language

### ISSUE THREAD

**Issue by KnowsCount** [github/linguist#5485]
## Describe the bug

the `*.tsx` files are not counted into the Typescript language. I simply consider it a bug because come on, all project using both react and typescript contains `tsx` files and it just cannot be right if `tsx` files are not counted.

### Expected behaviour

For `*.tsx` files to be counted into Typescript or at least another language.

### Related discussion

I briefly looked through the issues and found none. nor does the discussion

### Additional notes

none.

**Comment by lildude** [comment]
> For `*.tsx` files to be counted into Typescript or at least another language.

They already are. Why do you think they're not?

I'm going to guess you reached this conclusion by clicking TypeScript in the side bar and saw no `.tsx` files. If so, you should have a TSX entry in the list of language on the left.

A bit more detail… 

TSX is technically a dialect of TypeScript and Linguist treats it as such but still groups it under TypeScript:

https://github.com/github/linguist/blob/ca8b0027028d6d2f42ebe7d347b55f7c30572393/lib/linguist/languages.yml#L5922-L5932

This means it'll be counted in the TypeScript total in your side bar but will be identified as TSX elsewhere like the search results seen when clicking TypeScript in the sidebar as search has no concept of grouping like Linguist does.

This has been in place for over 2 years when it was split out from TypeScript in https://github.com/github/linguist/pull/4511 in order to fix https://github.com/github/linguist/issues/4359 which ultimately was a syntax highlighting issue.

**Comment by KnowsCount** [comment]
ah I do see. I did miss the `tsx` entry in the left sidebar... sorry for asking this stupid question and labelling it a bug... and thank you. I'll close this for now.

**Comment by guocaoyi** [comment]
`.tsx` suffix are still not recognized as TypeScript languages

```txt
Version: 1.83.1
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
OS: Darwin x64 23.0.0
```

https://github.com/search?q=repo%3Aguocaoyi%2Fcreate-chrome-ext++language%3ATypeScript&type=code

**Comment by lildude** [comment]
@guocaoyi my last [comment](https://github.com/github-linguist/linguist/issues/5485#issuecomment-888041136) still applies.
