### ISSUE TITLE
GH formatting `linguist-language=Markdown` for ChangeLog incorrectly

### ISSUE THREAD

**Issue by sebres** [github/linguist#5799]
## Describe the bug

At some point fail2ban's ChangeLog set within `.gitattributes` as `ChangeLog linguist-language=Markdown` (initially in https://github.com/fail2ban/fail2ban/pull/3126/files) became an invalid formatting later - it looks like plaintext without any line feed or rather like a totally unformatted HTML.

Example:
- https://github.com/fail2ban/fail2ban/blob/bc075ea682a3e3678ac5449cb1baeb0420655e8d/ChangeLog
- https://github.com/fail2ban/fail2ban/blob/bc075ea682a3e3678ac5449cb1baeb0420655e8d/.gitattributes

### Expected behaviour
Correctly formatted Markdown layout for ChangeLog

### Observed behaviour
Not formatted layout as it would be "plain" HTML without new lines etc.

### Additional notes

I don't know whether it is some conflicting rule of ChangeLog layout only or whether it is some issue of GH (not a linguist) which avoid correct formatting of the layout.

Anyway, commenting out the entry in .gitattributes in https://github.com/fail2ban/fail2ban/commit/1e5d5a446acd5171daf22975cb972695953a80f0 "solves" the issue, but it looks again like [plain text document now](https://github.com/fail2ban/fail2ban/blob/master/ChangeLog).
Reverting this in my clone illustrates [how it looks wrong again](https://github.com/sebres/fail2ban/blob/master/ChangeLog).

**Comment by lildude** [comment]
Yup, this isn't really Linguist at play.

Markdown rendering is handled by the [`github/markup`](https://github.com/github/markup) library. Whilst it uses Linguist to detect languages, it doesn't however honour the `.gitattributes` overrides because it asks Linguist to look at the file in isolation [here](https://github.com/github/markup/blob/46908504f5099b15a88030749f0aeb52cd2f6799/lib/github/markup.rb#L95-L96) which means it'll only use one of these methods of determining the language and not consider the `.gitattributes` file at all:

https://github.com/github/linguist/blob/97bc889ce840208652bf09b45f3b7859de43fe8e/lib/linguist.rb#L63-L70

None of these strategies will detect your Changelog file as Markdown hence you get plaintext.

In order to get the file rendered as Markdown, you'll have to use one of these extensions:

https://github.com/github/linguist/blob/dea6d4733b4fd68c67d248bfd0cfc5e1fa3cfa29/lib/linguist/languages.yml#L3607-L3620

Or add a modeline like `<!-- vim: syntax=Markdown -->` to the file.

See https://github.com/github/markup/issues/1102 and https://github.com/github/markup/issues/1069 for old known issues around this.

**Comment by sebres** [comment]
OK, thx! 
Thus closed here as 3rd party issue.
