### ISSUE TITLE
Broken Liquid highlighting?

### ISSUE THREAD

**Issue by charlespwd** [github/linguist#5807]
## Describe the bug

It looks like the liquid markdown syntax is not turning the code into tokens. That is, I'd expect the following markdown to output something highlighted. 
```
 | ```liquid
 | {% for product in all_products %}
 |   <div>{{ product.featured_image }}</div>
 | {% endfor %}
 | ```
```

It's working in [lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=json&grammar_url=https%3A%2F%2Fgithub.com%2FShopify%2Fliquid-tm-grammar%2Fblob%2Fmain%2Fliquid.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FShopify%2Fliquid-tm-grammar%2Fblob%2Fmain%2Fshowcase.liquid&code=). But not on here:

```liquid
{% for product in all_products %}
  <div>{{ product.featured_image }}</div>
{% endfor %}
```

Which shows up as:
```
<pre>
{% for product in all_products %}
  &lt;div&gt;{{ product.featured_image }}&lt;/div&gt;
{% endfor %}
</pre>
```

### Expected behaviour

I'd expect the syntax to be highlighted the same way it is in lightshow. Something like:
```
<pre class="code">{% <span class="pl-k">for</span> <span class="pl-c1">product</span> <span class="pl-k">in</span> <span class="pl-c1">all_products</span> %}
  &lt;<span class="pl-ent">div</span>&gt;{{ <span class="pl-c1">product</span>.<span class="pl-smi">featured_image</span> }}&lt;/<span class="pl-ent">div</span>&gt;
{% <span class="pl-k">endfor</span> %}
</pre>
```

**Comment by lildude** [comment]
Ooof, this is happening because the grammar compiler is picking up the YAML format of the grammar which appears to be incomplete and doesn't highlight correctly as can be seen in [lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=yaml&grammar_url=https%3A%2F%2Fgithub.com%2FShopify%2Fliquid-tm-grammar%2Fblob%2Fmain%2Fliquid.YAML-tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FShopify%2Fliquid-tm-grammar%2Fblob%2Fmain%2Fshowcase.liquid&code=)

This is the result of the compiler running on that file:

```json
{
  "name": "Liquid HTML",
  "scopeName": "text.html.liquid",
  "patterns": [
    {
      "include": "#core"
    }
  ],
  "injections": {
    "L:meta.embedded.block.js, L:meta.embedded.block.css, L:meta.embedded.block.html, L:string.quoted": {
      "patterns": [
        {
          "include": "#injection"
        }
      ]
    }
  }
}
```

Whilst the repo has a JSON representation of the grammar, it's not in the location expected for JSON grammar files so is being ignored:

https://github.com/github/linguist/blob/6b02d3bd769d07d1fdc661ba9e37aad0fd70e2ff/tools/grammars/compiler/loader.go#L124-L125

**Comment by charlespwd** [comment]
Ha! Yeah we're reusing the repository of rules in two files. And the repository is processed because some of the regexes are too insane to be spelled out.

I think I'll just make them .yaml files and avoid the problem. IIRC I only used that extension because of we were heavily inspired by https://github.com/microsoft/TypeScript-TmLanguage. Didn't know it was a standard :see_no_evil:

**Comment by charlespwd** [comment]
Oh right. Non-standard location.

**Comment by charlespwd** [comment]
We'll have to wait for the next release for this to get picked up, eh?

**Comment by lildude** [comment]
> We'll have to wait for the next release for this to get picked up, eh?

Yup

**Comment by lildude** [comment]
Liquid highlighting is working again. I manually updated the compiled grammars used by our syntax highlighting service so we could get it working again without having to rush a new release.

I'm going to be making a 7.19.1 update to fix https://github.com/github/linguist/issues/5808 and will pull in an update to the Linguist grammar so everything is in sync across the board.
