### ISSUE TITLE
After registering new language, github shows language on repo main page, but not when clicking on that language

### ISSUE THREAD

**Issue by manwithafox** [github/linguist#5952]
## Describe the bug
Recently, _CAP CDS_ was added to the set of supported languages.
The language is now shown in repos containing corresponding files - on the main page e.g.
https://github.com/SAP-samples/cloud-cap-samples

But when clicking on the [_CAP CDS_ language](https://github.com/SAP-samples/cloud-cap-samples/search?l=cap-cds), the search states 
> We couldn’t find any code matching '' in [SAP-samples/cloud-cap-samples](https://github.com/SAP-samples/cloud-cap-samples)

and the box with **Languages** on the left also doesn't list _CAP CDS_.

### Expected behaviour
Like other languages contained in above mentioned repo, _CAP CDS_ search should list those files and the _CAP CDS_ language should be shown in the **Languages** box on the left.

### Additional notes
(Not sure how Linguist and GH play together, if this is a Linguist bug or rather some index problem on GH.)

Note: for forks, the languages on the main page are not even clickable. I tried with a fresh one but also some older.

**Comment by lildude** [comment]
This is not an issue with Linguist and nothing Linguist can do anything about.

You're looking at Search and its functionality which is completely independent of Linguist. It doesn't use Linguist. Instead it uses [go-enry](https://github.com/go-enry/go-enry) which pulls in the Linguist releases, however it tends to lag behind Linguist by a few weeks to months. It also requires our Search team to pull in the latest version as and when.

So any time you see a language missing from Search and search results, it's likely because of this and the only option is to wait for go-enry to update and for this to then be pulled into Search.

Closing as this is not a Linguist bug.

**Comment by manwithafox** [comment]
Thanks for clarification, Colin.

Cheers,
Christian
