### ISSUE TITLE
[new language] Github Action

### ISSUE THREAD

**Issue by chenrui333** [github/linguist#6203]
## Language name

Github Action

## URL of example repository
https://github.com/chenrui333/github-action-test

## URL of syntax highlighting grammar
https://github.com/chenrui333/github-action-test/blob/main/.github/workflows/display-github-context.yml
https://github.com/chenrui333/github-action-test/blob/main/.github/workflows/

## Most popular extensions
* `.yml` for github action workflow files
* `action.yml` for composite runs

## Additional details

It would be helpful if github action is its own language, and it would help write better github action configurations for every repo.

**Comment by chenrui333** [comment]
Sorry, need someone to update the issue label.

**Comment by Alhadis** [comment]
> It would be helpful if github action is its own language, and it would help write better github action configurations

Erh, how?

**Comment by lildude** [comment]
> It would be helpful if github action is its own language, and it would help write better github action configurations for every repo.

Making a "GitHub Actions" language will not help with this at all as you'll still be looking at plain text in YAML format... except now it'll have a language name of "GitHub Actions" instead of "YAML".

What's more, the GitHub UI already helps with editing your workflows: https://github.blog/2019-10-01-new-workflow-editor-for-github-actions/

Closing.
