### ISSUE TITLE
Add 'ansi" language for custom colors in markdown

### ISSUE THREAD

**Issue by spidertyler2005** [github/linguist#6277]
## URL of example repository

What does this mean?

## URL of syntax highlighting grammar

Don't know what this means. I am going to list this link:
https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html
since it gives a tutorial on the usage of ansi escape codes and lists a large number of them.

## Most popular extensions

Not sure what this is asking.  ANSI color codes are by default used in any terminal. Discord also has support for these codes within code blocks. It is extremely useful.

## Detected language

None. This is exclusively for markdown codeblocks. This will allow a temporary form of syntax highlighting for languages not yet included in linguist. For example, I am making my own programming language but syntax is changing a lot and thus it doesn't make sense to commit fully to any kind of highlighter yet.

## Example of ANSI language use in codeblocks

````
```ansi
[31;1mdefine [37mmain[30;1m() {
    [36mprintln[30;1m([32m"Hello World"[30;1m);
[30;1m}
[0m
```
````
**screenshot example from discord**
![image](https://user-images.githubusercontent.com/38941820/216796959-793e10d1-c21f-418f-b491-d94bbfa07a40.png)

## Why should this exist?

When creating custom programming languages, markup languages, file formats, etc it can be extremely useful to have some kind of syntax highlighting. Although this isn't the same as custom syntax highlighting, it provides an extremely useful temporary solution for people working on the previously mentioned projects. It would be invaluable for documentation! This also would be significantly easier than implementing repo specific highlighters (something github has ignored when it has been requested for years).

Sorry if this is the wrong place for this btw. As far as I can find, this is the only place you can request this sort of feature to github. I could be wrong ofc. Feel free to remove this Issue if I have put this in the wrong place.

**Comment by lildude** [comment]
This is outside of Linguist scope as its about interpretting the code you write in the code block which puts it into the realm of the code behind those code blocks which is [markup](https://github.com/github/markup). https://github.com/github/markup/issues/1440 seems like a very similar request.

As this is the wrong repo and an issue already exists, I'm going to close this issue. Feel free to contribute to the other issue if you want to.

**Comment by lildude** [comment]
> Is the issue simply that the way markup integrates with linguist makes "hiding" characters (e.g. based on the control sequences) impossible?

Not quite. Linguist does not interpret or provide any syntax highlighting functionality. All it does is provide the Textmate-compatible grammars (really just a bunch of regexes) that are used by one of the syntax highlighting engines GitHub uses and markup.

The syntax highlighting engines look at the strings as they appear and uses the grammars to wrap the strings in appropriate HTML tags for rendering the highlighting. No interpretation content is done at all. 

In order to get the ANSI sequences rendered and applied correctly, markup (or something else) would need to interpret the characters and replace them with the appropriate HTML to render the subsequent strings appropriately.

A good illustration is Mermaid files. Linguist provides the grammar so [this code view of the file](https://github.com/github-linguist/linguist/blob/master/samples/Mermaid/flowchart.mmd?short_path=f67a995) has syntax highlighting, however a completely different library is used to render that same content as this diagram:

```mermaid
flowchart LR
	A[Hard edge] -->|Link text| B(Round edge)
	B --> C{Decision}
	C -->|One| D[Result one]
	C -->|Two| E[Result two]
```

Linguist has no control over this, and it wouldn't for the interpretation of the ANSI sequences; that would be up to markup or some other library GitHub may use.
