### ISSUE TITLE
Delphi code misidentified as Pascal

### ISSUE THREAD

**Issue by Faq** [github/linguist#905]
Seems all delphi projects show as pascal now
 Example:
https://github.com/Faq/TXTGenerator
https://github.com/Gurux/Gurux.DLMS.Delphi

**Comment by arfon** [comment]
We have a couple of different ways to override language detection now in Linguist which is probably as good as we can do right now. Please take a look at these over here: https://github.com/github/linguist#overrides

**Comment by EarlGlynn** [comment]
I really do not understand this thread.  Why are there summaries by language of GitHub repositories when you refuse to put the right label on the repository?  You even refuse to let the authors put the right labels on the repository.  This "resolution" simply does not make any sense to me.

**Comment by nunopicado** [comment]
Still nothing on this?
arfon's suggestion was tried, but does not work.
If I add 

> *.pas linguist-language=Delphi

to the .gitattributes file, the language changes from Pascal to Component Pascal, which is another completely different language, which is neither Pascal nor Object Pascal/Delphi.

It's funny how people use github statistics to argument that Delphi does not show in the Top languages used today, when github doesn't even recognize the existence of the language.

Would it be so hard to make it work correctly?
I don't mind having to add a .gitattributes file, if it would only work!

**Comment by arfon** [comment]
@nunopicado - this is because `delphi` is [listed as an alias](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L658) for Component Pascal.

Probably the best thing we can do right now is to list Dephi as a language in [`languages.yml`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) but not add any extensions as we still don't have a way to reliably identify a Delphi project on a _per-file basis_.

Doing this would allow the overrides to work (`*.pas linguist-language=Delphi`) but little else :-\

**Comment by nunopicado** [comment]
Thanks arfon, for your reply.

I do think Delphi should be separated from Component Pascal, the same for Object Pascal.
Delphi and Object Pascal could be marked as alias to one another (one as a language, one as an alias, I don't really mind which is which). Even though there are different flavours of Object Pascal, at least it fits in the description.

There are some file extensions which are exclusive to Delphi. Those could be added.
The problem is with .pas files, which is a common extension.

It was mentioned that there must be something in the code to differentiate standard Pascal from Delphi/Object Pascal. Well, I guess there is.

Standard Pascal is not object oriented, so there are no classes.
Delphi, on the other hand, is heavily object oriented, so there will probably be not many .pas files which do not have the keywords Class or Interface.

Would that be enough to create an rule for linguist?

**Comment by arfon** [comment]
> Standard Pascal is not object oriented, so there are no classes.
Delphi, on the other hand, is heavily object oriented, so there will probably be not many .pas files which do not have the keyword Class.

Very possibly! Basically we need to be able to write a heuristic (a regular expression) that is applied on a per-file extension basis. Here's a good example for `.es` which is used by JavaScript and Erlang: https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L139-L145

@nunopicado - Would you be interested in attempting this in a Pull Request?

**Comment by nunopicado** [comment]
Strange as it may seem, I never used regular expressions! :)
But I'll give it a try. I'll check you example and try to create something that can differentiate .pas files.
I'll get back to you on this.
Thank you @arfon! ;)

**Comment by arfon** [comment]
> Strange as it may seem, I never used regular expressions! :)

Welcome to the dark side 😉

> I'll check you example and try to create something that can differentiate .pas files.
I'll get back to you on this.

👍 thanks. We can definitely help you get this polished up.

**Comment by nunopicado** [comment]
:+1:

**Comment by JazzMaster** [comment]
still un patched. seen as C++ and java when its clearly FPC sources for SDL.

**Comment by pchaigno** [comment]
@JazzMaster Could you open a separate issue with the appropriate details so that we can look into a fix?
